secondfile/objects/Account.object
<CustomObject>
    <fields>
        <fullName>ASE_ACNA__c</fullName>
        <description>Field  to capture ACNA value associated to ASE Product</description>
        <label>ASE ACNA</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ASE_Ordering_Type__c</fullName>
        <description>ASE Ordering Type Field for ASE Product</description>
        <label>ASE Ordering Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>None</fullName>
                    <default>true</default>
                    <label>None</label>
                </value>
                <value>
                    <fullName>ASR</fullName>
                </value>
                <value>
                    <fullName>WOT</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ASE_Product__c</fullName>
        <defaultValue>false</defaultValue>
        <label>ASE Product</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>No_Of_Active_BAN__c</fullName>
        <description>Roll Up Summary for Active BAN Count</description>
        <label>No. of Active BANs</label>
        <summaryFilterItems>
            <field>ASE_Billing_Account_Number__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </summaryFilterItems>
        <summaryForeignKey>ASE_Billing_Account_Number__c.Account_Name__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>No_Of_Active_CNM__c</fullName>
        <description>Rollup Summary for Active CNM</description>
        <label>No. of Active CNUMs</label>
        <summaryFilterItems>
            <field>ASE_Wholesale_Contract_Number__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </summaryFilterItems>
        <summaryForeignKey>ASE_Wholesale_Contract_Number__c.Account_Name__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
</CustomObject>

example/secondfile/objects/ASE_Wholesale_Contract_Number__c.object
<CustomObject>
    <fields>
        <fullName>Account_Name__c</fullName>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>ASE Wholesale Contract Number</relationshipLabel>
        <relationshipName>ASE_Wholesale_Contract_Number</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <label>ASE Wholesale Contract Number</label>
    <nameField>
        <label>CNUM #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ASE Wholesale Contract Number</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

secondfile/classes/ASEWholesaleContractNumberTriggerHandler.cls
public with sharing class ASEWholesaleContractNumberTriggerHandler extends SITriggerOperations.SITriggerImpl{

    public boolean isExecuted;
    public ASEWholesaleContractNumberTriggerHandler() 
    {
       isExecuted = true;
       
    }

    public override boolean onBeforeInsert(SObject[] newObjects) 
    {
        checkDuplicateName(newObjects, newObjects, true);
        return isExecuted;
    }
      public override boolean onAfterInsert(SObject[] newObjects) 
    {
       List<ASE_Wholesale_Contract_Number__c> newObjList=newObjects;
    //   updateASEProductOnAccount(newObjList[0].Account_Name__c);
        return true;
    }
    public override boolean onBeforeUpdate(SObject[] oldObjects,SObject[] newObjects,Map<Id,SObject> newObjectsMap )
    {
        checkDuplicateName(oldObjects, newObjects, false);
        return isExecuted;
    }
      public override boolean  onAfterUpdate(SObject[] oldObjects,SObject[] newObjects,Map<Id,SObject> newObjectsMap) 
    {
        List<ASE_Wholesale_Contract_Number__c> newObjList=newObjects;
        updateASEProductOnAccount(newObjList[0].Account_Name__c);
        return true;        
    }
    public void checkDuplicateName(SObject[] oldObjects, SObject[] updatedObjects, boolean isInsert){
        List<ASE_Wholesale_Contract_Number__c> newObjList = updatedObjects;
        List<ASE_Wholesale_Contract_Number__c> oldObjList = oldObjects;
        Map<String,object> ASEMap = new Map<String,object>();
        List<String> nameStr = new List<String>();
        for(integer i=0;i<newObjList.size();i++){
            if(((newObjList[i].name != oldObjList[i].name || newObjList[i].Active__c != oldObjList[i].Active__c) && newObjList[i].Active__c ) || (newObjList[i].Active__c && isInsert == true)){
                ASEMap.put(newObjList[i].name,newObjList[i]);
            }   
        }
        
        List<ASE_Wholesale_Contract_Number__c> ASEWholesaleContractNumList = new List<ASE_Wholesale_Contract_Number__c>();
        ASEWholesaleContractNumList = [Select Name, Account_Name__c, Active__c  from ASE_Wholesale_Contract_Number__c WHERE Name IN: ASEMap.keySet() AND Active__c =: true];
        
        for(ASE_Wholesale_Contract_Number__c ase: newObjList){
            if(ASEWholesaleContractNumList != null && ASEWholesaleContractNumList.size() > 0){
                ase.addError('The CNUM entered is already in the system, only unique CNUMs are allowed.');     
            } 
        }
    }
    /*
    Added as part of Sprint-29 US780973
    */
    public void updateASEProductOnAccount(String accId)
    {
      
      Account currentAccount=[select No_Of_Active_BAN__c,No_Of_Active_CNM__c,ASE_ACNA__c,ASE_Ordering_Type__c,ASE_Product__c from Account where id=: accId];            

        if(currentAccount.ASE_Product__c  )
        {
        List<ASE_Wholesale_Contract_Number__c> ASEWholesaleContractNumList =new List<ASE_Wholesale_Contract_Number__c>();
             ASEWholesaleContractNumList = [Select Name, Account_Name__c, Active__c  from ASE_Wholesale_Contract_Number__c WHERE Account_Name__c =: accId AND Active__c =: true];          
              if( ASEWholesaleContractNumList.size()== 0){
                currentAccount.ASE_Product__c=False;
                update currentAccount;
                }
        }
        
        
    }
}