secondfile/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Legal_Reviewer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Legal Reviewer</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts9</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Marketing_Consultant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Provider Directory Reviewer</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts8</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

example/secondfile/objects/Admin_Control__c.object
<CustomObject>
    <fields>
        <fullName>Provider_Directory_Reviewer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Provider Directory Reviewer</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Admin_Control</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Admin Control</label>
    <nameField>
        <displayFormat>AC-{0000}</displayFormat>
        <label>Admin Control Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Admin Control</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

secondfile/objects/Directory__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Directory Entries</relationshipLabel>
        <relationshipName>Directory_Entries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Additional_Information_Feedback__c</fullName>
        <label>Additional Information Feedback</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Approval_Timestamp__c</fullName>
        <label>Approval Timestamp</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Approver</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Directory_Entries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Auto_Approved__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Auto Approved</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>BufferToStoreMultiPickVal__c</fullName>
        <label>Search-Friendly Multi-Pick Val</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Company_Display_Name__c</fullName>
        <label>Company Display Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Connect_Tab_Feedback__c</fullName>
        <label>Contact Tab Feedback</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Demo_Video__c</fullName>
        <label>Demo Video</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>1200</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Details_Tab_Feedback__c</fullName>
        <label>Details Tab Feedback</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Display_On_Landing_Page__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Display On Landing Page</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Feedback_History_Additional_Information__c</fullName>
        <label>Feedback History-Additional Information</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Feedback_History_Contact__c</fullName>
        <label>Feedback History - Contact</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Feedback_History_Details__c</fullName>
        <label>Feedback History - Details</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Feedback_History_Overview__c</fullName>
        <label>Feedback History - Overview</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Feedback_History_Provider_Details__c</fullName>
        <label>Feedback History - Provider Details</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Full_Size_Logo__c</fullName>
        <label>Full-Size Logo Link</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Industries__c</fullName>
        <label>Industries</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Accounting</fullName>
                </value>
                <value>
                    <fullName>Aerospace</fullName>
                </value>
                <value>
                    <fullName>Agricultural</fullName>
                </value>
                <value>
                    <fullName>Architect</fullName>
                </value>
                <value>
                    <fullName>Automotive</fullName>
                </value>
                <value>
                    <fullName>Banking</fullName>
                </value>
                <value>
                    <fullName>Builders</fullName>
                </value>
                <value>
                    <fullName>Chemical</fullName>
                </value>
                <value>
                    <fullName>Communications</fullName>
                </value>
                <value>
                    <fullName>Education</fullName>
                </value>
                <value>
                    <fullName>Enterprise</fullName>
                </value>
                <value>
                    <fullName>Entertainment</fullName>
                </value>
                <value>
                    <fullName>Financial</fullName>
                </value>
                <value>
                    <fullName>Fortune 100</fullName>
                </value>
                <value>
                    <fullName>Government Federal</fullName>
                </value>
                <value>
                    <fullName>Government Local</fullName>
                </value>
                <value>
                    <fullName>Government State</fullName>
                </value>
                <value>
                    <fullName>Healthcare</fullName>
                </value>
                <value>
                    <fullName>Hospitality</fullName>
                </value>
                <value>
                    <fullName>Industrial</fullName>
                </value>
                <value>
                    <fullName>Insurance</fullName>
                </value>
                <value>
                    <fullName>International business</fullName>
                </value>
                <value>
                    <fullName>Legal</fullName>
                </value>
                <value>
                    <fullName>Manufacturing</fullName>
                </value>
                <value>
                    <fullName>Media</fullName>
                </value>
                <value>
                    <fullName>Petroleum</fullName>
                </value>
                <value>
                    <fullName>Professional services</fullName>
                </value>
                <value>
                    <fullName>Publishing</fullName>
                </value>
                <value>
                    <fullName>Real Estate</fullName>
                </value>
                <value>
                    <fullName>Retail</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Legal_Reviewer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Legal Reviewer</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Directory_Entries2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Logo_Link__c</fullName>
        <label>Logo Link</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Marketing_Consultant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Provider Directory Reviewer</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Directory_Entries1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Number_of_Employees__c</fullName>
        <label>Number of Employees</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Overview_Tab_Feedback__c</fullName>
        <label>Overview Tab Feedback</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Phone_Number_Secondary__c</fullName>
        <label>Secondary Phone Number</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Phone_Number__c</fullName>
        <label>Phone Number</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Primary_Email_Address__c</fullName>
        <label>Primary Email Address</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Provider_Details_Feedback__c</fullName>
        <label>Provider Details Feedback</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>National (U.S.)</fullName>
                </value>
                <value>
                    <fullName>West (U.S.)</fullName>
                </value>
                <value>
                    <fullName>South (U.S.)</fullName>
                </value>
                <value>
                    <fullName>Midwest (U.S.)</fullName>
                </value>
                <value>
                    <fullName>Northeast (U.S.)</fullName>
                </value>
                <value>
                    <fullName>North America</fullName>
                </value>
                <value>
                    <fullName>Europe</fullName>
                </value>
                <value>
                    <fullName>India/Southern Asia</fullName>
                </value>
                <value>
                    <fullName>Eastern Asia</fullName>
                </value>
                <value>
                    <fullName>Middle East &amp; Central Asia</fullName>
                </value>
                <value>
                    <fullName>Central &amp; South America</fullName>
                </value>
                <value>
                    <fullName>Africa</fullName>
                </value>
                <value>
                    <fullName>Australia/Oceania</fullName>
                </value>
                <value>
                    <fullName>Global</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Restrict_Validation_Rule__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Restrict Validation Rule</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Secondary_Email_Address__c</fullName>
        <label>Secondary Email Address</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Solutions__c</fullName>
        <label>Solutions</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Network Services</fullName>
                </value>
                <value>
                    <fullName>Mobile Services</fullName>
                </value>
                <value>
                    <fullName>Cloud &amp; Hosting</fullName>
                </value>
                <value>
                    <fullName>Application Services</fullName>
                </value>
                <value>
                    <fullName>Managed Services</fullName>
                </value>
                <value>
                    <fullName>Security</fullName>
                </value>
                <value>
                    <fullName>Disaster Recovery</fullName>
                </value>
                <value>
                    <fullName>IT Support</fullName>
                </value>
                <value>
                    <fullName>Conference Call Services</fullName>
                </value>
                <value>
                    <fullName>Billing</fullName>
                </value>
                <value>
                    <fullName>Financing</fullName>
                </value>
                <value>
                    <fullName>Taxation</fullName>
                </value>
                <value>
                    <fullName>Software Solutions</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Pending Approval</fullName>
                </value>
                <value>
                    <fullName>Pending Legal Approval</fullName>
                </value>
                <value>
                    <fullName>Review Requested</fullName>
                </value>
                <value>
                    <fullName>Published</fullName>
                </value>
                <value>
                    <fullName>Archived</fullName>
                </value>
                <value>
                    <fullName>Deleted</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Summary__c</fullName>
        <label>Summary</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Tagline__c</fullName>
        <label>Tagline</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Website__c</fullName>
        <label>Website</label>
        <type>Url</type>
    </fields>
    <label>Directory</label>
    <nameField>
        <displayFormat>DE-{0000}</displayFormat>
        <label>Directory Entry</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Directory Entries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

example/secondfile/classes/SIDirectoryTriggerHandler.cls
/* 
 Name: SITriggerOperations.SITriggerImpl
 Type: Class 
 
 Description: 
 */ 
public with sharing class SIDirectoryTriggerHandler extends SITriggerOperations.SITriggerImpl {
    
    public boolean isExecuted ;

    //Default cons
/* 
 Name: SIDirectoryTriggerHandler
 Description: 
 */ 
    public SIDirectoryTriggerHandler() {
        isExecuted = true;
    }
    
    //An Overridden method
/* 
 Name: onBeforeInsert
 Description: 
 */ 
    public override boolean onBeforeInsert(SObject[] newObjects) {
        try {
                updateDirectoryFields(newObjects);
                DirectoryAutoApproval(newObjects);
                CopyFieldsonDirectory(newObjects);
                     
        } catch(Exception excep) {
            isExecuted = false;
            throw excep;
        }
        return isExecuted;
    }
    
    //An Overridden method
/* 
 Name: onAfterInsert
 Description: 
 */ 
    public override boolean onAfterInsert(SObject[] newObjects) {
        try {  
              updateAccountFields(newObjects);
              checkDirectoryEntryNew(newObjects);
              DirectoryApproval(newObjects,newObjects,true); 
        } catch(Exception excep) {
            isExecuted = false;
            throw excep;
        }
        return isExecuted;
    }
    
    //An Overridden method
/* 
 Name: onBeforeUpdate
 Description: 
 */ 
    public override boolean onBeforeUpdate(SObject[] oldObjects,SObject[] newObjects,Map<Id,SObject> newObjectsMap) {
        try {
                updateDirectoryFields(newObjects);
                updateCurrentApproverAndTimeStamp(oldObjects,newObjects);
                CopyFieldsonDirectory(newObjects);
                UpdateDirectoryAutoApproval(newObjects,oldObjects);
        } catch(Exception excep) {
            isExecuted = false;
            throw excep;
        }
        return isExecuted;
    }
    
/* 
 Name: onAfterUpdate
 Description: 
 */ 
    public override boolean onAfterUpdate(SObject[] oldObjects,SObject[] newObjects,Map<Id,SObject> newObjectsMap ){
        try
        {
            checkDirectoryEntryNew(newObjects);
            DirectoryApproval(newObjects,oldObjects,false);
        }
        catch(Exception e){
            //System.Debug(UtilityConstant.EXCEPTIONHERE_x+e.getMessage());
            isExecuted=false;
            throw e;
        }
        return isExecuted;    
    }
    
    //Business logic to update Marketing Consultant and Legal Reviewer when Account is Populated
    public void updateDirectoryFields(SObject[] newObjects)
    {
        try{
        list<Directory__c> newList = newObjects;
        set<Id> accountId = new set<Id>();
         
        for(Directory__c directory : newList)
        {
            if(directory.Account__c != null)
            {
                accountId.add(directory.Account__c);
            }
            //Business logic to update all multiselect picklist values to "BufferToStoreMultiPickVal" field such that field will be searchable in SOSL query.
            if(directory.Status__c==SIConstants.Status_Published)
            {
                directory.BufferToStoreMultiPickVal__c=directory.Industries__c+'\n'+directory.Region__c+'\n'+directory.Solutions__c+'\n'+directory.Number_of_Employees__c;
            }
        }
        
        list<Account> accList = [Select Id,Marketing_Consultant__c,Legal_Reviewer__c From Account Where Id IN :accountId];
        Admin_Control__c admincontrol = [Select Provider_Directory_Reviewer__c From Admin_Control__c LIMIT 1 ];
        
        for(Directory__c directory : newList)
        {
            for(Account account : accList)
            {
                if(directory.Account__c!=null && directory.Account__c == account.Id)
                {
                   if(account.Marketing_Consultant__c!=null ){
                    directory.Marketing_Consultant__c=account.Marketing_Consultant__c;
                    }else{
                        directory.Marketing_Consultant__c = admincontrol.Provider_Directory_Reviewer__c;
                    }
                  
                    directory.Legal_Reviewer__c=account.Legal_Reviewer__c;                    
                }                             
            }
        }
    }
    catch(Exception e){
ATTException.logException( e.getTypeName(), ATTException.constructExceptionMessageString(e));
}
}
    
    //Business Logic To update Provider Directory Reviewer Field on Account From Admin Control if Directory Status is Pending Approval
    
/* 
 Name: updateAccountFields
 Description: 
 */ 
    public void updateAccountFields(SObject[] newObjects){
    try{
        list<Directory__c> newLists = newObjects;
        set<Id> accountId = new set<Id>();
         
        for(Directory__c directory : newLists)
        {
            if(directory.Account__c != null)
            {
                accountId.add(directory.Account__c);
            }        
        }
         list<Account> accLists = [Select Id,Marketing_Consultant__c From Account Where Id IN :accountId and Marketing_Consultant__c=:null];
        
            if(accLists!=null ){ 
            
                 Admin_Control__c admincontrols = [Select Provider_Directory_Reviewer__c From Admin_Control__c LIMIT 1 ];
             
                 for(Account account : accLists){
                   account.Marketing_Consultant__c = admincontrols.Provider_Directory_Reviewer__c;
                 }            
                 update accLists;     
           }    
         }
         catch(Exception e){
ATTException.logException( e.getTypeName(), ATTException.constructExceptionMessageString(e));
}
}
    
    //Business logic to update Approver and Approval Timestamp when status is changed to Review Requested or Published
    public void updateCurrentApproverAndTimeStamp(SObject[] oldObjects,SObject[] newObjects)
    {
        try{
        list<Directory__c> oldDirectory = oldObjects;
        list<Directory__c> newDirectory = newObjects;
        
        for (Integer i=0; i<newDirectory.size(); i++)
        {
            if((newDirectory[i].Status__c!=null && oldDirectory[i].Status__c!=null) && (oldDirectory[i].Status__c==SIConstants.Status_Pending_Approval ||oldDirectory[i].Status__c==SIConstants.Status_Pending_Legal_Approval) && (newDirectory[i].Status__c==SIConstants.Status_Review_Requested || newDirectory[i].Status__c==SIConstants.Status_Published))
            {
                newDirectory[i].Approver__c=UserInfo.getUserId(); 
                newDirectory[i].Approval_Timestamp__c = system.Now();
            }
            //Business logic to update "Display On Landing Page" to false when status change from published to another status.
            if(oldDirectory[i].Status__c==SIConstants.Status_Published && newDirectory[i].Status__c != SIConstants.Status_Published && newDirectory[i].Display_On_Landing_Page__c)
            {
                newDirectory[i].Display_On_Landing_Page__c = false;
            }
        }
    }
    catch(Exception e){
ATTException.logException( e.getTypeName(), ATTException.constructExceptionMessageString(e));
}
}
    //Business logic to make sure an SP contains only one dierectory record with status Published. If there are any other records for that SP with satus
    //published then we are archieving the old records and new record will remian same with status published.
    public void checkDirectoryEntryNew(SObject[] newObjects)
    {
        try{
        list<Directory__c> newDirectory = newObjects;
        set<Id> AccountIds = new Set<Id>();
        set<Id> DirectoryIds  = new Set<Id>();
        list<Directory__c> updateoldDirectory = new list<Directory__c>();
        
        for(Directory__c D: newDirectory){
            if((D.Status__c==SIConstants.Status_Published || D.Status__c==SIConstants.Status_Published_Pending_New_Version)&& D.Account__c!=null){
                    AccountIds.add(D.Account__c);
                    DirectoryIds.add(D.Id);
                }           
            }
        
        updateoldDirectory = [Select Id,Account__c,Status__c from Directory__c where (Status__c=:SIConstants.Status_Published or Status__c=:SIConstants.Status_Published_Pending_New_Version) and Account__c IN:AccountIds and Id Not IN:DirectoryIds];
        
        for(Directory__c updateDirec: updateoldDirectory){
            updateDirec.Restrict_Validation_Rule__c = True;
            updateDirec.Status__c=SIConstants.Status_Archived;
        }
            
        if(updateoldDirectory!=null){
            update updateoldDirectory;
        }
    }
    catch(Exception e){
ATTException.logException( e.getTypeName(), ATTException.constructExceptionMessageString(e));
}
}
    
    public void CopyFieldsonDirectory (SObject[] updatedObjects)
    {
        try{
       List<Directory__c> LNewlist = updatedObjects;
       for(Integer i=0;i<LNewlist.size();i++)
       {  
          if(LNewlist[i].Additional_Information_Feedback__c!=null)
              {
               if(LNewlist[i].Feedback_History_Additional_Information__c!=null){
                LNewlist[i].Feedback_History_Additional_Information__c = '['+Datetime.now().format()+ ']: \n '+ LNewlist[i].Additional_Information_Feedback__c+'\n\n'+LNewlist[i].Feedback_History_Additional_Information__c;
                }
                else{
                LNewlist[i].Feedback_History_Additional_Information__c = '['+Datetime.now().format()+ ']: \n'+ LNewlist[i].Additional_Information_Feedback__c;
                }
               // LNewlist[i].Additional_Information_Feedback__c=null;
                
                if(LNewlist[i].Feedback_History_Additional_Information__c.Length()>32700){
                
                    LNewlist[i].Feedback_History_Additional_Information__c =LNewlist[i].Feedback_History_Additional_Information__c.substring(0,32700);
         
                }
            }
         
         if(LNewlist[i].Connect_Tab_Feedback__c!=null)
              {
               if(LNewlist[i].Feedback_History_Contact__c!=null){
                LNewlist[i].Feedback_History_Contact__c = '['+Datetime.now().format()+ ']: \n '+ LNewlist[i].Connect_Tab_Feedback__c +'\n\n'+LNewlist[i].Feedback_History_Contact__c;
                }
                else{
                LNewlist[i].Feedback_History_Contact__c = '['+Datetime.now().format()+ ']: \n'+ LNewlist[i].Connect_Tab_Feedback__c;
                }
               // LNewlist[i].Connect_Tab_Feedback__c =null;
                          
                if(LNewlist[i].Feedback_History_Contact__c.Length()>32700){
                
                    LNewlist[i].Feedback_History_Contact__c =LNewlist[i].Feedback_History_Contact__c.substring(0,32700);
         
                }
            }   
         
        if(LNewlist[i].Details_Tab_Feedback__c!=null)
              {
               if(LNewlist[i].Feedback_History_Details__c!=null){
                LNewlist[i].Feedback_History_Details__c = '['+Datetime.now().format()+ ']: \n '+ LNewlist[i].Details_Tab_Feedback__c +'\n\n'+LNewlist[i].Feedback_History_Details__c;
                }
                else{
                LNewlist[i].Feedback_History_Details__c = '['+Datetime.now().format()+ ']: \n'+ LNewlist[i].Details_Tab_Feedback__c;
                }
               // LNewlist[i].Details_Tab_Feedback__c =null;
                
                if(LNewlist[i].Feedback_History_Details__c.Length()>32700){
                
                    LNewlist[i].Feedback_History_Details__c =LNewlist[i].Feedback_History_Details__c.substring(0,32700);
         
                }
            }   
            
          if(LNewlist[i].Overview_Tab_Feedback__c!=null)
              {
               if(LNewlist[i].Feedback_History_Overview__c!=null){
                LNewlist[i].Feedback_History_Overview__c = '['+Datetime.now().format()+ ']: \n '+ LNewlist[i].Overview_Tab_Feedback__c +'\n\n'+LNewlist[i].Feedback_History_Overview__c;
                }
                else{
                LNewlist[i].Feedback_History_Overview__c = '['+Datetime.now().format()+ ']: \n'+ LNewlist[i].Overview_Tab_Feedback__c;
                }
               // LNewlist[i].Overview_Tab_Feedback__c =null;
                        
                if(LNewlist[i].Feedback_History_Overview__c.Length()>32700){
                
                    LNewlist[i].Feedback_History_Overview__c =LNewlist[i].Feedback_History_Overview__c.substring(0,32700);
         
                }
            }    
        
          if(LNewlist[i].Provider_Details_Feedback__c!=null)
              {
               if(LNewlist[i].Feedback_History_Provider_Details__c!=null){
                LNewlist[i].Feedback_History_Provider_Details__c = '['+Datetime.now().format()+ ']: \n '+ LNewlist[i].Provider_Details_Feedback__c +'\n\n'+LNewlist[i].Feedback_History_Provider_Details__c;
                }
                else{
                LNewlist[i].Feedback_History_Provider_Details__c = '['+Datetime.now().format()+ ']: \n'+ LNewlist[i].Provider_Details_Feedback__c;
                }
               // LNewlist[i].Provider_Details_Feedback__c =null;
                                
                if(LNewlist[i].Feedback_History_Provider_Details__c.Length()>32700){
                
                    LNewlist[i].Feedback_History_Provider_Details__c =LNewlist[i].Feedback_History_Provider_Details__c.substring(0,32700);
         
                }
            }    
        
       }
       
       
   }
   catch(Exception e){
ATTException.logException( e.getTypeName(), ATTException.constructExceptionMessageString(e));
}
}
    
/* 
 Name: DirectoryApproval
 Description: 
 */ 
    public void DirectoryApproval(SObject[] newObjects,SObject[] oldObjects,Boolean dirInsert){
try{        
    List<Directory__c> PDNewList =newObjects;
    List<Directory__c> PDOldList =oldObjects;
    
    if(dirInsert){
    
        for(Directory__c D:PDNewList){
        
            if(D.Status__c == SIConstants.Status_Pending_Approval && D.Marketing_Consultant__c!=null && D.Legal_Reviewer__c!=null){
                Approval.ProcessSubmitRequest req = new Approval.ProcessSubmitRequest();
                req.setComments('Submitted for approval. Please approve.');
                req.setObjectId(D.Id);
                //req.setObjectId(Trigger.old[i].Id);
                // submit the approval request for processing
                Approval.ProcessResult result = Approval.process(req);
                // display if the reqeust was successful
            }
        }
    }
    
    else{
            for (Integer i = 0; i < PDNewList.size(); i++) {
                if (PDNewList[i].Status__c == SIConstants.Status_Pending_Approval && PDNewList[i].Status__c !=PDOldList[i].Status__c && PDNewList[i].Marketing_Consultant__c!=null && PDNewList[i].Legal_Reviewer__c!=null) {
                    
                    // create the new approval request to submit
                    Approval.ProcessSubmitRequest req = new Approval.ProcessSubmitRequest();
                    req.setComments('Submitted for approval. Please approve.');
                    req.setObjectId(PDNewList[i].Id);
                    // submit the approval request for processing
                    Approval.ProcessResult result = Approval.process(req);  // display if the reqeust was successful                           
           }
         }
       }  
    }
    catch(Exception e){
ATTException.logException( e.getTypeName(), ATTException.constructExceptionMessageString(e));
}
}
/* 
 Name: DirectoryAutoApproval
 Description: 
 */ 
    public void DirectoryAutoApproval(SObject[] newObjects){  
try{    
        List<Directory__c> directorylist = newObjects;
        List<Directory__c> DirDBList = new List<Directory__c>();
        set<Id> AccountId = new set<Id>();
        Map<Id,Directory__c> ACMap=new Map<Id,Directory__c>();
     
        for(Directory__c directory:directorylist ){
            AccountId.add(directory.Account__c);
        }
        
        if(!AccountId.isEmpty()&& AccountId!=null){
        
         DirDBList =  [Select Logo_Link__c,Marketing_Consultant__c,Approval_Timestamp__c,Demo_Video__c,Company_Display_Name__c,Tagline__c,Summary__c,Description__c,Account__c,Full_Size_Logo__c,Phone_Number_Secondary__c from Directory__c where Account__c IN :Accountid AND Status__c IN ('Published','Archived')  order by  LastModifiedDate desc ]; 
        
        }
        if(!DirDBList.isEmpty()&& DirDBList!=null){
            for(Directory__c DB :DirDBList ){
                if(ACMap.get(DB.Account__c)==null)
                {
                    ACMap.put(DB.Account__c,DB);
                }
             }
             for(Directory__c dir:directorylist){
                  if(ACMap.get(dir.Account__c)!=null){
                    if(dir.Company_Display_Name__c==ACMap.get((dir.Account__c)).Company_Display_Name__c 
                    && dir.Status__c ==SIConstants.Status_Pending_Approval
                    && dir.Tagline__c==ACMap.get((dir.Account__c)).Tagline__c
                    && dir.Logo_Link__c==ACMap.get((dir.Account__c)).Logo_Link__c 
                    && dir.Demo_Video__c==ACMap.get((dir.Account__c)).Demo_Video__c 
                    && dir.Summary__c==ACMap.get((dir.Account__c)).Summary__c 
                    && dir.Description__c==ACMap.get((dir.Account__c)).Description__c
                    && dir.Full_Size_Logo__c==ACMap.get((dir.Account__c)).Full_Size_Logo__c)                   
                    {
                        dir.Status__c=SIConstants.Status_Published;
                        dir.Approver__c = ACMap.get((dir.Account__c)).Marketing_Consultant__c;
                        dir.Approval_Timestamp__c = ACMap.get((dir.Account__c)).Approval_Timestamp__c;
                        dir.Auto_Approved__c = true;
                    }
                }
             }
        }
   }
   catch(Exception e){
ATTException.logException( e.getTypeName(), ATTException.constructExceptionMessageString(e));
}
}

/* 
 Name: UpdateDirectoryAutoApproval
 Description: 
 */ 
public void UpdateDirectoryAutoApproval(SObject[] newObject,SObject[] oldObject){
    try{
            List<Directory__c> directorynewlist = newObject;
            List<Directory__c> directoryoldlist = oldObject;
            List<Directory__c> DirDBList = new List<Directory__c>();
            set<Id> AccountId = new set<Id>();
            for(Directory__c directory : directorynewlist)
            {
                AccountId.add(directory.Account__c);
            }
            if(!AccountId.isEmpty() && AccountId!=null)
            {
                DirDBList = [Select Region__c,Number_of_Employees__c,Solutions__c,Primary_Email_Address__c,Secondary_Email_Address__c,Website__c,Phone_Number__c,City__c,State__c,Country__c,Industries__c,Request_More_Information__c,Account__c from Directory__c where Account__c IN :Accountid AND Status__c IN ('Published')  order by  LastModifiedDate desc ]; 
            }
            if(!DirDBList.isEmpty()&&DirDBList != null){
              for (Integer i=0; i<directorynewlist.size(); i++)
              {
                if((directorynewlist[i].Region__c != directoryoldlist[i].Region__c) 
                 ||(directorynewlist[i].Number_of_Employees__c != directoryoldlist[i].Number_of_Employees__c)
                 ||(directorynewlist[i].Solutions__c != directoryoldlist[i].Solutions__c) 
                 ||(directorynewlist[i].Primary_Email_Address__c != directoryoldlist[i].Primary_Email_Address__c) 
                 ||(directorynewlist[i].Secondary_Email_Address__c != directoryoldlist[i].Secondary_Email_Address__c)
                 ||(directorynewlist[i].Website__c != directoryoldlist[i].Website__c)
                 ||(directorynewlist[i].Phone_Number__c != directoryoldlist[i].Phone_Number__c)
                 ||(directorynewlist[i].City__c != directoryoldlist[i].City__c)
                 ||(directorynewlist[i].State__c != directoryoldlist[i].State__c)
                 ||(directorynewlist[i].Country__c != directoryoldlist[i].Country__c)
                 ||(directorynewlist[i].Industries__c != directoryoldlist[i].Industries__c)
                 ||(directorynewlist[i].Request_More_Information__c != directoryoldlist[i].Request_More_Information__c))                
                {
                    directorynewlist[i].Status__c =SIConstants.Status_Published;
                    directorynewlist[i].Auto_Approved__c = true;
                    
                }
            }          
         }
     }
     catch(Exception e){
ATTException.logException( e.getTypeName(), ATTException.constructExceptionMessageString(e));
}
}
 }