secondfile/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Billing_Address__c</fullName>
        <label>Billing Street</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Billing_City__c</fullName>
        <label>Billing City</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Billing_Same_as_Company_Address__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>If the Billing Address is the same as Company Address check this box</inlineHelpText>
        <label>Same as Company Address</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Billing_State__c</fullName>
        <label>Billing State/Province</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Billing_Zip_Code__c</fullName>
        <label>Billing Zip/Postal Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MRA_Number__c</fullName>
        <label>MRA Number</label>
        <length>30</length>
        <type>Text</type>
    </fields>
</CustomObject>

example/secondfile/objects/Certification__c.object
<CustomObject>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Certifications</relationshipLabel>
        <relationshipName>Certifications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Who_Passed__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Who Passed</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Certifications</relationshipLabel>
        <relationshipName>Certification_Trainings</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Certification</label>
    <nameField>
        <displayFormat>C-{000000}</displayFormat>
        <label>Certification ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Certifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

example/secondfile/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Primary_Contact__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Portal Administrator</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Adminstrative</fullName>
                </value>
                <value>
                    <fullName>Alternate Portal Admin</fullName>
                </value>
                <value>
                    <fullName>API Contact</fullName>
                </value>
                <value>
                    <fullName>Architect/IT Lead Contact</fullName>
                </value>
                <value>
                    <fullName>CEO</fullName>
                </value>
                <value>
                    <fullName>CFO</fullName>
                </value>
                <value>
                    <fullName>Contact for Notices</fullName>
                </value>
                <value>
                    <fullName>COO</fullName>
                </value>
                <value>
                    <fullName>Fieldglass Administrator</fullName>
                </value>
                <value>
                    <fullName>Finance</fullName>
                </value>
                <value>
                    <fullName>Main Contact</fullName>
                </value>
                <value>
                    <fullName>Marketing</fullName>
                </value>
                <value>
                    <fullName>MDF Management</fullName>
                </value>
                <value>
                    <fullName>Mobility Lead</fullName>
                </value>
                <value>
                    <fullName>NOC</fullName>
                </value>
                <value>
                    <fullName>Operations</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Owner</fullName>
                </value>
                <value>
                    <fullName>Portal Administrator</fullName>
                </value>
                <value>
                    <fullName>President</fullName>
                </value>
                <value>
                    <fullName>Primary Billing Contact</fullName>
                </value>
                <value>
                    <fullName>Provisioning Contact</fullName>
                </value>
                <value>
                    <fullName>Sales</fullName>
                </value>
                <value>
                    <fullName>Training</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SIDeleteContact__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Deleting the Created Contact from Lead Conversion</description>
        <label>SIDeleteContact</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>isconverted__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This intent of this field is to indicated when the associated lead has been converted into an account</description>
        <label>isconverted</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

secondfile/objects/Credit_Validation__c.object
<CustomObject>
    <fields>
        <fullName>SP_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SP Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Credit Validations</relationshipLabel>
        <relationshipName>Credit_Validations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SP_Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SP Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Credit Validations</relationshipLabel>
        <relationshipName>Credit_Validations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Credit Validation</label>
    <nameField>
        <displayFormat>CV-{000000}</displayFormat>
        <label>Credit Validation ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Credit Validations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

secondfile/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Additional_information__c</fullName>
        <label>Bus Dev Activity Log</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Billing_Address__c</fullName>
        <label>Billing Address</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Billing_City__c</fullName>
        <label>Billing City</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Billing_Same_as_Company_Address__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>If the Billing Address is the same as Company Address check this box</inlineHelpText>
        <label>Same as Company Address</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Billing_State__c</fullName>
        <label>Billing State</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Billing_Zip_Code__c</fullName>
        <label>Billing Zip Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Bus_Dev_Comment__c</fullName>
        <description>New Feild Dec Release</description>
        <label>Bus Dev Comment</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Business_Development_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Business Development Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Leads1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>How_did_you_learn_about_AT_T_Partner_Exc__c</fullName>
        <label>How did you learn about Partner Exchange</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Event/Tradeshow</fullName>
                </value>
                <value>
                    <fullName>Email</fullName>
                </value>
                <value>
                    <fullName>Online</fullName>
                </value>
                <value>
                    <fullName>Another Solution Provider</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Webinar</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>MRA_Executed_Date__c</fullName>
        <label>MRA Executed Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>MRA_Number__c</fullName>
        <description>MRA Number assigned to an Account</description>
        <displayFormat>MA{0000000}UA</displayFormat>
        <label>MRA Number</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>Other_Method__c</fullName>
        <label>Source Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

example/secondfile/objects/Related_Documents__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Related_Documents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipName>Related_Documents</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Related Note</label>
    <nameField>
        <displayFormat>N-{0000}</displayFormat>
        <label>Related Documents Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Related Notes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

example/secondfile/objects/Source__c.object
<CustomObject>
    <description>Contains the initial details for every marketing interaction with an SP</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup relation  with Account</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Lead_Sources</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>If_Other_please_specify__c</fullName>
        <label>If Other, please specify</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Initial_Source__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Initial Source</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipName>Lead_Sources</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Source_Type__c</fullName>
        <label>Source Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Webinar</fullName>
                </value>
                <value>
                    <fullName>Event/Tradeshow</fullName>
                </value>
                <value>
                    <fullName>List</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Online</fullName>
                </value>
                <value>
                    <fullName>Email</fullName>
                </value>
                <value>
                    <fullName>Another Solution Provider</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Validation_Flag__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Validation Flag</label>
        <type>Checkbox</type>
    </fields>
    <label>Source</label>
    <nameField>
        <displayFormat>LS-{00000}</displayFormat>
        <label>Source ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

secondfile/classes/SILeadTriggerHandler.cls
/* 
 Name: SITriggerOperations.SITriggerImpl
 Type: Class 
 
 Description: 
 */ 
public with sharing class SILeadTriggerHandler extends SITriggerOperations.SITriggerImpl {
    
    public boolean isExecuted ;

    //Default cons
/* 
 Name: SILeadTriggerHandler
 Description: 
 */ 
    public SILeadTriggerHandler() {
        isExecuted = true;
    }
    
/* 
 Name: onBeforeUpdate
 Description: 
 */ 
       public override boolean onBeforeUpdate(SObject[] oldObjects, SObject[] updatedObjects, Map<Id, SObject>  newObjectsMap )  {
        try {
            
            Leadcreditcheckconversion(updatedObjects);
            leadSourceEnhancements(oldObjects,updatedObjects,false);
            leadBusinessDevelopmentOwner(oldObjects,updatedObjects);
            Leadwithassociatedcontacts(updatedObjects);
            String obj=UtilityConstant.LEAD;
            String event=UtilityConstant.STATIC_UPDATE;
            SIWFEngineUtility.getInstance().Rulescoringengine(obj,event,oldObjects,updatedObjects);
            leadBillingInformation(updatedObjects);
            CopyFieldsonLead(updatedObjects);
                
        } catch(Exception excep) {
            isExecuted = false;
            throw excep;
        }
        return isExecuted;
    }
    
/* 
 Name: onBeforeInsert
 Description: 
 */ 
     public override boolean onBeforeInsert(SObject[] updatedObjects)  {
        try {
            String obj=UtilityConstant.LEAD;
            String event=UtilityConstant.STATIC_INSERT;
            SIWFEngineUtility.getInstance().Rulescoringengine(obj,event,updatedObjects,updatedObjects);
            leadBillingInformation(updatedObjects);
            CopyFieldsonLead(updatedObjects);
            leadSourceEnhancements(null,updatedObjects,true);
            
        } catch(Exception excep) {
            isExecuted = false;
            throw excep;
        }
        return isExecuted;
    }
    
/* 
 Name: onAfterUpdate
 Description: 
 */ 
    public override boolean onAfterUpdate(SObject[] oldObjects, SObject[] updatedObjects, Map<Id, SObject>  newObjectsMap )  {
    
    try {
            
            //DeleteContact(updatedObjects);
                
        } catch(Exception excep) {
            isExecuted = false;
            throw excep;
        }
        return isExecuted;
    
    }
    
    
/* 
 Name: Leadcreditcheckconversion
 Description: 
 */ 
   public void leadcreditcheckconversion (SObject[] updatedObjects){
        
    List<Lead> leadNewlist = updatedObjects;
    List<Credit_Validation__c> cVList=new List<Credit_Validation__c>();
    List<Certification__c> cFList=new List<Certification__c>();
    List<Related_Documents__c> docList=new List<Related_Documents__c>();
    List<Contact> contactList=new List<Contact>();
    List<Account> accountList = new List<Account>();
    List<Contact> contactDeleteList=new List<Contact>();
    List<Source__c> sourceList = new List<Source__c>();
    Map<Id,Id> leadMap = new Map<Id,Id>();
    List<ID> convertIDs=new List<ID>();
    List<ID> convertAccIDs=new List<ID>();
    RecordType recordtype= [Select r.SobjectType, r.Name, r.Id From RecordType r where r.SobjectType='Contact' and r.Name='Standard Contact'];
       
    //getting the Lead IDs which converted to Account & also creating Map between Lead ID,ConvertedAccountID
        for (lead LL:leadNewlist)
        {
          if (LL.isConverted)
           {
                convertIDs.add(LL.id);
                convertAccIDs.add(LL.ConvertedAccountID);
                LeadMap.put(LL.id,LL.ConvertedAccountID);

           }
        }  
        //getting the CV & CF & LeadSourceList list which needs to update.
        CVList = [select id,SP_Lead__c,SP_Account__c from Credit_Validation__c v where SP_Lead__c in :convertIDs];
        CFList = [select id,Lead__c,Who_Passed__c from Certification__c v where Lead__c in :convertIDs];
        DocList =[select id,Lead__c,Account__c from Related_Documents__c where Lead__c in : convertIDs];
        ContactList=[select id,Lead__c,AccountId  from Contact where Lead__c in :convertIDs];
        accountList=[Select ID,Description,MRA_Number__c from Account where ID IN:convertAccIDs]; 
        ContactDeleteList=[select id,Lead__c,AccountId  from Contact where Lead__c=null and AccountId in :convertAccIDs];
        SourceList=[select id,Lead__c,Account__c from Source__c where Lead__c in : convertIDs];
       //Assigning ConvertedAccountID to CV & CF
       
       /** Below code added to fix the ORT defect related to lead to account conversion**/
        Map<Id,Id> parentAccountMap = new Map<Id,Id>();
             
        for(Account acc: accountList){
            parentAccountMap.put(acc.Id,acc.Id);                    
        }
        if(parentAccountMap.size() > 0) {        
            SIHelper.createSPSharingPartnerRule(SIConstants.ACCOUNT_SHARE,parentAccountMap);
        }
       /* End of ORT defect Fix */
       
        for(Source__c ls:SourceList){
            ls.Account__c=LeadMap.get(ls.Lead__c);
        }
          for(Credit_Validation__c cv:CVList){
            cv.SP_Account__c=LeadMap.get(cv.SP_Lead__c);
          }
          for(Certification__c cf:CFList){
            cf.Who_Passed__c=LeadMap.get(cf.Lead__c);
          }
          for(Related_Documents__c rd:DocList){
            rd.Account__c=LeadMap.get(rd.Lead__c);
          }
          for(Contact ct:ContactList){
            ct.AccountId =LeadMap.get(ct.Lead__c);
            ct.RecordTypeId=recordtype.Id;
            ct.isconverted__c=true;
          }
          for(Contact ct:ContactDeleteList){
            
            ct.SIDeleteContact__c=true;
            ct.Primary_Contact__c=false;
            ct.accountId=null;
          }
          for(Lead leadUpdate:leadNewlist)
             for(Account acct:accountList){
             if(leadUpdate.ConvertedAccountID==acct.ID){
               acct.Description=leadUpdate.Description;
               acct.MRA_Number__c=leadUpdate.MRA_Number__c;
               }
          }
        //updating CV,CF,Doc,LeadSourceList and Contact List
        try{
            update SourceList;
            update CVList;
            update CFList;
            update DocList;
            update ContactList;
            update ContactDeleteList;
            update accountList; 
        }
        catch(Exception Ex)
        {
            ATTException.logException( Ex.getTypeName(), ATTException.constructExceptionMessageString(Ex));
        }
        
    }
/* 
 Name: leadBusinessDevelopmentOwner
 Description: 
 */       
   public void leadBusinessDevelopmentOwner(SObject[] oldObjects,SObject[] updatedObjects)
    {
        try{
        list<Lead> oldLeadList = oldObjects;
        list<Lead> newLeadList = updatedObjects;
        list<QueueSobject> queue = [select QueueId FROM QueueSobject];
        if(!newLeadList.isEmpty() && newLeadList!= null)
        {
            for (Integer i=0; i<newLeadList.size(); i++)
            {
                for(Integer j=0; j<queue.size(); j++)
                {
                    if(newLeadList[i].OwnerId == queue[j].QueueId && newLeadList[i].MRA_Executed_Date__c!=null)
                    {
                        newLeadList[i].addError('Lead Owner must not be a Queue when MRA has been executed');
                    }
                    if(oldLeadList[i].MRA_Executed_Date__c!=newLeadList[i].MRA_Executed_Date__c && newLeadList[i].MRA_Executed_Date__c!=null)
                    {
                            newLeadList[i].Business_Development_Owner__c=newLeadList[i].OwnerID;
                    } 
                    if(newLeadList[i].OwnerId == queue[j].QueueId && newLeadList[i].OwnerId !=oldLeadList[i].OwnerId)
                    {
                        newLeadList[i].addError('Lead Owner must Not be Changed to BID Lead Queue Again');
                    }
                }  
            }
        }
    }
    catch(Exception e){
ATTException.logException( e.getTypeName(), ATTException.constructExceptionMessageString(e));
}
} 
    
    //Lead validation check when lead status is SP Profile Completed
/* 
 Name: Leadwithassociatedcontacts
 Description: 
 */ 
   public void  leadwithassociatedcontacts(Sobject[] updateObjects)
    {
        try{
        List<Lead> leadNewList = updateObjects;
        Map<ID,Boolean> leadprimaryMap= new Map<ID,Boolean>();
        Map<ID,Boolean> leadMainContactMap= new Map<ID,Boolean>();
        Map<ID,Boolean> leadPoratlMap= new Map<ID,Boolean>();
        list<Contact> contactList= new list<Contact>();
        set<Id> leadId=new set<Id>();
        Integer pc,mc,pbc; 
         
        for(Lead lead:leadNewlist)
        {
            if(lead.Status == SIConstants.Lead_Status_SPProfileCompleted)
            {
                leadId.add(lead.id);
            }    
        }
        contactList =[Select Primary_Contact__c,Role__c,Lead__c,Id from Contact where Lead__c IN :leadId ];
        
        for(Lead lead1 : leadNewList)
        {
            pc=0;mc=0;pbc=0;
            for(Contact con : contactList)
            {
                if(lead1.Id == con.lead__c)
                {
                    if(con.Primary_Contact__c==true)
                    {
                        pc++;
                    }
                    if(con.Role__c!=null){
                        if(con.Role__c.contains(SIConstants.Contact_Roll_MainContact)){
                            mc++;
                        }
                    }
                    if(con.Role__c!=null){
                        if(con.Role__c.contains(SIConstants.Contact_Roll_PrimaryBilling))
                        {
                            pbc++;
                        }
                    }
                }
            }
            if(pc>0)
            {
                leadprimaryMap.put(lead1.Id,true);
            }
            if(mc>0)
            {
                leadMainContactMap.put(lead1.Id,true);
            }
            if(pbc>0)
            {
                leadPoratlMap.put(lead1.Id,true);
            }
        }   
        
        for(Lead lead2 : leadNewList)
        {
            if(leadId.contains(lead2.ID) && leadprimaryMap.get(lead2.Id)==null)
            {
                lead2.addError('Lead must contain a Portal Administrator in order to update Lead Status to SP Profile Completed');
            }
            if(leadId.contains(lead2.ID) && leadMainContactMap.get(lead2.Id)==null)
            {
                lead2.addError('Lead must contain a Main Contact in order to update Lead Status to SP Profile Completed');
            }
            if(leadId.contains(lead2.ID) && leadPoratlMap.get(lead2.Id)==null)
            {
                lead2.addError('Lead must contain a Primary Billing Contact in order to update Lead Status to SP Profile Completed');
            }       
       }
  }
  catch(Exception e){
ATTException.logException( e.getTypeName(), ATTException.constructExceptionMessageString(e));
}
} 
       
   /*Copy Lead one Feild to antoher Feild */  
   /* 
 Name: CopyFieldsonLead
 Description: 
 */
   public void copyFieldsonLead (SObject[] updatedObjects)
    {
        try{
        List<Lead> lNewlist = updatedObjects;
       for(Integer i=0;i<LNewlist.size();i++)
       {  

          if(LNewlist[i].Bus_Dev_Comment__c!=null)
              {
               if(LNewlist[i].Additional_information__c!=null){
                LNewlist[i].Additional_information__c = '['+Datetime.now().format()+'-'+ Userinfo.getName() + ']: \n '+ LNewlist[i].Bus_Dev_Comment__c+'\n\n'+LNewlist[i].Additional_information__c;
                }
                else{
                LNewlist[i].Additional_information__c = '['+Datetime.now().format()+'-'+ Userinfo.getName() + ']: \n'+ LNewlist[i].Bus_Dev_Comment__c;
                }
                LNewlist[i].Bus_Dev_Comment__c=null;
                
                if(LNewlist[i].Additional_information__c.Length()>32700){
                
                    LNewlist[i].Additional_information__c =LNewlist[i].Additional_information__c.substring(0,32700);
                
                }
                
                
            }
    
       }
       
   } 
catch(Exception e){
ATTException.logException( e.getTypeName(), ATTException.constructExceptionMessageString(e));
}
}   
  /* 
 Name: leadBillingInformation
 Description: 
 */ 
    public void leadBillingInformation(SObject[] updatedObjects)
    {
        try{
        list<Lead> leadList = updatedObjects;
        
        for(Lead lead : leadList)
        {
            if(lead.Billing_Same_as_Company_Address__c)
            {
                lead.Billing_Address__c=lead.Street;
                lead.Billing_City__c=lead.City;
                lead.Billing_Zip_Code__c=lead.PostalCode;
                lead.Billing_State__c=lead.State;
                lead.Billing_Same_as_Company_Address__c=false;
            }
        }
    }
    catch(Exception e){
ATTException.logException( e.getTypeName(), ATTException.constructExceptionMessageString(e));
}
} 
    
    //Lead Soucre enhancement on "How did you learn about Partner Exchange?" field updation.
 /* 
 Name: leadSourceEnhancements
 Description: 
 */ 
    public void leadSourceEnhancements(SObject[] oldObjects,SObject[] updatedObjects,Boolean isInsert)
    {
        try{
        list<Lead> oldList = oldObjects;        
        list<Lead> updatedList = updatedObjects;
        list<Lead> newList = new List<Lead>();
        list<Source__c> sourcelist = new list<Source__c>();
        ID profileId = userinfo.getProfileId();
        String profileName=[Select Id,Name from Profile where Id=:profileId limit 1].Name;
        Set<Id> leadId = new Set<Id>();
        Map<Id,Boolean> intialSouceCheck = new Map<Id,Boolean>();
        
        for(Lead lead : updatedList)
        {
            leadId.add(lead.Id);
        }
        
        sourcelist = [select Id,Initial_Source__c,Lead__c from Source__c where Lead__c IN :leadId];
        
        for(Source__c source : sourcelist)
        {
            if(source.Initial_Source__c)
            {
                intialSouceCheck.put(source.Lead__c,true);
            }
        }
        
        for(Lead lead : updatedList)
        {
            if(isInsert && lead.How_did_you_learn_about_AT_T_Partner_Exc__c!=null)
            {
                newList.add(lead);              
            }
        }
        
        for(Integer i=0; i<updatedList.size(); i++)
        {
            if(!isInsert && oldList[i].How_did_you_learn_about_AT_T_Partner_Exc__c == Null && updatedList[i].How_did_you_learn_about_AT_T_Partner_Exc__c!=null)
            {
                newList.add(updatedList[i]);
            }
        }
        
        for(Lead lead : newList)
        {
            Source__c source = new Source__c();
            source.Validation_Flag__c=true;
            source.Lead__c=lead.Id;
            source.Source_Type__c=lead.How_did_you_learn_about_AT_T_Partner_Exc__c;
            if(source.Source_Type__c.equals(SIConstants.Source_Type_Other))
            {
                source.If_Other_please_specify__c=lead.Other_Method__c;
            }
            else
            {
                source.Source_Detail__c=lead.Other_Method__c;
            }
            if(profileName!=SIConstants.System_Administrator || profileName!=SIConstants.SI_API_User)
            {
                source.Record_Origin__c=SIConstants.Record_Origin_UserCreated;
                if(intialSouceCheck.get(lead.Id)==true)
                {
                    source.Initial_Source__c=true;
                }
                source.Date_of_Interaction__c=System.today();
            }
            insert source;
        }
    }
    catch(Exception e){
ATTException.logException( e.getTypeName(), ATTException.constructExceptionMessageString(e));
}
} 
}