secondfile/objects/Account.object
<CustomObject>
    <fields>
        <fullName>ASE_ACNA__c</fullName>
        <description>Field  to capture ACNA value associated to ASE Product</description>
        <label>ASE ACNA</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ASE_Ordering_Type__c</fullName>
        <description>ASE Ordering Type Field for ASE Product</description>
        <label>ASE Ordering Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>None</fullName>
                    <default>true</default>
                    <label>None</label>
                </value>
                <value>
                    <fullName>ASR</fullName>
                </value>
                <value>
                    <fullName>WOT</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ASE_Product__c</fullName>
        <defaultValue>false</defaultValue>
        <label>ASE Product</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>No_Of_Active_BAN__c</fullName>
        <description>Roll Up Summary for Active BAN Count</description>
        <label>No. of Active BANs</label>
        <summaryFilterItems>
            <field>ASE_Billing_Account_Number__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </summaryFilterItems>
        <summaryForeignKey>ASE_Billing_Account_Number__c.Account_Name__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>No_Of_Active_CNM__c</fullName>
        <description>Rollup Summary for Active CNM</description>
        <label>No. of Active CNUMs</label>
        <summaryFilterItems>
            <field>ASE_Wholesale_Contract_Number__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </summaryFilterItems>
        <summaryForeignKey>ASE_Wholesale_Contract_Number__c.Account_Name__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
</CustomObject>

secondfile/objects/ASE_Billing_Account_Number__c.object
<CustomObject>
    <fields>
        <fullName>Account_Name__c</fullName>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>ASE Billing Account Number</relationshipLabel>
        <relationshipName>ASE_Billing_Account_Number</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Ban_LATA__c</fullName>
        <formula>Name + TEXT(LATA__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Ban LATA</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LATA__c</fullName>
        <label>LATA</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <controllingField>State__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>320</fullName>
                </value>
                <value>
                    <fullName>322</fullName>
                </value>
                <value>
                    <fullName>324</fullName>
                </value>
                <value>
                    <fullName>325</fullName>
                </value>
                <value>
                    <fullName>326</fullName>
                </value>
                <value>
                    <fullName>328</fullName>
                </value>
                <value>
                    <fullName>330</fullName>
                </value>
                <value>
                    <fullName>332</fullName>
                </value>
                <value>
                    <fullName>334</fullName>
                </value>
                <value>
                    <fullName>336</fullName>
                </value>
                <value>
                    <fullName>338</fullName>
                </value>
                <value>
                    <fullName>340</fullName>
                </value>
                <value>
                    <fullName>342</fullName>
                </value>
                <value>
                    <fullName>344</fullName>
                </value>
                <value>
                    <fullName>346</fullName>
                </value>
                <value>
                    <fullName>348</fullName>
                </value>
                <value>
                    <fullName>350</fullName>
                </value>
                <value>
                    <fullName>352</fullName>
                </value>
                <value>
                    <fullName>354</fullName>
                </value>
                <value>
                    <fullName>356</fullName>
                </value>
                <value>
                    <fullName>358</fullName>
                </value>
                <value>
                    <fullName>360</fullName>
                </value>
                <value>
                    <fullName>362</fullName>
                </value>
                <value>
                    <fullName>364</fullName>
                </value>
                <value>
                    <fullName>366</fullName>
                </value>
                <value>
                    <fullName>368</fullName>
                </value>
                <value>
                    <fullName>370</fullName>
                </value>
                <value>
                    <fullName>374</fullName>
                </value>
                <value>
                    <fullName>376</fullName>
                </value>
                <value>
                    <fullName>420</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>ASE Billing Account Number</label>
    <nameField>
        <label>BAN #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ASE Billing Account Number</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

example/secondfile/classes/ASEBillingAccountNumberTriggerHandler.cls
public with sharing class ASEBillingAccountNumberTriggerHandler extends SITriggerOperations.SITriggerImpl{
    
    public boolean isExecuted;
    public ASEBillingAccountNumberTriggerHandler() 
    {
       isExecuted = true;
       
    }
    
    public override boolean onBeforeInsert(SObject[] newObjects) 
    {
     checkDuplicateName(newObjects, newObjects, true);
     return isExecuted;
    }
       public override boolean onAfterInsert(SObject[] newObjects) 
    {
       List<ASE_Billing_Account_Number__c> newObjList=newObjects;
       // updateASEProductOnAccount(newObjList[0].Account_Name__c);
        return true;
    }
    
    public override boolean onBeforeUpdate(SObject[] oldObjects,SObject[] newObjects,Map<Id,SObject> newObjectsMap )
    {
     checkDuplicateName(oldObjects, newObjects, false);
     return isExecuted;
    }
      public override boolean  onAfterUpdate(SObject[] oldObjects,SObject[] newObjects,Map<Id,SObject> newObjectsMap) 
    {
        List<ASE_Billing_Account_Number__c> newObjList=newObjects;
        updateASEProductOnAccount(newObjList[0].Account_Name__c);
        return true;        
    }
    public void checkDuplicateName(SObject[] oldObjects, SObject[] updatedObjects, boolean isInsert){
        List<ASE_Billing_Account_Number__c> newObjList = updatedObjects;
        List<ASE_Billing_Account_Number__c> oldObjList = oldObjects;
        Map<String,object> ASEMap = new Map<String,object>();
        List<String> nameStr = new List<String>();
        for(integer i=0;i<newObjList.size();i++){
            if(((newObjList[i].name != oldObjList[i].name || newObjList[i].Active__c != oldObjList[i].Active__c || newObjList[i].LATA__c != oldObjList[i].LATA__c) && newObjList[i].Active__c ) || (newObjList[i].Active__c == true && isInsert == true)){
                ASEMap.put(newObjList[i].Ban_LATA__c,newObjList[i]);
            }   
        }
        
        List<ASE_Billing_Account_Number__c> ASEBillingAccNumList = new List<ASE_Billing_Account_Number__c>();
        ASEBillingAccNumList = [Select Name, Account_Name__c, Active__c, LATA__c  from ASE_Billing_Account_Number__c WHERE Ban_LATA__c IN: ASEMap.keySet() AND Active__c =: true];
        
        for(ASE_Billing_Account_Number__c accNum: newObjList){
            if(ASEBillingAccNumList != null && ASEBillingAccNumList.size() > 0){
                accNum.addError('The BAN & LATA entered is already in the system, only unique BAN & LATA combinations are allowed.');     
            } 
        }
    }
      /*
    Added as part of Sprint-29 US780973
    */
    public void updateASEProductOnAccount(String accId)
    {
       
      Account currentAccount=[select No_Of_Active_BAN__c,No_Of_Active_CNM__c,ASE_ACNA__c,ASE_Ordering_Type__c,ASE_Product__c from Account where id=: accId];            

        if(currentAccount.ASE_Product__c  )
        {
        List<ASE_Billing_Account_Number__c> aseBillingAccountList=new List<ASE_Billing_Account_Number__c>();
             aseBillingAccountList= [Select Name, Account_Name__c, Active__c  from ASE_Billing_Account_Number__c WHERE Account_Name__c =: accId AND Active__c =: true];          
              if( aseBillingAccountList.size()== 0){
                currentAccount.ASE_Product__c=False;
                update currentAccount;
                }
        }
        
        
    }
}