secondfile/objects/Circuit_and_VLAN_Details__c.object
<CustomObject>
    <fields>
        <fullName>MACD_Type__c</fullName>
        <description>This is a technical field to capture MACD type for which the record has been created. Not required on page layout.</description>
        <label>MACD Type</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Premise__c</fullName>
        <label>Premise</label>
        <referenceTo>RDS_Premise_Details__c</referenceTo>
        <relationshipName>Circuit_and_VLAN_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>RDS-Circuit and VLAN Details</label>
    <nameField>
        <displayFormat>CV - {000000}</displayFormat>
        <label>RDS-Circuit and VLAN Details Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RDS-Circuit and VLAN Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

secondfile/objects/Deal_Hash__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Master Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>RDS-Deal Hash</relationshipLabel>
        <relationshipName>Deal_Hash</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>RDS_Version__c</fullName>
        <defaultValue>1</defaultValue>
        <label>RDS Version</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>RDS-Deal Hash</label>
    <nameField>
        <displayFormat>DH-{00000}</displayFormat>
        <label>Deal Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RDS-Deal Hash</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

example/secondfile/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Is_MD5_Call_Required__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is MD5 Call Required</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MACD_Type__c</fullName>
        <label>MACD Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>A</fullName>
                </value>
                <value>
                    <fullName>C</fullName>
                </value>
                <value>
                    <fullName>D</fullName>
                </value>
                <value>
                    <fullName>M</fullName>
                </value>
                <value>
                    <fullName>N</fullName>
                </value>
                <value>
                    <fullName>R</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>RDS_Deal_Hash__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>RDS-Deal Hash</label>
        <referenceTo>Deal_Hash__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>RelatedOpportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RDS_Version__c</fullName>
        <defaultValue>1</defaultValue>
        <label>RDS Version</label>
        <precision>15</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

secondfile/objects/RDS_Access_Circuit_ID__c.object
<CustomObject>
    <description>Premise Details-Premise Data-Circuit and VLAN Details-Access Circuit ID</description>
    <fields>
        <fullName>Circuit_and_VLAN_Details__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Premise Details-Premise Data-Circuit and VLAN Details-Access Circuit ID</description>
        <label>Circuit and VLAN Details</label>
        <referenceTo>Circuit_and_VLAN_Details__c</referenceTo>
        <relationshipName>Circuit_and_VLAN_Details</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MACD_Type__c</fullName>
        <description>This is a technical field to indicate that record has been created due to MACD Disconnect. Not required on page layout.</description>
        <label>MACD Type</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <label>RDS-Access Circuit ID</label>
    <nameField>
        <displayFormat>AC -{0000000}</displayFormat>
        <label>Access Circuit ID Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RDS-Access Circuit ID</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

secondfile/objects/RDS_History_Tracking__c.object
<CustomObject>
    <fields>
        <fullName>DealHash__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>For holding Deal Hash has ID</description>
        <label>Deal Hash</label>
        <referenceTo>Deal_Hash__c</referenceTo>
        <relationshipName>RDSHistoryTracking</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Encrypted_Password__c</fullName>
        <description>Encrypted Password</description>
        <label>Encrypted Password</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MACD_Type__c</fullName>
        <description>This is a technical field to indicate that record has been created due to MACD Disconnect. Not required on page layout.</description>
        <label>MACD Type</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity_Name__c</fullName>
        <label>Opportunity Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>RDSHistoryTracking</relationshipLabel>
        <relationshipName>RDSHistoryTracking</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PremiseDetails__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>RDS-Premise Details</label>
        <referenceTo>RDS_Premise_Details__c</referenceTo>
        <relationshipLabel>RDSHistoryTracking</relationshipLabel>
        <relationshipName>RDSHistoryTracking</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RDSCircuitVLANDetails__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>RDS-Circuit and VLAN Details</label>
        <referenceTo>Circuit_and_VLAN_Details__c</referenceTo>
        <relationshipLabel>RDSHistoryTracking</relationshipLabel>
        <relationshipName>RDSHistoryTracking</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RDSModifiedDateTime__c</fullName>
        <description>For Tracking the RDS Modified Date/Time</description>
        <label>RDS Modified Date/Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Routing_Protocal__c</fullName>
        <description>For Capturing Routing Protocal</description>
        <label>Routing Protocol</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>V4Family__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>RDS-V4 Family Data</label>
        <referenceTo>RDS_V4_Family_Data__c</referenceTo>
        <relationshipLabel>RDSHistoryTracking</relationshipLabel>
        <relationshipName>RDSHistoryTracking</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>RDS-History Tracking</label>
    <nameField>
        <displayFormat>RHT-{00000000}</displayFormat>
        <label>RDS  History Tracking Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RDSHistoryTracking</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

secondfile/objects/RDS_Premise_Details__c.object
<CustomObject>
    <fields>
        <fullName>DealHash__c</fullName>
        <description>For Relating Premise with Parent Deal Hash Record</description>
        <label>Deal Hash</label>
        <referenceTo>Deal_Hash__c</referenceTo>
        <relationshipLabel>RDS-Premise Details</relationshipLabel>
        <relationshipName>Premise</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>MACD_Type__c</fullName>
        <label>MACD Type</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RDS_Version__c</fullName>
        <defaultValue>1</defaultValue>
        <label>RDS Version</label>
        <precision>15</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>RDS-Premise Details</label>
    <nameField>
        <displayFormat>P - {000000}</displayFormat>
        <label>Premise Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RDS-Premise Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

example/secondfile/objects/RDS_V4_Family_Data__c.object
<CustomObject>
    <description>Premise Details-Premise Data-Circuit and VLAN Details-VLAN Information-V4 Family Data</description>
    <fields>
        <fullName>Deal_Hash_ID__c</fullName>
        <formula>IF(RDS_VLAN_Information_V4__c !=&apos;&apos;,RDS_VLAN_Information_V4__r.Circuit_and_VLAN_Details__r.Premise__r.DealHash__r.Id, RDS_Circuit_and_VLAN_Details_V4__r.Premise__r.DealHash__r.Id)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Deal Hash ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Encrypted_Password__c</fullName>
        <description>Premise Details- Premise Data-circuit and VLAN Information-VLAN Information-V4 Family Data-MD 5- Encrypted Password</description>
        <label>Encrypted Password</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Is_MD5_Call_Required__c</fullName>
        <formula>IF(AND(Routing_Protocol__c=&apos;BGP4&apos;,Encrypted_Password__c!=null), true, false)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Is MD5 Call Required</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MACD_Type__c</fullName>
        <description>This is a technical field to indicate that record has been created due to MACD Disconnect. Not required on page layout.</description>
        <label>MACD Type</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity_Name__c</fullName>
        <description>To be tacked on report</description>
        <label>Opportunity Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RDS_Circuit_and_VLAN_Details_V4__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Direct Link to Parent RDS-Circuit and VLAN Details record</description>
        <label>RDS-Circuit and VLAN Details</label>
        <referenceTo>Circuit_and_VLAN_Details__c</referenceTo>
        <relationshipLabel>RDS-V4 Family Data</relationshipLabel>
        <relationshipName>RDS_V4_Family_Data</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RDS_VLAN_Information_V4__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Premise Details-Premise Data-Circuit And VLAN Details-VLAN Information-V4 Family Data-VLAN Information V4</description>
        <label>RDS-VLAN Information V4</label>
        <referenceTo>VLAN_Information__c</referenceTo>
        <relationshipLabel>RDS-V4 Family Data</relationshipLabel>
        <relationshipName>RDS_V4_Family_Data</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Routing_Protocol__c</fullName>
        <description>Premise Details- Premise Data-circuit and VLAN Information-VLAN Information-V4 Family Data-Routing Protocol</description>
        <label>Routing Protocol</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Selected_Opportunity_On_RDS__c</fullName>
        <formula>IF( RDS_VLAN_Information_V4__c !=&apos;&apos; ,  RDS_VLAN_Information_V4__r.Circuit_and_VLAN_Details__r.Premise__r.DealHash__r.Selected_Opportunity__c ,  RDS_Circuit_and_VLAN_Details_V4__r.Premise__r.DealHash__r.Selected_Opportunity__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Selected Opportunity On RDS</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Version_From_Premise__c</fullName>
        <formula>IF(RDS_VLAN_Information_V4__c !=&apos;&apos;,RDS_VLAN_Information_V4__r.Circuit_and_VLAN_Details__r.Premise__r.RDS_Version__c, RDS_Circuit_and_VLAN_Details_V4__r.Premise__r.RDS_Version__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Version From Premise</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>RDS-V4 Family Data</label>
    <nameField>
        <displayFormat>FDV4-{0000}</displayFormat>
        <label>RDS-V4 Family Data Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RDS-V4 Family Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

example/secondfile/objects/VLAN_Information__c.object
<CustomObject>
    <description>Premise Details-Premise Data-Circuit and VLAN Details-VLAN Information</description>
    <fields>
        <fullName>Circuit_and_VLAN_Details__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Premise Details-Premise Data-Circuit and VLAN Details-VLAN Information</description>
        <label>Circuit and VLAN Details</label>
        <referenceTo>Circuit_and_VLAN_Details__c</referenceTo>
        <relationshipName>VLAN_Information</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MACD_Type__c</fullName>
        <description>This is a technical field to indicate that record has been created due to MACD Disconnect. Not required on page layout.</description>
        <label>MACD Type</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <label>RDS-VLAN Information</label>
    <nameField>
        <displayFormat>VLAN - {0000000}</displayFormat>
        <label>VLAN Information  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RDS-VLAN Information</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

example/secondfile/classes/API_RDS_V4FamilyDataTriggerHandler.cls
/*
     Component Name :API_RDS_V4FamilyDataTriggerHandler
     Requirement/User Story Number : US238470 
     Requirement Description:Insert History Tracking Record on V4 Record insert
     Component Author:Accenture IDC
     Created Date:5th May 2014 
     Version:1.0
     Version 1.1: updated the logic around inserting record in history table matching the routing protocol and Encrypted password.
     Last Modified By: Accenture IDC
    */ 
public with sharing class API_RDS_V4FamilyDataTriggerHandler extends SITriggerOperations.SITriggerImpl{
      
      public boolean isExecuted ;
      List<RDS_V4_Family_Data__c> listofv4= new List<RDS_V4_Family_Data__c>();

    //Default cons
/* 
 Name: API_RDS_V4FamilyDataTriggerHandler
 Description: 
 */ 
    public API_RDS_V4FamilyDataTriggerHandler() {
        isExecuted = true; 
    }
    
/* 
 Name: onAfterUpdate
 Description: 
 */ 
    public override boolean onAfterUpdate(SObject[] oldObjects, SObject[] updatedObjects, Map<Id, SObject>  newObjectsMap )  {
        try {
            rdsTriggerHistory(updatedObjects,false,true);
            
            checkMd5RequiredCheckboxOnOppty(updatedObjects);            
        
        } catch(Exception excep) {
            excep.getMessage();
            isExecuted = false;
            throw excep;
            ATTException.logException( excep.getTypeName(), ATTException.constructExceptionMessageString(excep));
        }
        return isExecuted;
    }
    
/* 
 Name: onAfterInsert
 Description: 
 */ 
     public override boolean onAfterInsert(SObject[] updatedObjects)  {
        try {
            
            rdsTriggerHistory(updatedObjects,true,false);
            
            checkMd5RequiredCheckboxOnOppty(updatedObjects);                        
        } catch(Exception excep) {
             excep.getMessage();
            isExecuted = false;
            throw excep;
            ATTException.logException( excep.getTypeName(), ATTException.constructExceptionMessageString(excep));
        }
        return isExecuted;
    }
     /*
      *Name :rdsTriggerHistory
      * */ 
     public void rdsTriggerHistory(SObject[] updatedObjects,Boolean isInsert, Boolean isUpdate)
     {
      try{   
        listofv4 = updatedObjects;
        Set<Id> rdsIdsetVLAN = New Set<Id>();
        Set<Id> rdsIdsetCVLAN = New Set<Id>();
        List<RDS_History_Tracking__c> rdsHistoryTrackingList = New List<RDS_History_Tracking__c>();
        List<Messaging.SingleEmailMessage> listOfMails = new List<Messaging.SingleEmailMessage>();
        List<RDS_History_Tracking__c> rdsexistingHistoryRecordList=New List<RDS_History_Tracking__c>();
        String opptyName;
        String reportURL;
        String sfdcBaseURL = URL.getSalesforceBaseUrl().toExternalForm();
        
        if(isInsert || isUpdate)
        {
            for (RDS_V4_Family_Data__c v4familyRecord: listofv4  ){
                if(v4familyRecord.Routing_Protocol__c!=SIConstants.ROUTINGPROTOCOL && v4familyRecord.Encrypted_Password__c!=null && v4familyRecord.RDS_VLAN_Information_V4__c!=null){
                    rdsIdsetVLAN.add(v4familyRecord.Id);
                }
                if(v4familyRecord.Routing_Protocol__c!=SIConstants.ROUTINGPROTOCOL && v4familyRecord.Encrypted_Password__c!=null && v4familyRecord.RDS_Circuit_and_VLAN_Details_V4__c!=null){
                    rdsIdsetCVLAN.add(v4familyRecord.Id);
                }
            }
            if(!rdsIdsetVLAN.isEmpty() && rdsIdsetVLAN.size()>0){
                List<RDS_V4_Family_Data__c> v4familyRecordList=[Select Id,RDS_V4_Family_Data__c.RDS_VLAN_Information_V4__r.Circuit_and_VLAN_Details__r.Premise__r.DealHash__r.Opportunity__r.Owner.Email,RDS_V4_Family_Data__c.RDS_VLAN_Information_V4__r.Circuit_and_VLAN_Details__r.Premise__r.ID,RDS_VLAN_Information_V4__r.Id,RDS_V4_Family_Data__c.RDS_VLAN_Information_V4__r.Circuit_and_VLAN_Details__r.Premise__r.DealHash__r.Opportunity__r.Name ,RDS_V4_Family_Data__c.RDS_VLAN_Information_V4__r.Circuit_and_VLAN_Details__r.ID,RDS_VLAN_Information_V4__r.Circuit_and_VLAN_Details__r.Premise__r.DealHash__r.Id,Routing_Protocol__c,Encrypted_Password__c from RDS_V4_Family_Data__c where Id IN:rdsIdsetVLAN];
                if(v4familyRecordList.size()>0){
                    for(RDS_V4_Family_Data__c v4famRecord:v4familyRecordList){                        
                        List<String> sendTo= new List<String>();
                        sendTo.add(v4famRecord.RDS_VLAN_Information_V4__r.Circuit_and_VLAN_Details__r.Premise__r.DealHash__r.Opportunity__r.Owner.Email);
                        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
                        mail.setToAddresses(sendTo);
                        opptyName=v4famRecord.RDS_VLAN_Information_V4__r.Circuit_and_VLAN_Details__r.Premise__r.DealHash__r.Opportunity__r.Name;
                        reportURL=sfdcBaseURL+'/'+Label.RDS_History_Tracking_Report_ID+'?pv1='+opptyName;
                        mail.setSubject('RDS - Information correction needed');
                        mail.setHtmlBody('<table><tr><td>Dear EBM,</td></tr><br/><tr><td>Please see attached report and make necessary corrections to RDS.  RDS review will not be completed without this information.</td></tr><br/><br/><tr><td>Click Here to view the Report</td></tr><tr><td>'+reportURL+'</td></tr><br/><tr><td>Best regards,</td></tr><br/><tr><td>SFDC Admin</td></tr></table>'); 
                        listOfMails.add(mail);
                        RDS_History_Tracking__c rdshistory= New  RDS_History_Tracking__c();
                        rdshistory.DealHash__c=v4famRecord.RDS_VLAN_Information_V4__r.Circuit_and_VLAN_Details__r.Premise__r.DealHash__r.Id;
                        rdshistory.V4Family__c=v4famRecord.Id;
                        rdshistory.RDSCircuitVLANDetails__c =v4famRecord.RDS_VLAN_Information_V4__r.Circuit_and_VLAN_Details__r.ID;
                        rdshistory.PremiseDetails__c=v4famRecord.RDS_VLAN_Information_V4__r.Circuit_and_VLAN_Details__r.Premise__r.Id;
                        rdshistory.Routing_Protocal__c=v4famRecord.Routing_Protocol__c;
                        rdshistory.Opportunity_Name__c=v4famRecord.RDS_VLAN_Information_V4__r.Circuit_and_VLAN_Details__r.Premise__r.DealHash__r.Opportunity__r.Name;
                        rdshistory.RDSModifiedDateTime__c= DateTime.Now();
                        rdshistory.Encrypted_Password__c =v4famRecord.Encrypted_Password__c;                        
                        
                        rdsHistoryTrackingList.add(rdshistory);
                    }  
                }           
                rdsexistingHistoryRecordList=[Select ID from RDS_History_Tracking__c where V4Family__c=:rdsIdsetVLAN];           
            }
            
            else if(!rdsIdsetCVLAN.isEmpty() && rdsIdsetCVLAN.size()>0){
                List<RDS_V4_Family_Data__c> v4familyRecordList=[Select Id,RDS_V4_Family_Data__c.RDS_Circuit_and_VLAN_Details_V4__r.Premise__r.DealHash__r.Opportunity__r.Owner.Email,RDS_V4_Family_Data__c.RDS_Circuit_and_VLAN_Details_V4__r.Premise__r.ID,RDS_Circuit_and_VLAN_Details_V4__r.Id,RDS_V4_Family_Data__c.RDS_Circuit_and_VLAN_Details_V4__r.Premise__r.DealHash__r.Opportunity__r.Name ,RDS_Circuit_and_VLAN_Details_V4__r.Premise__r.DealHash__r.Id,Routing_Protocol__c,Encrypted_Password__c from RDS_V4_Family_Data__c where Id IN:rdsIdsetCVLAN];
                if(v4familyRecordList.size()>0){
                    for(RDS_V4_Family_Data__c v4famRecord:v4familyRecordList){
                    
                        List<String> sendTo= new List<String>();
                        sendTo.add(v4famRecord.RDS_Circuit_and_VLAN_Details_V4__r.Premise__r.DealHash__r.Opportunity__r.Owner.Email);
                        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
                        mail.setToAddresses(sendTo);
                        opptyName=v4famRecord.RDS_Circuit_and_VLAN_Details_V4__r.Premise__r.DealHash__r.Opportunity__r.Name;
                        reportURL=sfdcBaseURL+'/'+Label.RDS_History_Tracking_Report_ID+'?pv1='+opptyName;
                        mail.setSubject('RDS - Information correction needed');
                        mail.setHtmlBody('<table><tr><td>Dear EBM,</td></tr><br/><tr><td>Please see attached report and make necessary corrections to RDS.  RDS review will not be completed without this information.</td></tr><br/><br/><tr><td>Click Here to view the Report</td></tr><tr><td>'+reportURL+'</td></tr><br/><tr><td>Best regards,</td></tr><br/><tr><td>SFDC Admin</td></tr></table>'); 
                        listOfMails.add(mail);
                        RDS_History_Tracking__c rdshistory= New  RDS_History_Tracking__c();
                        rdshistory.DealHash__c=v4famRecord.RDS_Circuit_and_VLAN_Details_V4__r.Premise__r.DealHash__r.Id;
                        rdshistory.V4Family__c=v4famRecord.Id;
                        rdshistory.RDSCircuitVLANDetails__c =v4famRecord.RDS_Circuit_and_VLAN_Details_V4__r.ID;
                        rdshistory.PremiseDetails__c=v4famRecord.RDS_Circuit_and_VLAN_Details_V4__r.Premise__r.Id;
                        rdshistory.Routing_Protocal__c=v4famRecord.Routing_Protocol__c;
                        rdshistory.Opportunity_Name__c=v4famRecord.RDS_Circuit_and_VLAN_Details_V4__r.Premise__r.DealHash__r.Opportunity__r.Name;
                        rdshistory.RDSModifiedDateTime__c= DateTime.Now();
                        rdshistory.Encrypted_Password__c =v4famRecord.Encrypted_Password__c;                        
                        
                        rdsHistoryTrackingList.add(rdshistory);
                    } 
                }
                rdsexistingHistoryRecordList=[Select ID from RDS_History_Tracking__c where V4Family__c=:rdsIdsetCVLAN];       
            }
            
            if (rdsexistingHistoryRecordList.size()>0){
                try{
                    Database.Delete(rdsexistingHistoryRecordList);
                }catch(Exception exe){
                    exe.getMessage();
                    ATTException.logException( exe.getTypeName(), ATTException.constructExceptionMessageString(exe));
                }
            }
            if(rdsHistoryTrackingList.size()>0){ 
                try{
                    Database.Insert(rdsHistoryTrackingList);
                }catch(Exception exe){
                    exe.getMessage();
                ATTException.logException( exe.getTypeName(), ATTException.constructExceptionMessageString(exe));   
                }
            }
        
        }
        if(isInsert && listOfMails != null && listOfMails.size() > 0){
            Messaging.sendEmail(listOfMails);
        }
      }catch(Exception ex){
            ATTException.logException( ex.getTypeName(), ATTException.constructExceptionMessageString(ex));
        }
    
    } 
    /*
    The method is to set the isMD5 required checkbox on oppty, based on which MD5 call goes out. 
    This is to restrict MD5 call is only sent whenever required and not always i.e. whenever v4 family data comes with routing protocol = BGP4 and encrypted passwoed!=null 
    */   
    /*public void checkMd5RequiredCheckboxOnOppty(SObject[] updatedObjects){
        List<RDS_V4_Family_Data__c> listofv4 =updatedObjects;
        Map<Id,Opportunity> opptyMap= New Map<Id,Opportunity>();
        Set<Id> opptyIdSet = new Set<Id>();
        Set<Id> opptyIdSet1 = new Set<Id>();
        Boolean v4MD5Checktrue=false;
        Boolean v4MD5CheckFalse=false;
        Boolean fieldUpdated = false;           
        
        for(RDS_V4_Family_Data__c v4:listofv4){   
            if(v4.Is_MD5_Call_Required__c == true){ 
                    v4MD5Checktrue=true;                
            }else{                 
                    v4MD5CheckFalse=true;
            }      
            opptyIdSet.add(v4.Selected_Opportunity_On_RDS__c);            
        }
        if(opptyIdSet.size()>0){
            for(Opportunity oppty: [Select id,Is_MD5_Call_Required__c from Opportunity where ID IN:opptyIdSet]){
                opptyMap.put(oppty.Id,oppty);
            }
        }
        
        if(!opptyMap.isEmpty() && opptyMap.size()>0){
            for(Opportunity opp:opptyMap.Values()){
                if(opp.Is_MD5_Call_Required__c == false && v4MD5Checktrue){
                    opp.Is_MD5_Call_Required__c = true;  
                    fieldUpdated = true;
                } /*else if(opp.Is_MD5_Call_Required__c == true && v4MD5CheckFalse){
                    opp.Is_MD5_Call_Required__c = false;  
                    fieldUpdated = true;
                }
            }
        }*/
        /*if(opptyMap.size()>0 && !opptyMap.isEmpty() && fieldUpdated){
            try{
                update opptyMap.Values();
            }
            Catch(Exception e){
                e.getMessage();
            }
        }
    
    }*/
/* 
 Name: checkMd5RequiredCheckboxOnOppty
 Description: 
 */ 
    public void checkMd5RequiredCheckboxOnOppty(SObject[] updatedObjects){
    try{    
        List<RDS_V4_Family_Data__c> listofv4 =updatedObjects;
        Map<Id,Opportunity> opptyMap= New Map<Id,Opportunity>();
        Set<Id> opptyIdSet = new Set<Id>();
        Set<Id> opptyIdSet1 = new Set<Id>();
        Boolean v4MD5Checktrue=false;
        Boolean v4MD5CheckFalse=false;
        Boolean fieldUpdated = false;
        List<Opportunity>opptyList =  new List<Opportunity>();
        List<Opportunity>updatedOpptyList =  new List<Opportunity>();
        Set<ID> v4Set1= new Set<ID>();
        Set<Decimal> v4Set2= new Set<Decimal>();  

    for(RDS_V4_Family_Data__c v4:listofv4){ 
        if(v4.Is_MD5_Call_Required__c == true){
            V4Set1.add(v4.Deal_Hash_ID__c);
            v4Set2.add(v4.Version_From_Premise__c);
        }       
        }
    
    
     OpptyList = [Select id,RDS_Version__c,RDS_Deal_Hash__c,MACD_Type__c From Opportunity where RDS_Version__c IN: v4Set2 AND RDS_Deal_Hash__c IN: v4Set1 AND MACD_Type__c !=: UtilityConstant.C AND MACD_Type__c !=: UtilityConstant.D];
        if(OpptyList.size()>0){
            for(Opportunity Opp:OpptyList){
                for(RDS_V4_Family_Data__c v4:listofv4)
                    if(opp.RDS_Version__c== v4.Version_From_Premise__c && opp.RDS_Deal_Hash__c==v4.Deal_Hash_ID__c && v4.Is_MD5_Call_Required__c == true && opp.MACD_Type__c != UtilityConstant.C && opp.MACD_Type__c != UtilityConstant.D)
                    {
                        opp.Is_MD5_Call_Required__c = true; 
                        UpdatedOpptyList.add(opp);
                    }
                }
        }
     if(UpdatedOpptyList.size()>0){
            try{
                update UpdatedOpptyList;
            }
            Catch(Exception e){
                e.getMessage();
                ATTException.logException( e.getTypeName(), ATTException.constructExceptionMessageString(e));
            }
        }
    
     }catch(Exception ex){
            ATTException.logException( ex.getTypeName(), ATTException.constructExceptionMessageString(ex));
        }
  }
 
}