secondfile/objects/CustomerSite__c.object
<CustomObject>
    <description>Custom object to store customer site information</description>
    <fields>
        <fullName>ASE_ITPA_Response_Status__c</fullName>
        <label>ASE ITPA Response Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Address_Line__c</fullName>
        <label>Street</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IsSoftRemove__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsSoftRemove</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <label>Location</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Room</fullName>
                </value>
                <value>
                    <fullName>Suite</fullName>
                </value>
                <value>
                    <fullName>Floor</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <label>Phone #</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Site_Name__c</fullName>
        <label>Site Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AL</fullName>
                </value>
                <value>
                    <fullName>AK</fullName>
                </value>
                <value>
                    <fullName>AZ</fullName>
                </value>
                <value>
                    <fullName>AR</fullName>
                </value>
                <value>
                    <fullName>CA</fullName>
                </value>
                <value>
                    <fullName>CO</fullName>
                </value>
                <value>
                    <fullName>CT</fullName>
                </value>
                <value>
                    <fullName>DE</fullName>
                </value>
                <value>
                    <fullName>FL</fullName>
                </value>
                <value>
                    <fullName>GA</fullName>
                </value>
                <value>
                    <fullName>HI</fullName>
                </value>
                <value>
                    <fullName>ID</fullName>
                </value>
                <value>
                    <fullName>IL</fullName>
                </value>
                <value>
                    <fullName>IN</fullName>
                </value>
                <value>
                    <fullName>IA</fullName>
                </value>
                <value>
                    <fullName>KS</fullName>
                </value>
                <value>
                    <fullName>KY</fullName>
                </value>
                <value>
                    <fullName>LA</fullName>
                </value>
                <value>
                    <fullName>ME</fullName>
                </value>
                <value>
                    <fullName>MD</fullName>
                </value>
                <value>
                    <fullName>MA</fullName>
                </value>
                <value>
                    <fullName>MI</fullName>
                </value>
                <value>
                    <fullName>MN</fullName>
                </value>
                <value>
                    <fullName>MS</fullName>
                </value>
                <value>
                    <fullName>MO</fullName>
                </value>
                <value>
                    <fullName>MT</fullName>
                </value>
                <value>
                    <fullName>NE</fullName>
                </value>
                <value>
                    <fullName>NV</fullName>
                </value>
                <value>
                    <fullName>NH</fullName>
                </value>
                <value>
                    <fullName>NJ</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>VASA_Response_Status__c</fullName>
        <label>Service Availability Response Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>ADDRESS RECORD CREATED</fullName>
                    <default>true</default>
                    <label>ADDRESS RECORD CREATED</label>
                </value>
                <value>
                    <fullName>ADDRESS EXACT MATCH</fullName>
                </value>
                <value>
                    <fullName>ADDRESS NO MATCH</fullName>
                </value>
                <value>
                    <fullName>POSSIBLE MATCHES</fullName>
                </value>
                <value>
                    <fullName>SERVICE AVAILABILITY CHECKED</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Zip_Code__c</fullName>
        <label>Zip Code</label>
        <length>5</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>AT&amp;T Customer Site</label>
    <nameField>
        <displayFormat>ADD-{000000}</displayFormat>
        <label>Site #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AT&amp;T Customer Sites</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

example/secondfile/classes/PopulateSiteAddReviewDataBuilder.cls
public class PopulateSiteAddReviewDataBuilder {
    public string actionType{get;set;}
    public Map<String,String> currDataMap {get;set;}
    public Map<String,String> propdDataMap {get;set;}
    public List<CustomerSite__c> currDataList {get;set;}
    public List<String> propdDataList {get;set;}
    public WrapperUIRenderComponentBuilder wrcb;
    
    public PopulateSiteAddReviewDataBuilder(String action){
        actionType = action;
    }
     public void executePostBuildPrep(WrapperUIRenderComponent wrc){
      wrcb.executePostBuildPrep(wrc);
       }
 

    public WrapperUIRenderComponent populateRevReqData(List<CustomerSite__c> customerSite,Map<String,boolean> junctionMap,String prod){
        
        system.debug('--action in pop builder---'+actionType);
        String actionType='Review';
        WrapperUIRenderComponent wrc= new WrapperUIRenderComponent('SiteAddressInfoTable'+actionType);
       
        wrcb= new WrapperUIRenderComponentBuilder (wrc,'ViewTable','BuyFlow','Flow',actionType);
          populateCurrentDataList(customerSite,junctionMap,prod);
      system.debug('---wrc at end of populateRevReqData---'+wrc);
        return wrc;                   
    }
    
    public void populateCurrentDataList(List<CustomerSite__c> customerSite,Map<String,boolean> junctionMap,String prod){

          integer i=1,j=1;   
       
        wrcb.loadSectionElement('Site Id','Site Id','Site Id'+i+'_'+j,'DataTableHeader',i,j) ;
        wrcb.loadSectionElement('IsSoftRemove','IsSoftRemove','IsSoftRemove'+i+'_'+j,'DataTableHeader',i,j+1) ;
        wrcb.loadSectionElement('Site Name','Site Name','Site Name'+i+'_'+j,'DataTableHeader',i,j+2) ;
        wrcb.loadSectionElement('Site Address','Site Address','Site Address'+i+'_'+j,'DataTableHeader',i,j+3) ;
        wrcb.loadSectionElement('Phone','Phone','Phone'+i+'_'+j,'DataTableHeader',i,j+4) ;
        wrcb.loadSectionElement('Site Status','Site Status','Site Status'+i+'_'+j,'DataTableHeader',i,j+5) ;
        wrcb.loadSectionElement('Action','Action','Action'+i+'_'+j,'DataTableHeader',i,j+6) ;
       
        String address='';
        String action='';
        i=2;j=1;
        system.debug('customerSite size in builder='+customerSite.size());
        for(CustomerSite__c custSite : customerSite){
      
        system.debug('value of I='+i+' and CustomerSite__c is'+custSite );
            address='';
            action='';

            wrcb.loadSectionElement( 'Site id',custSite.Id,'Site Id'+i+'_'+j,custSite.Id,i,j) ;
            //wrcb.loadSectionElement( 'IsSoftRemove',custSite.IsSoftRemove__c+'','IsSoftRemove'+i+'_'+j,custSite.Id,i,j+1) ;
            
            wrcb.loadSectionElement( 'IsSoftRemove',junctionMap.get(custSite.Id)+'','IsSoftRemove'+i+'_'+j,custSite.Id,i,j+1) ;
            wrcb.loadSectionElement( 'Site Name',custSite.Site_Name__c,'Site Name'+i+'_'+j,custSite.Id,i,j+2) ;
            wrcb.loadSectionElement( 'Site Address',custSite.Address_Line__c,'Site Address'+i+'_'+j,custSite.Id,i,j+3) ;
            wrcb.loadSectionElement( 'Site Location',custSite.Location__c,'Site Location'+i+'_'+j,custSite.Id,i,j+3) ;
            wrcb.loadSectionElement( 'Site City',custSite.City__c,'Site City'+i+'_'+j,custSite.Id,i,j+3) ;
            wrcb.loadSectionElement( 'Site State',custSite.State__c,'Site State'+i+'_'+j,custSite.Id,i,j+3) ;
            wrcb.loadSectionElement( 'Site Zip',custSite.Zip_Code__c,'Site Zip'+i+'_'+j,custSite.Id,i,j+3) ; 
          
            wrcb.loadSectionElement( 'Phone',custSite.Phone__c,'Phone'+i+'_'+j,custSite.Id,i,j+4) ;
             
            if(prod.equalsIgnoreCase(BuyflowConstant.ASE)){
                wrcb.loadSectionElement( 'SiteStatus',custSite.ASE_ITPA_Response_Status__c,'Site Status'+i+'_'+j,custSite.Id,i,j+5) ;
                //Code for action mapping
                if(custSite.ASE_ITPA_Response_Status__c  !='' && custSite.ASE_ITPA_Response_Status__c  !=null)
                {
                  if(custSite.ASE_ITPA_Response_Status__c.contains('ADDRESS NO MATCH') || custSite.ASE_ITPA_Response_Status__c.contains('ADDRESS RECORD CREATED') || custSite.ASE_ITPA_Response_Status__c.contains('POSSIBLE MATCHES') || custSite.ASE_ITPA_Response_Status__c.contains('SERVICE UNAVAILABLE'))
                 {
                  
                     wrcb.loadSectionElement( 'Edit','Edit','Edit'+i+'_'+j,custSite.Id,i,j+6) ;
                     wrcb.loadSectionElement( 'Pipe','|','Pipe'+i+'_'+j,custSite.Id,i,j+6) ;
                     wrcb.loadSectionElement( 'Remove','Remove','Remove'+i+'_'+j,custSite.Id,i,j+6) ;
                 
                 }
                else if(custSite.ASE_ITPA_Response_Status__c.contains('ADDRESS EXACT MATCH'))
                 {
                        wrcb.loadSectionElement( 'Remove','Remove','Remove'+i+'_'+j,custSite.Id,i,j+6) ;
                 }
                 
               }

            }
            else{ 
                wrcb.loadSectionElement( 'SiteStatus',custSite.VASA_Response_Status__c,'Site Status'+i+'_'+j,custSite.Id,i,j+5) ;
                //Code for action mapping
                if(custSite.VASA_Response_Status__c!='' && custSite.VASA_Response_Status__c!=null)
                {
                  if(custSite.VASA_Response_Status__c.contains('ADDRESS NO MATCH') || custSite.VASA_Response_Status__c.contains('ADDRESS RECORD CREATED') || custSite.VASA_Response_Status__c.contains('POSSIBLE MATCHES') || custSite.VASA_Response_Status__c.contains('SERVICE UNAVAILABLE'))
                 {
                  
                     wrcb.loadSectionElement( 'Edit','Edit','Edit'+i+'_'+j,custSite.Id,i,j+6) ;
                     wrcb.loadSectionElement( 'Pipe','|','Pipe'+i+'_'+j,custSite.Id,i,j+6) ;
                     wrcb.loadSectionElement( 'Remove','Remove','Remove'+i+'_'+j,custSite.Id,i,j+6) ;
                 
                 }
                else if(custSite.VASA_Response_Status__c.contains('ADDRESS EXACT MATCH'))
                 {
                        wrcb.loadSectionElement( 'Remove','Remove','Remove'+i+'_'+j,custSite.Id,i,j+6) ;
                 }
                 
               }
            }

             i++;
            
       }
           system.debug('value of i at the end='+i) ;
    }
     
    
    
}