secondfile/objects/CustomerSite__c.object
<CustomObject>
    <description>Custom object to store customer site information</description>
    <fields>
        <fullName>Address_Line__c</fullName>
        <label>Street</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BRASS_Response_Status__c</fullName>
        <label>BRASS Response Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>ALTERED ADDRESS</fullName>
                </value>
                <value>
                    <fullName>ALTERNATE ADDRESS</fullName>
                </value>
                <value>
                    <fullName>NO MATCH</fullName>
                </value>
                <value>
                    <fullName>VALID</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <label>Location</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Room</fullName>
                </value>
                <value>
                    <fullName>Suite</fullName>
                </value>
                <value>
                    <fullName>Floor</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <label>Phone #</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RoomBuildingFloorInput__c</fullName>
        <label>RoomBuildingFloorInput</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Site_Description__c</fullName>
        <label>Site Description</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Site_Name__c</fullName>
        <label>Site Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AL</fullName>
                </value>
                <value>
                    <fullName>AK</fullName>
                </value>
                <value>
                    <fullName>AZ</fullName>
                </value>
                <value>
                    <fullName>AR</fullName>
                </value>
                <value>
                    <fullName>CA</fullName>
                </value>
                <value>
                    <fullName>CO</fullName>
                </value>
                <value>
                    <fullName>CT</fullName>
                </value>
                <value>
                    <fullName>DE</fullName>
                </value>
                <value>
                    <fullName>FL</fullName>
                </value>
                <value>
                    <fullName>GA</fullName>
                </value>
                <value>
                    <fullName>HI</fullName>
                </value>
                <value>
                    <fullName>ID</fullName>
                </value>
                <value>
                    <fullName>IL</fullName>
                </value>
                <value>
                    <fullName>IN</fullName>
                </value>
                <value>
                    <fullName>IA</fullName>
                </value>
                <value>
                    <fullName>KS</fullName>
                </value>
                <value>
                    <fullName>KY</fullName>
                </value>
                <value>
                    <fullName>LA</fullName>
                </value>
                <value>
                    <fullName>ME</fullName>
                </value>
                <value>
                    <fullName>MD</fullName>
                </value>
                <value>
                    <fullName>MA</fullName>
                </value>
                <value>
                    <fullName>MI</fullName>
                </value>
                <value>
                    <fullName>MN</fullName>
                </value>
                <value>
                    <fullName>MS</fullName>
                </value>
                <value>
                    <fullName>MO</fullName>
                </value>
                <value>
                    <fullName>MT</fullName>
                </value>
                <value>
                    <fullName>NE</fullName>
                </value>
                <value>
                    <fullName>NV</fullName>
                </value>
                <value>
                    <fullName>NH</fullName>
                </value>
                <value>
                    <fullName>NJ</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>VASA_Response_Status__c</fullName>
        <label>Service Availability Response Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>ADDRESS RECORD CREATED</fullName>
                    <default>true</default>
                    <label>ADDRESS RECORD CREATED</label>
                </value>
                <value>
                    <fullName>ADDRESS EXACT MATCH</fullName>
                </value>
                <value>
                    <fullName>ADDRESS NO MATCH</fullName>
                </value>
                <value>
                    <fullName>POSSIBLE MATCHES</fullName>
                </value>
                <value>
                    <fullName>SERVICE AVAILABILITY CHECKED</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Zip_Code__c</fullName>
        <label>Zip Code</label>
        <length>5</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>AT&amp;T Customer Site</label>
    <nameField>
        <displayFormat>ADD-{000000}</displayFormat>
        <label>Site #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AT&amp;T Customer Sites</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

secondfile/classes/ExportCustomerSitesController.cls
public class ExportCustomerSitesController{


            String   actionType = 'ExportSites';

public WrapperUIRenderComponent wrcSites{get;set;}
WrapperUIRenderComponentBuilder      wrcbSites= null;

public ExportCustomerSitesController(){
try{
    wrcSites= new WrapperUIRenderComponent('Customer'+actionType);
    wrcbSites= new WrapperUIRenderComponentBuilder (wrcSites,'ExcelSiteList','BuyFlow','Flow',actionType);
    //callLoadExportSites(''); 
    }catch(Exception e){
    applicationException  ae= new applicationException ('00001','Exception caught while performning export of customer sites',e);
   System.debug('applicationException  caught is:'+ae);
   throw ae;
    }
}
public String sitesString{get;set;}
public WrapperUIRenderComponent callLoadExportSites(String sitesStringp){

 

   List<String> sites =sitesStringp.split(',');
   
    loadExportSites(sites);
    return wrcSites;
}
public void loadExportSites(List<String> sites){

  
List<CustomerSite__c> listOfSitesToExport = new List<CustomerSite__c>();
listOfSitesToExport = [Select Id, Site_Name__c, City__c, State__c, Address_Line__c, Zip_Code__c, Site_Description__c, BRASS_Response_Status__c, Phone__c,  VASA_Response_Status__c, Location__c, RoomBuildingFloorInput__c From CustomerSite__c Where Id in :sites];
system.debug('@@@@'+ listOfSitesToExport);
        integer i=2;

        loadExportSitesHeader(wrcbSites);
            for(CustomerSite__c obj : listOfSitesToExport ) {
                loadExportSitesData(wrcbSites,obj,i);
                i++;
            }

system.debug('wrcSites is:'+wrcSites);

}

public void loadExportSitesData(WrapperUIRenderComponentBuilder wrcbSites ,CustomerSite__c obj,integer i){
      wrcbSites.loadSectionElementAsCore('SiteName',obj.Site_Name__c,obj.id+'_SiteName',obj.id,i,1,false);           
                  wrcbSites.loadSectionElementAsCore('Address',obj.Address_Line__c,obj.id+'_'+'Address',obj.id,i,2,false);           
                  wrcbSites.loadSectionElementAsCore('Location',obj.Location__c,obj.id+'_'+'Location',obj.id,i,3,false);           
                //(obj.RoomBuildingFloorInput__c != null ?''+obj.RoomBuildingFloorInput__c:'')
                  wrcbSites.loadSectionElementAsCore('Location #',obj.RoomBuildingFloorInput__c != null ?''+obj.RoomBuildingFloorInput__c:'',obj.id+'_'+'Location #',obj.id,i,4,false);           
                  wrcbSites.loadSectionElementAsCore('City',obj.City__c,obj.id+'_'+'City',obj.id,i,5,false);           
                  wrcbSites.loadSectionElementAsCore('State',obj.State__c,obj.id+'_'+'State',obj.id,i,6,false);           
                  wrcbSites.loadSectionElementAsCore('Zip',obj.Zip_Code__c,obj.id+'_'+'Zip',obj.id,i,7,false);           
                  wrcbSites.loadSectionElementAsCore('Phone',obj.Phone__c,obj.id+'_'+'Phone',obj.id,i,8,false);           
                  wrcbSites.loadSectionElementAsCore('Status',obj.VASA_Response_Status__c,obj.id+'_'+'Status',obj.id,i,9,false);           
                
}

public void loadExportSitesHeader(WrapperUIRenderComponentBuilder wrcbSites ){
wrcbSites.loadSectionElementAsCore('SiteName','SiteName','SiteName','TeableHeader',1,1,false);           
  wrcbSites.loadSectionElementAsCore('Address','Address','Address','TeableHeader',1,2,false);           
     wrcbSites.loadSectionElementAsCore('Location','Location','Location','TeableHeader',1,3,false);           
     wrcbSites.loadSectionElementAsCore('Location #','Location #','Location #','TeableHeader',1,4,false);           
     wrcbSites.loadSectionElementAsCore('City','City','City','TeableHeader',1,5,false);           
     wrcbSites.loadSectionElementAsCore('State','State','State','TeableHeader',1,6,false);           
     wrcbSites.loadSectionElementAsCore('Zip','Zip','Zip','TeableHeader',1,7,false);           
     wrcbSites.loadSectionElementAsCore('Phone','Phone','Phone','TeableHeader',1,8,false);           
       wrcbSites.loadSectionElementAsCore('Status','Status','Status','TeableHeader',1,9,false);             
}

WrapperUIRenderComponent getSitesWRC(){
    return wrcSites;
}
}