secondfile/objects/Deal_Hash__c.object
<CustomObject>
    <fields>
        <fullName>RDS_Version_Select__c</fullName>
        <label>RDS Version Select</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>ALL</fullName>
                </value>
                <value>
                    <fullName>1</fullName>
                    <default>true</default>
                    <label>1</label>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>6</fullName>
                </value>
                <value>
                    <fullName>7</fullName>
                </value>
                <value>
                    <fullName>8</fullName>
                </value>
                <value>
                    <fullName>9</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
                <value>
                    <fullName>11</fullName>
                </value>
                <value>
                    <fullName>12</fullName>
                </value>
                <value>
                    <fullName>13</fullName>
                </value>
                <value>
                    <fullName>14</fullName>
                </value>
                <value>
                    <fullName>15</fullName>
                </value>
                <value>
                    <fullName>16</fullName>
                </value>
                <value>
                    <fullName>17</fullName>
                </value>
                <value>
                    <fullName>18</fullName>
                </value>
                <value>
                    <fullName>19</fullName>
                </value>
                <value>
                    <fullName>20</fullName>
                </value>
                <value>
                    <fullName>21</fullName>
                </value>
                <value>
                    <fullName>22</fullName>
                </value>
                <value>
                    <fullName>23</fullName>
                </value>
                <value>
                    <fullName>24</fullName>
                </value>
                <value>
                    <fullName>25</fullName>
                </value>
                <value>
                    <fullName>26</fullName>
                </value>
                <value>
                    <fullName>27</fullName>
                </value>
                <value>
                    <fullName>28</fullName>
                </value>
                <value>
                    <fullName>29</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>RDS_Version__c</fullName>
        <defaultValue>1</defaultValue>
        <label>RDS Version</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>RDS-Deal Hash</label>
    <nameField>
        <displayFormat>DH-{00000}</displayFormat>
        <label>Deal Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RDS-Deal Hash</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

secondfile/objects/RDS_Premise_Details__c.object
<CustomObject>
    <fields>
        <fullName>Best_Available_Due_Date__c</fullName>
        <description>Premise Details-Order Related Data-Best Available Due Date</description>
        <label>Best Available Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DealHash__c</fullName>
        <description>For Relating Premise with Parent Deal Hash Record</description>
        <label>Deal Hash</label>
        <referenceTo>Deal_Hash__c</referenceTo>
        <relationshipLabel>RDS-Premise Details</relationshipLabel>
        <relationshipName>Premise</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>GRID_Premise_ID__c</fullName>
        <label>GRID Premise ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Premise_Number__c</fullName>
        <label>Premise Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Premise_Street_Name__c</fullName>
        <label>Premise Street Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Premise_Street_Number__c</fullName>
        <label>Premise Street Number</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RDS_Version__c</fullName>
        <defaultValue>1</defaultValue>
        <label>RDS Version</label>
        <precision>15</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Request_Due_Date__c</fullName>
        <description>Premise Details-Order Related Data-Request Due Date</description>
        <label>Request Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Service_Type__c</fullName>
        <label>Service Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Transport_Type__c</fullName>
        <label>Transport Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>RDS-Premise Details</label>
    <nameField>
        <displayFormat>P - {000000}</displayFormat>
        <label>Premise Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RDS-Premise Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

secondfile/classes/API_PremiseRelatedList_Controller.cls
public Class API_PremiseRelatedList_Controller{

public List<RDS_Premise_Details__c> prlist{get;set;}
public List<Deal_Hash__c>dhlist = new List<Deal_Hash__c>();
public String RDSVersion {get;set;}
public String DhRecordId;
public String version;
public String dealname;
public String msg {get;set;}
public Boolean flagAll{get;set;}

    public API_PremiseRelatedList_Controller(ApexPages.StandardController controller) {
    DhRecordId=apexpages.currentpage().getparameters().get('id');
    dhlist = [Select id,Name,RDS_Version_Select__c from Deal_Hash__c where id=:DhRecordId];
    for(Deal_Hash__c dhrecord:dhlist)
    {
    version = dhrecord.RDS_Version_Select__c;
    dealname = dhrecord.Name;
    System.debug('@@@Version'+version );
        
    
        if(version=='ALL')
         {
            flagAll= true;
         }
    }
    if(version == null){
            System.debug('IN');
            ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.ERROR,'Please select RDS Version to get the Premise Details.'); 
            ApexPages.addMessage(myMsg); 
        }
        else{
                if(flagAll== true)
                {
                   prlist = [Select id,DealHash__c,RDS_Version__c,Name,Premise_Number__c,GRID_Premise_ID__c,Service_Type__c,Transport_Type__c,Premise_Street_Number__c,Premise_Street_Name__c,Best_Available_Due_Date__c,Request_Due_Date__c FROM RDS_Premise_Details__c where DealHash__c=:DhRecordId order by RDS_Version__c asc];
                   system.debug('ALL works');
                }
                else
                {
                  prlist = [Select id,DealHash__c,RDS_Version__c,Name,Premise_Number__c,GRID_Premise_ID__c,Service_Type__c,Transport_Type__c,Premise_Street_Number__c,Premise_Street_Name__c,Best_Available_Due_Date__c,Request_Due_Date__c FROM RDS_Premise_Details__c WHERE RDS_Version__c=: decimal.valueOf(Version) AND DealHash__c=:DhRecordId]; 
                 system.debug('filter works');
                } 
               
               if(prlist.size()==0)
               {   system.debug('@@@@@@@'+prlist);
                   ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.ERROR,'No Matching Premise details found for the selected RDS Version'); 
                   ApexPages.addMessage(myMsg); 
               }
           }
}

public PageReference newRecord()
{
   PageReference newrec = new PageReference(Label.API_DealHashVersionDisplay1+'='+dealname+Label.API_DealHashVersionDisplay2+'='+DhRecordId+Label.API_DealHashVersionDisplay3+'='+DhRecordId);
    return newrec;

}
}