secondfile/objects/DHStatus_Connection_Level_Data__c.object
<CustomObject>
    <description>RDS-Premise Details - DHStatus-Update Deal Hash Details - DHStatus-Logical Provisioning-DHStatus-Access Circuit Data--DHStatus-Connection Level Data</description>
    <fields>
        <fullName>DHStatus_Connection_Level_Data__c</fullName>
        <label>DHStatus-Connection Level Data</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>DHStatus_Update_Deal_Hash_Detail_Premise__c</fullName>
        <formula>DHStatus_Ethernet_Access_Circuit_Data__r.DHStatus_Access_Circuit_Data__r.DHStatus_Logical_Provisioning__r.DHStatus_Update_IDH__r.DHStatus_Update_Deal_Hash_Details__r.Premise_Number__c</formula>
        <label>DHStatus Update Deal Hash Detail Premise</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DHStatus_Update_Deal_Hash_Detials_ID__c</fullName>
        <formula>DHStatus_Ethernet_Access_Circuit_Data__r.DHStatus_Access_Circuit_Data__r.DHStatus_Logical_Provisioning__r.DHStatus_Update_IDH__r.DHStatus_Update_Deal_Hash_Details__r.Id</formula>
        <label>DHStatus Update Deal Hash Detials ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DHStatus_Update_IDH_Data_Type__c</fullName>
        <formula>DHStatus_Ethernet_Access_Circuit_Data__r.DHStatus_Access_Circuit_Data__r.DHStatus_Logical_Provisioning__r.DHStatus_Update_IDH__r.Data_Type__c</formula>
        <label>DHStatus Update IDH Data Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DHStatus_Update_IDH__c</fullName>
        <formula>DHStatus_Ethernet_Access_Circuit_Data__r.DHStatus_Access_Circuit_Data__r.DHStatus_Logical_Provisioning__r.DHStatus_Update_IDH__r.Id</formula>
        <label>DHStatus Update IDH</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>V4_LAN_Address_Mask__c</fullName>
        <label>V4 LAN Address Mask</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>V4_LAN_IP_Address__c</fullName>
        <label>V4 LAN IP Address</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>V4_WAN_Address_Mask__c</fullName>
        <description>RDS-Premise Details - DHStatus-Update Deal Hash Details - DHStatus-Logical Provisioning-DHStatus-Access Circuit Data-DHStatus-Connection Level Data-V4WANIPAddressData
-V4 WAN Address Mask</description>
        <label>V4 WAN Address Mask</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>V4_WAN_CER_IP_Address__c</fullName>
        <description>RDS-Premise Details - DHStatus-Update Deal Hash Details - DHStatus-Logical Provisioning-DHStatus-Access Circuit Data-DHStatus-Connection Level Data-V4WANIPAddressData
-V4 WAN CER IP Address</description>
        <label>V4 WAN CER IP Address</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>V4_WAN_IP_Address__c</fullName>
        <description>RDS-Premise Details - DHStatus-Update Deal Hash Details - DHStatus-Logical Provisioning-DHStatus-Access Circuit Data-DHStatus-Connection Level Data-V4WANIPAddressData
-V4 WAN IP Address</description>
        <label>V4 WAN IP Address</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>V4_WAN_PER_IP_Address__c</fullName>
        <description>RDS-Premise Details - DHStatus-Update Deal Hash Details - DHStatus-Logical Provisioning-DHStatus-Access Circuit Data-DHStatus-Connection Level Data-V4WANIPAddressData
-V4 WAN PER IP Address</description>
        <label>V4 WAN PER IP Address</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>V6WAN_PER_IP_Address__c</fullName>
        <description>RDS-Premise Details - DHStatus-Update Deal Hash Details - DHStatus-Logical Provisioning-DHStatus-Access Circuit Data-DHStatus-Connection Level Data-V6WANIPAddressData
-V6WAN PER IP Address</description>
        <label>V6WAN PER IP Address</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>V6_LAN_Address_Mask__c</fullName>
        <label>V6 LAN Address Mask</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>V6_LAN_IP_Address__c</fullName>
        <label>V6 LAN IP Address</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>V6_WAN_Address_Mask__c</fullName>
        <label>V6 WAN Address Mask</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>V6_WAN_CER_IP_Address__c</fullName>
        <description>RDS-Premise Details - DHStatus-Update Deal Hash Details - DHStatus-Logical Provisioning-DHStatus-Access Circuit Data-DHStatus-Connection Level Data-V6WANIPAddressData
-V6 WAN CER IP Address</description>
        <label>V6 WAN CER IP Address</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>V6_WAN_IP_Address__c</fullName>
        <description>RDS-Premise Details - DHStatus-Update Deal Hash Details - DHStatus-Logical Provisioning-DHStatus-Access Circuit Data-DHStatus-Connection Level Data-V6WANIPAddressData
- V6 WAN IP Address</description>
        <label>V6 WAN IP Address</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>DHStatus-Connection Level Data</label>
    <nameField>
        <displayFormat>CLD-{00000}</displayFormat>
        <label>DHStatus-Connection Level Data Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DHStatus-Connection Level Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

example/secondfile/objects/DHStatus_Update_Deal_Hash_Details__c.object
<CustomObject>
    <fields>
        <fullName>Premise_Number__c</fullName>
        <label>Premise Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>V4_CER_IP_Address__c</fullName>
        <label>V4 CER IP Address</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>V4_LAN_Address_Mask__c</fullName>
        <label>V4 LAN Address Mask</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>V4_LAN_IP_Address__c</fullName>
        <label>V4 LAN IP Address</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>V4_PER_IP_Address__c</fullName>
        <label>V4 PER IP Address</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>V4_WAN_Address_Mask__c</fullName>
        <label>V4 WAN Address Mask</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>V4_WAN_IP_Address__c</fullName>
        <label>V4 WAN IP Address</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>V6_CER_IP_Address__c</fullName>
        <label>V6 CER IP Address</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>V6_LAN_Address_Mask__c</fullName>
        <label>V6 LAN Address Mask</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>V6_LAN_IP_Address__c</fullName>
        <label>V6 LAN IP Address</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>V6_PER_IP_Address__c</fullName>
        <label>V6 PER IP Address</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>V6_WAN_Address_Mask__c</fullName>
        <label>V6 WAN Address Mask</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>V6_WAN_IP_Address__c</fullName>
        <label>V6 WAN IP Address</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>DHStatus-Update Deal Hash Details</label>
    <nameField>
        <displayFormat>DHS-{0000}</displayFormat>
        <label>DHStatus-RDS Update Deal Hash Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DHStatus-Update Deal Hash Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

example/secondfile/objects/DHStatus_Update_IDH__c.object
<CustomObject>
    <fields>
        <fullName>DHStatus_Update_Deal_Hash_Details__c</fullName>
        <label>DHStatus-Update Deal Hash Details</label>
        <referenceTo>DHStatus_Update_Deal_Hash_Details__c</referenceTo>
        <relationshipLabel>DHStatus – Update IDHs</relationshipLabel>
        <relationshipName>DHStatus_Update_IDHs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Data_Type__c</fullName>
        <label>Data Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>VLAN_V4_CER_IP_Address__c</fullName>
        <label>VLAN V4 CER IP Address</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>VLAN_V4_LAN_Address_Mask__c</fullName>
        <label>VLAN V4 LAN Address Mask</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>VLAN_V4_LAN_IP_Address__c</fullName>
        <label>VLAN V4 LAN IP Address</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>VLAN_V4_PER_IP_Address__c</fullName>
        <label>VLAN V4 PER IP Address</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>VLAN_V4_WAN_Address_Mask__c</fullName>
        <label>VLAN V4 WAN Address Mask</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>VLAN_V4_WAN_IP_Address__c</fullName>
        <label>VLAN V4 WAN IP Address</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>VLAN_V6_CER_IP_Address__c</fullName>
        <label>VLAN V6 CER IP Address</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>VLAN_V6_LAN_Address_Mask__c</fullName>
        <label>VLAN V6 LAN Address Mask</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>VLAN_V6_LAN_IP_Address__c</fullName>
        <label>VLAN V6 LAN IP Address</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>VLAN_V6_PER_IP_Address__c</fullName>
        <label>VLAN V6 PER IP Address</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>VLAN_V6_WAN_Address_Mask__c</fullName>
        <label>VLAN V6 WAN Address Mask</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>VLAN_V6_WAN_IP_Address__c</fullName>
        <label>VLAN V6 WAN IP Address</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>DHStatus – Update IDH</label>
    <nameField>
        <displayFormat>DH-IDH-{000000}</displayFormat>
        <label>DHStatus – Update IDH  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DHStatus – Update IDHs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

secondfile/classes/API_DHStatusConnectionLevelDataHandler.cls
/* Component Name :API_DHStatusConnectionLevelDataHandler     
Requirement/User Story Number : New IDH Structure    
Requirement Description:populating DHStatus-Update Deal Hash Details Fields
Component Author:Accenture IDC     
Created Date: 25th november 2014      
Version:1.0     
*/   
 
public with sharing class API_DHStatusConnectionLevelDataHandler extends SITriggerOperations.SITriggerImpl{
// To be used for Future after insert operations     
     public override boolean onAfterInsert (SObject[] newObjects){        
         try{ 
             UpdateDHStatusUpdateDealHashDetailsFields(newObjects);
            }        
         catch (exception e){
                e.getMessage();        
          } 
         return true;    
      } 
      
 /*    public override boolean onAfterUpdate(SObject[] oldObjects, SObject[] newObjects, Map<Id, SObject>  newObjectsMap){
            try{
               
               }        
            catch (exception e){ 
                   e.getMessage();        
             }
            return true;    
      } */
      public override boolean onAfterDelete(SObject[] oldObjects, Map<Id, SObject>  oldObjectsMap){        
         try{ 
             ClearDHStatusUpdateDealHashFields(oldObjects);
            }        
         catch (exception e){
                e.getMessage();        
          } 
         return true;    
      } 
 public void UpdateDHStatusUpdateDealHashDetailsFields(SObject[] newObjects)
     {
         List<DHStatus_Connection_Level_Data__c> DHStatusCLDList=newObjects;
         Set<String> IDHIdSet=new Set<String>();
         List<DHStatus_Update_IDH__c> IDHList=new List<DHStatus_Update_IDH__c>();
         Map<Id,DHStatus_Update_IDH__c> IDHMap=new Map<Id,DHStatus_Update_IDH__c>();
         for(DHStatus_Connection_Level_Data__c dcl:DHStatusCLDList)
         {
           
                 IDHIdSet.add(dcl.DHStatus_Update_IDH__c);
            
         }
            if(IDHIdSet.size()>0)
            {
              IDHList=[select Id,Data_Type__c,VLAN_V4_CER_IP_Address__c,VLAN_V4_LAN_Address_Mask__c,VLAN_V4_LAN_IP_Address__c,VLAN_V4_PER_IP_Address__c,VLAN_V4_WAN_Address_Mask__c,VLAN_V4_WAN_IP_Address__c,VLAN_V6_CER_IP_Address__c,VLAN_V6_LAN_Address_Mask__c,VLAN_V6_LAN_IP_Address__c,VLAN_V6_PER_IP_Address__c,VLAN_V6_WAN_Address_Mask__c,VLAN_V6_WAN_IP_Address__c from DHStatus_Update_IDH__c WHERE Id IN:IDHIdSet AND Data_Type__c='Vlan'];  
            } 
         if(IDHList.size()>0)
         {
             for(DHStatus_Update_IDH__c idh:IDHList)
             {
                 for(DHStatus_Connection_Level_Data__c dcld:DHStatusCLDList)
                 {
                     if(idh.Id==dcld.DHStatus_Update_IDH__c && idh.Data_Type__c=='Vlan')
                     {
                         idh.VLAN_V4_CER_IP_Address__c=dcld.V4_WAN_CER_IP_Address__c;
                         idh.VLAN_V6_CER_IP_Address__c=dcld.V6_WAN_CER_IP_Address__c;
                         
                         idh.VLAN_V4_PER_IP_Address__c=dcld.V4_WAN_PER_IP_Address__c;
                         idh.VLAN_V6_PER_IP_Address__c=dcld.V6WAN_PER_IP_Address__c;
                         
                         idh.VLAN_V4_WAN_IP_Address__c=dcld.V4_WAN_IP_Address__c;
                         idh.VLAN_V6_WAN_IP_Address__c=dcld.V6_WAN_IP_Address__c;
                         
                         idh.VLAN_V4_WAN_Address_Mask__c=dcld.V4_WAN_Address_Mask__c;
                         idh.VLAN_V6_WAN_Address_Mask__c=dcld.V6_WAN_Address_Mask__c;
                         
                         idh.VLAN_V4_LAN_IP_Address__c=dcld.V4_LAN_IP_Address__c;
                         idh.VLAN_V6_LAN_IP_Address__c=dcld.V6_LAN_IP_Address__c;
                         
                         idh.VLAN_V4_LAN_Address_Mask__c=dcld.V4_LAN_Address_Mask__c;
                         idh.VLAN_V6_LAN_Address_Mask__c=dcld.V6_LAN_Address_Mask__c;
                         IDHMap.put(idh.Id,idh);
                     }
                 }
             }
         }
         if(IDHMap.size()>0)
         {
             try
             {
                 update IDHMap.values();
             }
             Catch(Exception e)
             {
             }
         }
             
         
         /*List<DHStatus_Connection_Level_Data__c> DHStatusCLDList=newObjects;
         Set<String> DHStatusUDHDIdSet=new Set<String>();
         Set<String> DHStatusUDHDPremiseSet=new Set<String>();
         List<DHStatus_Update_Deal_Hash_Details__c> DHStatusUDHDList=new List<DHStatus_Update_Deal_Hash_Details__c>();
         Map<Id,DHStatus_Update_Deal_Hash_Details__c> DHStatusUDHDMap=new Map<Id,DHStatus_Update_Deal_Hash_Details__c>();
         for(DHStatus_Connection_Level_Data__c dcl:DHStatusCLDList)
         {
             if(dcl.V4_WAN_CER_IP_Address__c!=NULL || dcl.V6_WAN_CER_IP_Address__c!=NULL || dcl.V4_WAN_PER_IP_Address__c!=NULL || dcl.V6WAN_PER_IP_Address__c!=NULL || dcl.V4_WAN_IP_Address__c!=NULL || dcl.V6_WAN_IP_Address__c!=NULL || dcl.V4_WAN_Address_Mask__c!=NULL || dcl.V6_WAN_Address_Mask__c!=NULL || dcl.V4_LAN_IP_Address__c!=NULL || dcl.V6_LAN_IP_Address__c!=NULL || dcl.V4_LAN_Address_Mask__c!=NULL || dcl.V6_LAN_Address_Mask__c!=NULL)
             {
                 DHStatusUDHDIdSet.add(dcl.DHStatus_Update_Deal_Hash_Detials_ID__c);
                 DHStatusUDHDPremiseSet.add(dcl.DHStatus_Update_Deal_Hash_Detail_Premise__c);
             }
             
         }
              
             if(DHStatusUDHDIdSet.size()>0 && DHStatusUDHDPremiseSet.size()>0)
          {
            DHStatusUDHDList=[select Id,Premise_Number__c,V4_CER_IP_Address__c,V6_CER_IP_Address__c,V4_PER_IP_Address__c,V6_PER_IP_Address__c,V4_WAN_IP_Address__c,V6_WAN_IP_Address__c,V4_WAN_Address_Mask__c,V6_WAN_Address_Mask__c,V4_LAN_IP_Address__c,V6_LAN_IP_Address__c,V4_LAN_Address_Mask__c,V6_LAN_Address_Mask__c from DHStatus_Update_Deal_Hash_Details__c WHERE Id IN:DHStatusUDHDIdSet AND Premise_Number__c IN:DHStatusUDHDPremiseSet];
          }
          
          if(DHStatusUDHDList.size()>0)
          {
              for(DHStatus_Update_Deal_Hash_Details__c dhud:DHStatusUDHDList)
              {
                  for(DHStatus_Connection_Level_Data__c dcld:DHStatusCLDList)
                  {
                      if(dhud.Id==dcld.DHStatus_Update_Deal_Hash_Detials_ID__c && dhud.Premise_Number__c == dcld.DHStatus_Update_Deal_Hash_Detail_Premise__c && dcld.DHStatus_Update_IDH_Data_Type__c == 'Vlan')
                       {
                           System.debug('i am in');
                          dhud.V4_CER_IP_Address__c=dcld.V4_WAN_CER_IP_Address__c;
                          dhud.V6_CER_IP_Address__c=dcld.V6_WAN_CER_IP_Address__c;
                          dhud.V4_PER_IP_Address__c=dcld.V4_WAN_PER_IP_Address__c;
                          dhud.V6_PER_IP_Address__c=dcld.V6WAN_PER_IP_Address__c;                          
                          dhud.V4_WAN_IP_Address__c=dcld.V4_WAN_IP_Address__c;
                          dhud.V6_WAN_IP_Address__c=dcld.V6_WAN_IP_Address__c;
                          dhud.V4_WAN_Address_Mask__c=dcld.V4_WAN_Address_Mask__c;
                          dhud.V6_WAN_Address_Mask__c=dcld.V6_WAN_Address_Mask__c;
                          dhud.V4_LAN_IP_Address__c=dcld.V4_LAN_IP_Address__c;
                          dhud.V6_LAN_IP_Address__c=dcld.V6_LAN_IP_Address__c;
                          dhud.V4_LAN_Address_Mask__c=dcld.V4_LAN_Address_Mask__c;
                          dhud.V6_LAN_Address_Mask__c=dcld.V6_LAN_Address_Mask__c;
                          DHStatusUDHDMap.put(dhud.Id,dhud); 
                       }                       
                  }
              }
          }
       if(DHStatusUDHDMap.size()>0)
       {
           try
           {
               update DHStatusUDHDMap.values();
           }
           Catch(Exception e)
           {
         
           }
       } */
      }
  
  
  //deleting DHStatus Update Deal Hash Details Fields.
  public void ClearDHStatusUpdateDealHashFields(SObject[] oldObjects)
  {
       List<DHStatus_Connection_Level_Data__c> DeleteDHStatusCLDList=oldObjects; 
       Map<String,DHStatus_Connection_Level_Data__c> DeleteDHStatusCLDMap=new Map<String,DHStatus_Connection_Level_Data__c>();
       Map<Id,DHStatus_Update_IDH__c> IDHMap=new Map<Id,DHStatus_Update_IDH__c>();
       for(DHStatus_Connection_Level_Data__c dcl:DeleteDHStatusCLDList)
            {
                DeleteDHStatusCLDMap.put(dcl.DHStatus_Update_IDH__c,dcl);
            }
            
            if(DeleteDHStatusCLDMap!=NULL || !DeleteDHStatusCLDMap.isEmpty())
            {
               for(DHStatus_Update_IDH__c idh:[select Id,Data_Type__c,VLAN_V4_CER_IP_Address__c,VLAN_V4_LAN_Address_Mask__c,VLAN_V4_LAN_IP_Address__c,VLAN_V4_PER_IP_Address__c,VLAN_V4_WAN_Address_Mask__c,VLAN_V4_WAN_IP_Address__c,VLAN_V6_CER_IP_Address__c,VLAN_V6_LAN_Address_Mask__c,VLAN_V6_LAN_IP_Address__c,VLAN_V6_PER_IP_Address__c,VLAN_V6_WAN_Address_Mask__c,VLAN_V6_WAN_IP_Address__c from DHStatus_Update_IDH__c WHERE Id IN:DeleteDHStatusCLDMap.keySet() AND Data_Type__c='Vlan'])  
                {
                         idh.VLAN_V4_CER_IP_Address__c=NULL;
                         idh.VLAN_V6_CER_IP_Address__c=NULL;
                         
                         idh.VLAN_V4_PER_IP_Address__c=NULL;
                         idh.VLAN_V6_PER_IP_Address__c=NULL;
                         
                         idh.VLAN_V4_WAN_IP_Address__c=NULL;
                         idh.VLAN_V6_WAN_IP_Address__c=NULL;
                         
                         idh.VLAN_V4_WAN_Address_Mask__c=NULL;
                         idh.VLAN_V6_WAN_Address_Mask__c=NULL;
                         
                         idh.VLAN_V4_LAN_IP_Address__c=NULL;
                         idh.VLAN_V6_LAN_IP_Address__c=NULL;
                         
                         idh.VLAN_V4_LAN_Address_Mask__c=NULL;
                         idh.VLAN_V6_LAN_Address_Mask__c=NULL;
                         IDHMap.put(idh.Id,idh);
                    
                }
            }
            if(IDHMap.size()>0)
            {
               try
               { 
                Update IDHMap.values();
               }
               Catch(Exception e)
               {
               }
            }
        
        /*List<DHStatus_Connection_Level_Data__c> DeleteDHStatusCLDList=oldObjects;
        Map<String,DHStatus_Connection_Level_Data__c> DHStatusCLDMap=new  Map<String,DHStatus_Connection_Level_Data__c>();
        Map<Id,DHStatus_Update_Deal_Hash_Details__c> DHStatusUDHDMap=new Map<Id,DHStatus_Update_Deal_Hash_Details__c>();
        
            for(DHStatus_Connection_Level_Data__c dcl:DeleteDHStatusCLDList)
            {
                DHStatusCLDMap.put(dcl.DHStatus_Update_Deal_Hash_Detials_ID__c,dcl);
            }
            
                      
            if(DHStatusCLDMap!=NULL || !DHStatusCLDMap.isEmpty())
            {
                for(DHStatus_Update_Deal_Hash_Details__c udhd:[select Id,V4_CER_IP_Address__c,V6_CER_IP_Address__c,V4_PER_IP_Address__c,V6_PER_IP_Address__c,V4_WAN_IP_Address__c,V6_WAN_IP_Address__c,V4_WAN_Address_Mask__c,V6_WAN_Address_Mask__c,V4_LAN_IP_Address__c,V6_LAN_IP_Address__c,V4_LAN_Address_Mask__c,V6_LAN_Address_Mask__c from DHStatus_Update_Deal_Hash_Details__c WHERE Id IN:DHStatusCLDMap.keySet()])
                {
                    udhd.V4_CER_IP_Address__c=NULL;
                    udhd.V6_CER_IP_Address__c=NULL;
                    udhd.V4_PER_IP_Address__c=NULL;
                    udhd.V6_PER_IP_Address__c=NULL;
                    udhd.V4_WAN_IP_Address__c=NULL;
                    udhd.V6_WAN_IP_Address__c=NULL;
                    udhd.V4_WAN_Address_Mask__c=NULL;
                    udhd.V6_WAN_Address_Mask__c=NULL;
                    udhd.V4_LAN_IP_Address__c=NULL;
                    udhd.V6_LAN_IP_Address__c=NULL;
                    udhd.V4_LAN_Address_Mask__c=NULL;
                    udhd.V6_LAN_Address_Mask__c=NULL;
                   
                    DHStatusUDHDMap.put(udhd.Id,udhd);
                }
            }
           if(DHStatusUDHDMap.size()>0)
           {
               try
               {
                   update DHStatusUDHDMap.values();
               }
               Catch(Exception e)
               {
               }
           }*/                     
  }  
                           
   }