secondfile/objects/DHStatus_PL_Group_Port_Data__c.object
<CustomObject>
    <fields>
        <fullName>DHStatus_Update_Deal_Hash_Detail_Premise__c</fullName>
        <formula>DHStatus_PrivateLineAccessCircuitData__r.DHStatus_Access_Circuit_Data__r.DHStatus_Logical_Provisioning__r.DHStatus_Update_IDH__r.DHStatus_Update_Deal_Hash_Details__r.Premise_Number__c</formula>
        <label>DHStatus Update Deal Hash Detail Premise</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DHStatus_Update_Deal_Hash_Detials_ID__c</fullName>
        <formula>DHStatus_PrivateLineAccessCircuitData__r.DHStatus_Access_Circuit_Data__r.DHStatus_Logical_Provisioning__r.DHStatus_Update_IDH__r.DHStatus_Update_Deal_Hash_Details__r.Id</formula>
        <label>DHStatus Update Deal Hash Detials ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DHStatus_Update_IDH_Data_Type__c</fullName>
        <formula>DHStatus_PrivateLineAccessCircuitData__r.DHStatus_Access_Circuit_Data__r.DHStatus_Logical_Provisioning__r.DHStatus_Update_IDH__r.Data_Type__c</formula>
        <label>DHStatus Update IDH Data Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>V4_LAN_Address_Mask__c</fullName>
        <label>V4 LAN Address Mask</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>V4_LAN_IP_Address__c</fullName>
        <label>V4 LAN IP Address</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>V4_WAN_Address_Mask__c</fullName>
        <label>V4 WAN Address Mask</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>V4_WAN_CER_IP_Address__c</fullName>
        <label>V4 WAN CER IP Address</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>V4_WAN_IP_Address__c</fullName>
        <label>V4 WAN IP Address</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>V4_WAN_PER_IP_Address__c</fullName>
        <label>V4 WAN PER IP Address</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>V6_LAN_Address_Mask__c</fullName>
        <label>V6 LAN Address Mask</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>V6_LAN_IP_Address__c</fullName>
        <label>V6 LAN IP Address</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>V6_WAN_Address_Mask__c</fullName>
        <label>V6 WAN Address Mask</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>V6_WAN_CER_IP_Address__c</fullName>
        <label>V6 WAN CER IP Address</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>V6_WAN_IP_Address__c</fullName>
        <label>V6 WAN IP Address</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>V6_WAN_PER_IP_Address__c</fullName>
        <label>V6 WAN PER IP Address</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>DHStatus-PL Group Port Data</label>
    <nameField>
        <displayFormat>DHPLGPD-{000000}</displayFormat>
        <label>DHStatus-PL Group Port Data Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DHStatus-PL Group Port Datas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

example/secondfile/objects/DHStatus_Update_Deal_Hash_Details__c.object
<CustomObject>
    <fields>
        <fullName>Premise_Number__c</fullName>
        <label>Premise Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>V4_CER_IP_Address__c</fullName>
        <label>V4 CER IP Address</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>V4_LAN_Address_Mask__c</fullName>
        <label>V4 LAN Address Mask</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>V4_LAN_IP_Address__c</fullName>
        <label>V4 LAN IP Address</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>V4_PER_IP_Address__c</fullName>
        <label>V4 PER IP Address</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>V4_WAN_Address_Mask__c</fullName>
        <label>V4 WAN Address Mask</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>V4_WAN_IP_Address__c</fullName>
        <label>V4 WAN IP Address</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>V6_CER_IP_Address__c</fullName>
        <label>V6 CER IP Address</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>V6_LAN_Address_Mask__c</fullName>
        <label>V6 LAN Address Mask</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>V6_LAN_IP_Address__c</fullName>
        <label>V6 LAN IP Address</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>V6_PER_IP_Address__c</fullName>
        <label>V6 PER IP Address</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>V6_WAN_Address_Mask__c</fullName>
        <label>V6 WAN Address Mask</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>V6_WAN_IP_Address__c</fullName>
        <label>V6 WAN IP Address</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>DHStatus-Update Deal Hash Details</label>
    <nameField>
        <displayFormat>DHS-{0000}</displayFormat>
        <label>DHStatus-RDS Update Deal Hash Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DHStatus-Update Deal Hash Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

secondfile/classes/API_DHStatusPLGroupPortDataHandler.cls
/* Component Name :API_DHStatusPLGroupPortDataHandler  
Requirement/User Story Number : IDH New Derivation       
Requirement Description:Update DHStatus-Update Deal Hash Details Fields
Component Author:Accenture IDC     
Created Date: 25th november 2014      
Version:1.0     
*/   
 
public with sharing class API_DHStatusPLGroupPortDataHandler extends SITriggerOperations.SITriggerImpl{
// To be used for Future after insert operations     
     public override boolean onAfterInsert (SObject[] newObjects){        
         try{ 
                UpdateDHStatusDealHashDetialsFields(newObjects);
            }        
         catch (exception e){
                e.getMessage();        
          } 
         return true;    
      } 
      
    /* public override boolean onAfterUpdate(SObject[] oldObjects, SObject[] newObjects, Map<Id, SObject>  newObjectsMap){
            try{
              
               }        
            catch (exception e){ 
                   e.getMessage();        
             }
            return true;    
      } */
      public override boolean onAfterDelete(SObject[] oldObjects, Map<Id, SObject>  oldObjectsMap){        
         try{ 
             ClearDHStatusUpdateDealHashFields(oldObjects);
            }        
         catch (exception e){
                e.getMessage();        
          } 
         return true;    
      }
  
//populating Corresponding DHStatus-Update Deal Hash Details Fields           
public void UpdateDHStatusDealHashDetialsFields(SObject[] newObjects)
    {
      List<DHStatus_PL_Group_Port_Data__c> DHStatusPLGPDList=newObjects;
      Set<String> DHStatusUDHDIdSet=new Set<String>();
      Set<String> DHStatusUDHDPremiseSet=new Set<String>();
      List<DHStatus_Update_Deal_Hash_Details__c> DHStatusUDHDList=new List<DHStatus_Update_Deal_Hash_Details__c>();
      Map<Id,DHStatus_Update_Deal_Hash_Details__c> DHStatusUDHDMap=new Map<Id,DHStatus_Update_Deal_Hash_Details__c>();
      for(DHStatus_PL_Group_Port_Data__c dhpl:DHStatusPLGPDList)
      {
        
              DHStatusUDHDIdSet.add(dhpl.DHStatus_Update_Deal_Hash_Detials_ID__c);
              DHStatusUDHDPremiseSet.add(dhpl.DHStatus_Update_Deal_Hash_Detail_Premise__c);
          
      }
          if(DHStatusUDHDIdSet.size()>0 && DHStatusUDHDPremiseSet.size()>0)
          {
            DHStatusUDHDList=[select Id,Premise_Number__c,V4_CER_IP_Address__c,V6_CER_IP_Address__c,V4_PER_IP_Address__c,V6_PER_IP_Address__c,V4_WAN_IP_Address__c,V6_WAN_IP_Address__c,V4_WAN_Address_Mask__c,V6_WAN_Address_Mask__c,V4_LAN_IP_Address__c,V6_LAN_IP_Address__c,V4_LAN_Address_Mask__c,V6_LAN_Address_Mask__c from DHStatus_Update_Deal_Hash_Details__c WHERE Id IN:DHStatusUDHDIdSet AND Premise_Number__c IN:DHStatusUDHDPremiseSet];
          }
          if(DHStatusUDHDList.size()>0)
          {
              for(DHStatus_Update_Deal_Hash_Details__c dhud:DHStatusUDHDList)
              {
                  for(DHStatus_PL_Group_Port_Data__c dhplg:DHStatusPLGPDList)
                  {
                      if(dhud.Id==dhplg.DHStatus_Update_Deal_Hash_Detials_ID__c && dhud.Premise_Number__c == dhplg.DHStatus_Update_Deal_Hash_Detail_Premise__c && dhplg.DHStatus_Update_IDH_Data_Type__c == 'GroupPort')
                       {
                          dhud.V4_CER_IP_Address__c=dhplg.V4_WAN_CER_IP_Address__c;
                          dhud.V6_CER_IP_Address__c=dhplg.V6_WAN_CER_IP_Address__c;
                          dhud.V4_PER_IP_Address__c=dhplg.V4_WAN_PER_IP_Address__c;
                          dhud.V6_PER_IP_Address__c=dhplg.V6_WAN_PER_IP_Address__c;                          
                          dhud.V4_WAN_IP_Address__c=dhplg.V4_WAN_IP_Address__c;
                          dhud.V6_WAN_IP_Address__c=dhplg.V6_WAN_IP_Address__c;
                          dhud.V4_WAN_Address_Mask__c=dhplg.V4_WAN_Address_Mask__c;
                          dhud.V6_WAN_Address_Mask__c=dhplg.V6_WAN_Address_Mask__c;
                          dhud.V4_LAN_IP_Address__c=dhplg.V4_LAN_IP_Address__c;
                          dhud.V6_LAN_IP_Address__c=dhplg.V6_LAN_IP_Address__c;
                          dhud.V4_LAN_Address_Mask__c=dhplg.V4_LAN_Address_Mask__c;
                          dhud.V6_LAN_Address_Mask__c=dhplg.V6_LAN_Address_Mask__c;
                          DHStatusUDHDMap.put(dhud.Id,dhud); 
                       }                       
                  }
              }
          }
       if(DHStatusUDHDMap.size()>0)
       {
           try
           {
               update DHStatusUDHDMap.values();
           }
           Catch(Exception e)
           {
         
           }
       }  
      }
  //deleting DHStatus Update Deal Hash Details Fields.
  public void ClearDHStatusUpdateDealHashFields(SObject[] oldObjects)
  {
         
        List<DHStatus_PL_Group_Port_Data__c> DeleteDHStatusPLGroupList=oldObjects;
        Map<String,DHStatus_PL_Group_Port_Data__c> DHStatusPLGroupMap=new  Map<String,DHStatus_PL_Group_Port_Data__c>();
        Map<Id,DHStatus_Update_Deal_Hash_Details__c> DHStatusUDHDMap=new Map<Id,DHStatus_Update_Deal_Hash_Details__c>();
        
            for(DHStatus_PL_Group_Port_Data__c dpl:DeleteDHStatusPLGroupList)
            {
                DHStatusPLGroupMap.put(dpl.DHStatus_Update_Deal_Hash_Detials_ID__c,dpl);
                
            }
            system.debug('#########' +DHStatusPLGroupMap);
               // system.debug('@@@@@@@@@' +dpl.DHStatus_Update_Deal_Hash_Detials_ID__c);
            
                      
            if(DHStatusPLGroupMap!=NULL || !DHStatusPLGroupMap.isEmpty())
            {
                for(DHStatus_Update_Deal_Hash_Details__c udhd:[select Id,V4_CER_IP_Address__c,V6_CER_IP_Address__c,V4_PER_IP_Address__c,V6_PER_IP_Address__c,V4_WAN_IP_Address__c,V6_WAN_IP_Address__c,V4_WAN_Address_Mask__c,V6_WAN_Address_Mask__c,V4_LAN_IP_Address__c,V6_LAN_IP_Address__c,V4_LAN_Address_Mask__c,V6_LAN_Address_Mask__c from DHStatus_Update_Deal_Hash_Details__c WHERE Id IN:DHStatusPLGroupMap.keySet()])
                {
                    udhd.V4_CER_IP_Address__c=NULL;
                    udhd.V6_CER_IP_Address__c=NULL;
                    udhd.V4_PER_IP_Address__c=NULL;
                    udhd.V6_PER_IP_Address__c=NULL;
                    udhd.V4_WAN_IP_Address__c=NULL;
                    udhd.V6_WAN_IP_Address__c=NULL;
                    udhd.V4_WAN_Address_Mask__c=NULL;
                    udhd.V6_WAN_Address_Mask__c=NULL;
                    udhd.V4_LAN_IP_Address__c=NULL;
                    udhd.V6_LAN_IP_Address__c=NULL;
                    udhd.V4_LAN_Address_Mask__c=NULL;
                    udhd.V6_LAN_Address_Mask__c=NULL;
                   
                    DHStatusUDHDMap.put(udhd.Id,udhd);
                }
            }
           if(DHStatusUDHDMap.size()>0)
           {
               try
               {
                   update DHStatusUDHDMap.values();
               }
               Catch(Exception e)
               {
               }
           }                       
  }                      
}