secondfile/objects/DHStatus_Provisioning_Billing_Details__c.object
<CustomObject>
    <description>RDS-Premise Details - DHStatus-Update Deal Hash Details - DHStatus-Billing Update Details-DHStatus-Provisioning Billing Details</description>
    <fields>
        <fullName>Competitive_Discount_Effective_Date__c</fullName>
        <description>RDS-Premise Details - DHStatus-Update Deal Hash Details - DHStatus-Billing Update Details-DHStatus-Provisioning Billing Details-Competitive Discount Effective Date</description>
        <label>Competitive Discount Effective Date</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DHStatusUpdateDealHashDetailsID__c</fullName>
        <formula>DHStatus_Billing_Update_Details__r.DHStatus_Update_IDH__r.DHStatus_Update_Deal_Hash_Details__r.Id</formula>
        <label>DHStatusUpdateDealHashDetailsID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DHStatusUpdateDealHashPremiseNumber__c</fullName>
        <formula>DHStatus_Billing_Update_Details__r.DHStatus_Update_IDH__r.DHStatus_Update_Deal_Hash_Details__r.RDS_Premise_Details_For_DHStatus__r.Premise_Number__c</formula>
        <label>DHStatusUpdateDealHashPremiseNumber</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DHStatus_IDH_Data_Type__c</fullName>
        <formula>DHStatus_Billing_Update_Details__r.DHStatus_Update_IDH__r.Data_Type__c</formula>
        <label>DHStatus IDH Data Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Effective_Date__c</fullName>
        <description>RDS-Premise Details - DHStatus-Update Deal Hash Details - DHStatus-Billing Update Details-DHStatus-Provisioning Billing Details-Effective Date</description>
        <label>Effective Date</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>DHStatus-Provisioning Billing Details</label>
    <nameField>
        <displayFormat>PBD-{0000}</displayFormat>
        <label>DHStatus-Provisioning Billing Details Na</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DHStatus-Provisioning Billing Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

example/secondfile/objects/DHStatus_Update_Deal_Hash_Details__c.object
<CustomObject>
    <fields>
        <fullName>Port_Billing_Activation_Effective_Date__c</fullName>
        <label>Port Billing Activation Effective Date</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Port_Competitive_Discounts_EffectiveDate__c</fullName>
        <label>Port Competitive Discounts EffectiveDate</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Premise_Number__c</fullName>
        <label>Premise Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>DHStatus-Update Deal Hash Details</label>
    <nameField>
        <displayFormat>DHS-{0000}</displayFormat>
        <label>DHStatus-RDS Update Deal Hash Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DHStatus-Update Deal Hash Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

example/secondfile/classes/API_DHStatusProvisioningHandler.cls
/* Component Name :API_DHStatusProvisioningTriggerHandler   
 Requirement/User Story Number : Provisioning Milestone Report      
Requirement Description:Update DHStatus-Update Deal Hash Details Fields
Component Author:Accenture IDC     
Created Date: 25th november 2014      
Version:1.0     
*/    
public with sharing class API_DHStatusProvisioningHandler extends SITriggerOperations.SITriggerImpl{
/*method*/
public override boolean onAfterInsert (SObject[] newObjects){        
         try{ 
            UpdateDHStatusUpdateDealHashDetailsFields(newObjects);
            }        
         catch (exception e){
                e.getMessage();        
          } 
         return true;    
      } 
          
    public override boolean onAfterDelete(SObject[] oldObjects, Map<Id, SObject>  oldObjectsMap){        
         try{ 
             ClearDHStatusUpdateDealHashFields(oldObjects);
            }        
         catch (exception e){
                e.getMessage();        
          } 
         return true;    
      }
/*populating Port Billing Activation Effective Date,Port Competitive Discounts EffectiveDate on DHStatus-Update Deal Hash Details from DHStatus Provisioning Billing Details  */
public void updateDHStatusUpdateDealHashDetailsFields(SObject[] newObjects)
{
        List<DHStatus_Provisioning_Billing_Details__c> dHStatusLPList=newObjects;
        Set<String> dHStatusUDHDIDSet=new Set<String>();
        Set<String> dHStatusUDHDPremiseNumberSet=new Set<String>();
        List<DHStatus_Update_Deal_Hash_Details__c> dHStatusUDHDList=new List<DHStatus_Update_Deal_Hash_Details__c>();        
        Map<Id,DHStatus_Update_Deal_Hash_Details__c> dHStatusUDHDMap=new Map<Id,DHStatus_Update_Deal_Hash_Details__c>();
        for(DHStatus_Provisioning_Billing_Details__c dlp:DHStatusLPList)
        {
         
                DHStatusUDHDIDSet.add(dlp.DHStatusUpdateDealHashDetailsID__c);
                DHStatusUDHDPremiseNumberSet.add(dlp.DHStatusUpdateDealHashPremiseNumber__c);
                
        }
                        
        if(DHStatusUDHDIDSet.size()>0 && DHStatusUDHDPremiseNumberSet.size()>0)
        {
            DHStatusUDHDList=[select Id,Premise_Number__c,Port_Billing_Activation_Effective_Date__c,Port_Competitive_Discounts_EffectiveDate__c from DHStatus_Update_Deal_Hash_Details__c WHERE Id IN:DHStatusUDHDIDSet AND Premise_Number__c IN:DHStatusUDHDPremiseNumberSet];
        } 
        if(DHStatusUDHDList.size()>0)
        {
            for(DHStatus_Update_Deal_Hash_Details__c udhd:DHStatusUDHDList)
            {
                for(DHStatus_Provisioning_Billing_Details__c dlpp:DHStatusLPList)
                {
                    if(udhd.Id==dlpp.DHStatusUpdateDealHashDetailsID__c && udhd.Premise_Number__c==dlpp.DHStatusUpdateDealHashPremiseNumber__c && dlpp.DHStatus_IDH_Data_Type__c=='Billing')
                        {
                          udhd.Port_Billing_Activation_Effective_Date__c=dlpp.Effective_Date__c;
                          udhd.Port_Competitive_Discounts_EffectiveDate__c=dlpp.Competitive_Discount_Effective_Date__c;
                          DHStatusUDHDMap.put(udhd.Id,udhd);  
                        }    
                }
            }
        }
      if(DHStatusUDHDMap.size()>0)
      {
          try
          {
          update DHStatusUDHDMap.Values();
          }catch(Exception e){
                ATTException.logException( e.getTypeName(), ATTException.constructExceptionMessageString(e));
            }
      }         
  }

/*clear Corresponding DHStatusUpdateDealHash fields after deleting the logical provisioning */
   public void clearDHStatusUpdateDealHashFields(SObject[] oldObjects)
     {
       
        List<DHStatus_Provisioning_Billing_Details__c> deleteDHStatusPBList=oldObjects;
        Map<String,DHStatus_Provisioning_Billing_Details__c> dHStatusPBMap=new  Map<String,DHStatus_Provisioning_Billing_Details__c>();
        Map<Id,DHStatus_Update_Deal_Hash_Details__c> dHStatusUDHDMap=new Map<Id,DHStatus_Update_Deal_Hash_Details__c>();
        
            for(DHStatus_Provisioning_Billing_Details__c dpb:DeleteDHStatusPBList)
            {
                DHStatusPBMap.put(dpb.DHStatusUpdateDealHashDetailsID__c,dpb);
               
            }          
            if(DHStatusPBMap!=NULL || !DHStatusPBMap.isEmpty())
            {
                for(DHStatus_Update_Deal_Hash_Details__c udhd:[select Id,Premise_Number__c,Port_Billing_Activation_Effective_Date__c,Port_Competitive_Discounts_EffectiveDate__c from DHStatus_Update_Deal_Hash_Details__c WHERE Id IN:DHStatusPBMap.keySet()])
                {
                    udhd.Port_Billing_Activation_Effective_Date__c=NULL;
                    udhd.Port_Competitive_Discounts_EffectiveDate__c=NULL;
                    DHStatusUDHDMap.put(udhd.Id,udhd);
                }
            }
           if(DHStatusUDHDMap.size()>0)
           {
               try
               {
                   update DHStatusUDHDMap.values();
               }catch(Exception e){
                ATTException.logException( e.getTypeName(), ATTException.constructExceptionMessageString(e));
            }
           }                            
      }      
 
}