secondfile/objects/DHStatus_Access_Circuit_Data__c.object
<CustomObject>
    <description>RDS-Premise Details - DHStatus-Update Deal Hash Details - DHStatus-Logical Provisioning-DHStatus
-Access Circuit Data</description>
    <fields>
        <fullName>DHStatus_Update_Deal_Hash_Details__c</fullName>
        <formula>DHStatus_Logical_Provisioning__r.DHStatus_Update_Deal_Hash_Details__r.Id</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>DHStatus-Update Deal Hash Details</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Private_Line_Activation_Status__c</fullName>
        <description>RDS-Premise Details - DHStatus-Update Deal Hash Details - DHStatus-Logical Provisioning-DHStatus-Access Circuit Data-Private Line Activation Status</description>
        <label>Private Line Activation Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>DHStatus-Access Circuit Data</label>
    <nameField>
        <displayFormat>ACD-{0000}</displayFormat>
        <label>DHStatus-Access Circuit Data Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DHStatus-Access Circuit Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

example/secondfile/objects/DHStatus_Update_Deal_Hash_Details__c.object
<CustomObject>
    <fields>
        <fullName>Test_and_Turn_Up__c</fullName>
        <label>TTU Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>DHStatus-Update Deal Hash Details</label>
    <nameField>
        <displayFormat>DHS-{0000}</displayFormat>
        <label>DHStatus-RDS Update Deal Hash Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DHStatus-Update Deal Hash Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

example/secondfile/classes/APIDHStatus_AccessCircuit_TriggerHandler.cls
public with sharing Class APIDHStatus_AccessCircuit_TriggerHandler extends SITriggerOperations.SITriggerImpl{
// To be used for Future after insert operations     
     public override boolean onAfterInsert (SObject[] newObjects){        
         try{ 
             populateTestAndTurnUpDate(newObjects);
            
            }        
         catch (exception e){
                e.getMessage();        
          } 
         return true;    
      }
       
      public override boolean onAfterUpdate(SObject[] oldObjects, SObject[] newObjects, Map<Id, SObject>  newObjectsMap){
            try{
                populateTestAndTurnUpDate(newObjects);
                
               }        
            catch (exception e){ 
                   e.getMessage();        
             }
             return true;    
      }
      public override boolean onAfterDelete(SObject[] oldObjects, Map<Id, SObject>  oldObjectsMap){        
         try{ 
             clearTestandTurnUpDate(oldObjects);
            }        
         catch (exception e){
                e.getMessage();        
          } 
         return true;    
      } 
      
      public void populateTestAndTurnUpDate(SObject[] newObjects){
          List<DHStatus_Access_Circuit_Data__c> listOfcircuit= newObjects;
          Map<Id,DHStatus_Access_Circuit_Data__c> mapofCircuit = new Map<Id,DHStatus_Access_Circuit_Data__c>();
          List<DHStatus_Update_Deal_Hash_Details__c> udhdObjList = new List<DHStatus_Update_Deal_Hash_Details__c>();
          List<DHStatus_Update_Deal_Hash_Details__c> udhdObjListToUpdate = new List<DHStatus_Update_Deal_Hash_Details__c>();
          
          for(DHStatus_Access_Circuit_Data__c cir:listOfcircuit){
              if(cir.Private_Line_Activation_Status__c!= null){                  
                  mapofCircuit.put(cir.DHStatus_Update_Deal_Hash_Details__c,cir);
              }          
          }
         
         if((mapofCircuit!= null)|| (!mapofCircuit.isEmpty())){
             udhdObjList = [select id,Test_and_Turn_Up__c from DHStatus_Update_Deal_Hash_Details__c where id in :mapofCircuit.keySet()]; 
             if(udhdObjList.size()>0){        
                 for(DHStatus_Update_Deal_Hash_Details__c dh:udhdObjList){
                     for(DHStatus_Access_Circuit_Data__c cir :mapofCircuit.values()){ 
                       if(cir.DHStatus_Update_Deal_Hash_Details__c == dh.Id){              
                           dh.Test_and_Turn_Up__c = cir.Private_Line_Activation_Status__c;
                           udhdObjListToUpdate .add(dh);         
                       }       
                     }
                 }
             }
         }
             if(udhdObjListToUpdate.size()>0){
                 try{
                     update udhdObjListToUpdate;
                 }Catch(Exception e){
                     e.getMessage();
                 }
             
             }
         
      }
      public void clearTestandTurnUpDate(SObject[] oldObjects){
          List<DHStatus_Access_Circuit_Data__c> listOfcircuit= oldObjects;
          Map<Id,DHStatus_Access_Circuit_Data__c> mapofCircuit = new Map<Id,DHStatus_Access_Circuit_Data__c>();
          List<DHStatus_Update_Deal_Hash_Details__c> udhdObjList = new List<DHStatus_Update_Deal_Hash_Details__c>();
          List<DHStatus_Update_Deal_Hash_Details__c> udhdObjListToUpdate = new List<DHStatus_Update_Deal_Hash_Details__c>();
          
          for(DHStatus_Access_Circuit_Data__c cir:listOfcircuit){
                               
                  mapofCircuit.put(cir.DHStatus_Update_Deal_Hash_Details__c,cir);
                        
          }
         
         if((mapofCircuit!= null)|| (!mapofCircuit.isEmpty())){
             udhdObjList = [select id,Test_and_Turn_Up__c from DHStatus_Update_Deal_Hash_Details__c where id in :mapofCircuit.keySet()]; 
             if(udhdObjList.size()>0){        
                 for(DHStatus_Update_Deal_Hash_Details__c dh:udhdObjList){
                     for(DHStatus_Access_Circuit_Data__c cir :mapofCircuit.values()){
                       if(cir.DHStatus_Update_Deal_Hash_Details__c == dh.Id){                 
                           dh.Test_and_Turn_Up__c = '';
                           udhdObjListToUpdate .add(dh); 
                       }               
                     }
                 }
             }
         }
             if(udhdObjListToUpdate.size()>0){
                 try{
                     update udhdObjListToUpdate;
                 }Catch(Exception e){
                     e.getMessage();
                 }
             
             }
      }
}