secondfile/objects/Engagement__c.object
<CustomObject>
    <description>Object to store Events and Sponsorships to display on Connect tab</description>
    <fields>
        <fullName>Banner_Status__c</fullName>
        <label>Banner Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Display_On_Landing_Page__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Display On Landing Page</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Published</fullName>
                </value>
                <value>
                    <fullName>Archived</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Engagement</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Engagements</pluralLabel>
    <recordTypes>
        <fullName>Banner</fullName>
        <active>true</active>
        <description>Banner New Record Type</description>
        <label>Banner</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

example/secondfile/classes/SI_EngagementObjectTriggerHandler.cls
public with sharing class SI_EngagementObjectTriggerHandler extends SITriggerOperations.SITriggerImpl{

public override boolean onAfterUpdate(SObject[] oldObjects, SObject[] updatedObjects, Map<Id, SObject> newObjectsMap)
    {
        try
        {
           CheckStatusActiveEngagement(updatedObjects);
        }
        catch (exception e)
        {
            System.debug('Exception : '+ e);
        }
        return true;
    } 
    public override boolean onAfterInsert(SObject[] newObjects)
    {
        try
        {
             CheckStatusActiveEngagement(newObjects);
        }
        catch (exception e)
        {
            System.debug('Exception : '+ e);
        }
        return true;
    }  
    //An Overridden method
    public override boolean onBeforeUpdate(SObject[] oldObjects,SObject[] newObjects,Map<Id,SObject> newObjectsMap) {
        try {
                updateEngagementFields(oldObjects,newObjects);
        }catch (exception e)
        {
            System.debug('Exception : '+ e);
        }
        return true;
    }
    public void CheckStatusActiveEngagement(SObject[] updatedObjects){
    Integer total_size=0;
    List<Engagement__c> EngagementList = updatedObjects;
    total_size=[select count() from Engagement__c where RecordType.Name ='Banner' AND Banner_Status__c='Active'];
    system.debug('*********************************');
    if(total_size>1){
            for(Engagement__c E:EngagementList){
              E.Banner_Status__c.adderror('Only one Engagement Record should have its Banner Status set as Active');
              system.debug('&&&&&&&&&&&');
              }
           }    
    }

//Business logic to update "Display On Landing Page" to false when status change from published to another status.
    public void updateEngagementFields(SObject[] oldObjects,SObject[] newObjects)
    {
        list<Engagement__c> oldList = oldObjects;
        list<Engagement__c> newList = newObjects;
        
        for (Integer i=0; i<newList.size(); i++)
        {
            if(oldList[i].Status__c == SIConstants.Engagement_Status_Published && newList[i].Status__c != SIConstants.Engagement_Status_Published && newList[i].Display_On_Landing_Page__c)
            {
                newList[i].Display_On_Landing_Page__c = false;
            }
        }
    }
}