secondfile/objects/Wireline_Promotion_Rules__c.object
<CustomObject>
    <description>Master Promotions object to store all the promotions created so that Promotion Engine can consume them part of execution.</description>
    <fields>
        <fullName>Bulk_Promotion__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Bulk is required mode when values are more than 100 for single criteria. Example: Address with combination of fields is not supported in Bulk mode.</inlineHelpText>
        <label>Bulk Mode</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Do_Not_Run__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This deactivates promotion regardless of other promotion parameters.</description>
        <inlineHelpText>This deactivates promotion regardless of other promotion parameters.</inlineHelpText>
        <label>Stop Promotion Now</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Expired__c</fullName>
        <defaultValue>false</defaultValue>
        <description>To check the status of the whether the promotion is expired.</description>
        <inlineHelpText>To check the status of the whether the promotion is expired.</inlineHelpText>
        <label>Expired</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Field_Inputs__c</fullName>
        <inlineHelpText>This will hold the key value pairs for each dynamic field configured for this promotion</inlineHelpText>
        <label>Field Inputs</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Promo_Type__c</fullName>
        <inlineHelpText>Type of Promotion</inlineHelpText>
        <label>Promotion Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Rate Card Map</fullName>
                </value>
                <value>
                    <fullName>SP Tier-Term</fullName>
                </value>
                <value>
                    <fullName>Port</fullName>
                </value>
                <value>
                    <fullName>Access</fullName>
                </value>
                <value>
                    <fullName>Feature</fullName>
                </value>
                <value>
                    <fullName>One-Time Charge</fullName>
                </value>
                <value>
                    <fullName>SP</fullName>
                </value>
                <value>
                    <fullName>Order</fullName>
                </value>
                <value>
                    <fullName>Deal Reg</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Select_Fields_Json__c</fullName>
        <label>Select Fields for Json</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <label>Wireline Promotion Rules</label>
    <nameField>
        <displayFormat>Promo-{0000}</displayFormat>
        <label>Promotion ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Wireline Promotion Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

secondfile/objects/WirelinePromoCacheData__c.object
<CustomObject>
    <fields>
        <fullName>cacheKey__c</fullName>
        <label>cacheKey</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>cacheValue__c</fullName>
        <label>cacheValue</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <label>Wireline Promo Cache Data</label>
    <nameField>
        <label>Wireline Promo Cache Data Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Wireline Promo Cache Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

example/secondfile/classes/PromotionCacheFeeder.cls
/******************************************************************************************************************
Name:        PromotionCacheFeeder
Description: This is the helper class which reads the promotions configured and creates the data in the cache. 
             Map will be in this format: 
             <Value>:[<list of promotions>];
             To access the cache data do CachePromotionValueFetcher Object = new CachePromotionValueFetcher();
             Object.get(<value>);
             This will return the list of promotions for every value in all the configured Active promotions. 
Author:      Varun Kumar
Change Log:  10/23/2018     Initial Version 1        Varun Kumar
*******************************************************************************************************************/
public class PromotionCacheFeeder{

    List<Wireline_Promotion_Rules__c> wpr; 
    Set<String> cacheKeySet = new Set<String>(); 
    
    /*Use this constructor when you want to load a particular Promotion*/
    public PromotionCacheFeeder(string promotionid){
        wpr = [select id,Select_Fields_Json__c,Promo_Type__c,Field_Inputs__c from Wireline_Promotion_Rules__c where id =:promotionid AND Bulk_Promotion__c = FALSE];    
    }
    
    /*Use this constructor when you want to load all Promotion*/
    public PromotionCacheFeeder(){
        wpr = [select id,Select_Fields_Json__c,Promo_Type__c,Field_Inputs__c,Do_Not_Run__c,Expired__c from Wireline_Promotion_Rules__c Where Do_Not_Run__c = FALSE AND Expired__c = FALSE AND Bulk_Promotion__c = FALSE];
        System.debug('@@@PromotionCacheFeeder WPR Size: ' + wpr.size());
    }

    /*Call this method for loading the data into Cache. Constructor will only prepare the data to be loaded*/
    public void feedPromotions(){  
       
        WirelinePromoCacheData__c cacheData = [Select cacheKey__c,cacheValue__c from WirelinePromoCacheData__c  limit 1];
        try{
            for(Wireline_Promotion_Rules__c wp : wpr){
                system.debug('@@wprcustom' + wp.id);
                if(wp.Select_Fields_Json__c != null){
                    System.debug('JSON value is: ' + wp.Select_Fields_Json__c);
                    parseJsonforfieldValues(wp.id,wp.Select_Fields_Json__c);
                }
                String sp = wp.Field_Inputs__c;
                if(sp!=null && sp.containsIgnoreCase('SP List')){
                    List<String> ss = sp.split('\\|');
                    System.debug('@@@SP Account List: ' + ss);
                    for(String s : ss){
                        if(s.containsIgnoreCase('SP List')){
                            List<String> spnamesList = s.split(':');
                            System.debug('@@@SP Names After Split 1: '+spnamesList);
                            if(spnamesList.size() >= 2 && spnamesList[1] != null && spnamesList[1] != ''){
                                List<String> spnList = spnamesList[1].split(';');
                                system.debug('@@@SP Names After Split 2: '+spnList);
                                for(String spnl : spnList){
                                    system.debug('@@@SP Name Before Null Check: '+spnl);
                                    spnl = spnl.replaceAll('"', '');
                                    if(spnl != ''){
                                        system.debug('@@@SP Name in loop: '+spnl);
                                        new PromotionCacheBuilder(spnl,wp.Id+'_'+wp.Promo_Type__c); 
                                        spnl = spnl.deleteWhitespace();
                                        spnl= spnl.replaceAll('[|,|.|\\,|\\-|"||:|~|!|@|#|$|%|^|&|*|_|+|=|<|>|?|\\(|\\)|\\{|\\}|\\;|\\\'"]', '');
                                        spnl= spnl.toUpperCase();                                        
                                        cacheKeySet.add(spnl); 
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
        catch(Exception e){ 
            system.debug('Exception '+e.getMessage()+' at line no '+e.getLineNumber());
        }
        cacheData.cacheKey__c = 'cacheKeys';
        cacheData.cacheValue__c =  (String)JSON.serialize(cacheKeySet);
        system.debug('Cachekeyset--->'+cacheKeySet);
        system.debug('-------->'+cacheData);
        update cacheData;
    }
    
    /*This is internal method not for calling from outside. Uses the promotion JSON and loads it into Memory*/
    public void parseJsonforfieldValues(string promotionId, string promotionJson){
        String promotionType='';
        List<string> valueAndPromotion = new List<string>();
        System.debug('@@@Promotion JSON: ' + promotionJson);
        Map<string,object> pJson = (Map<string,object>) JSON.deserializeUntyped(promotionJson);
        
        map<string,object> promotionTypeMap = (map<string,object>)pJson.get('promotionType');
        system.debug('@@@Promotion Type: ' + promotionTypeMap);
        if(promotionTypeMap != null){
            promotionType= (String) promotionTypeMap.get('promotionType'); 
            system.debug('promotion type is: ' + promotionType);
            promotionId = promotionId+'_'+promotionType;
        }
        
        map<string,object> fieldsValuesMap = (map<string,object>)pJson.get('fieldValuesList');
        system.debug('@@@Field Values Map: ' + fieldsValuesMap);
        
        List<object> fieldValueString = (List<object>)fieldsValuesMap.get('fieldValues');
        System.debug('@@@Fields Values String: ' + fieldValueString);
        for(object fieldValue: fieldValueString){
            system.debug('@@fieldValueCustom' + fieldValue);
            string stringWithSemiColon = String.ValueOf(fieldValue);
            system.debug('@@strcustom' + stringWithSemiColon);
            /*if(stringWithSemiColon.contains(';') == true){
                system.debug('@@insideIfcustom');
                stringWithSemiColon = stringWithSemiColon.replaceAll(';' , ',');
            }*/
            List<String> fieldValueLst = new List<String>();
            if(stringWithSemiColon.contains(';') == true){
                system.debug('contains');
                fieldValueLst = stringWithSemiColon.split(';');
            }
            else{
                fieldValueLst.add(stringWithSemiColon);
            }
            system.debug('@@@Field Value List: ' + fieldValueLst);
            for(integer i =0; i<fieldValueLst.size();i++){
                String cacheKey =  (String) fieldValueLst [i];
                System.debug('@@@Cache Key: ' +cacheKey );
                new PromotionCacheBuilder(cacheKey ,promotionId);
                cacheKey = cacheKey.deleteWhitespace();
                cacheKey= cacheKey.replaceAll('[|,|.|\\,|\\-|"||:|~|!|@|#|$|%|^|&|*|_|+|=|<|>|?|\\(|\\)|\\{|\\}|\\;|\\\'"]', '');
                cacheKey = cacheKey.replace('/','');
                cacheKey = cacheKey.replace('\\','');
                cacheKey= cacheKey.toUpperCase();
                cacheKeySet.add(cacheKey);
            }
        }        
    }
}