example/secondfile/objects/Account_End_Customer_Junction__c.object
<CustomObject>
    <description>A many-to-many object which holds the information from Account and End customer i.e. One SP Account can have many end customers and One end customer can have multiple SP Accounts</description>
    <fields>
        <fullName>Account_Owner__c</fullName>
        <formula>Account__r.OwnerId</formula>
        <label>Account Owner</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>End_Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>End Customer</label>
        <referenceTo>End_Customer__c</referenceTo>
        <relationshipLabel>Related SP Accounts</relationshipLabel>
        <relationshipName>Account_End_Customer_Junction</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Account End Customer - Junction</label>
    <nameField>
        <displayFormat>AEJ-{0000}</displayFormat>
        <label>Account End Customer Junction ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account End Customer - Junction</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

secondfile/objects/Deal_Hash__c.object
<CustomObject>
    <fields>
        <fullName>Customer_Defining_Group_ID__c</fullName>
        <label>Customer Defining Group ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Master Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>RDS-Deal Hash</relationshipLabel>
        <relationshipName>Deal_Hash</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>RDS-Deal Hash</label>
    <nameField>
        <displayFormat>DH-{00000}</displayFormat>
        <label>Deal Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RDS-Deal Hash</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

example/secondfile/objects/End_Customer__c.object
<CustomObject>
    <fields>
        <fullName>CDG__c</fullName>
        <label>CDG</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Named_Account__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Named Account</label>
        <type>Checkbox</type>
    </fields>
    <label>End Customer</label>
    <nameField>
        <label>End Customer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>End Customers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

example/secondfile/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>End_Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>End Customer</label>
        <referenceTo>End_Customer__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

secondfile/classes/SIEndcustomerTriggerHandler.cls
public with sharing class SIEndcustomerTriggerHandler extends SITriggerOperations.SITriggerImpl
{
    EmailTemplate notificationTamplate=[Select Subject,Name,Id,HtmlValue From EmailTemplate  where Name ='Named Endcustomer Creation Alert' limit 1] ;
    public List <Account_End_Customer_Junction__c> acctEndCustList=New List<Account_End_Customer_Junction__c>();
    Public List <User> usr= New List<User>(); 
    public set <Id> accoutOwners= New set <Id>();
    public String ownerNames='';
    public set <id> endCustnSet = New set <id>();
    public Map <Id,String> userMap= New Map <Id,String>();
    public Map<id,String> ownerMap= New Map<Id,String>();
    public List <End_Customer__c> ecListOld= New List<End_Customer__c>();
    public List <End_Customer__c> ecListNew= New List<End_Customer__c>();  
       
    public override boolean onAfterUpdate(SObject[] oldObjects, SObject[] updatedObjects, Map<Id, SObject>  newObjectsMap) 
    {
      validateUpdation(oldObjects,updatedObjects);
      UpdateCustomerDefiningGroup(updatedObjects);      
      return True;
    }
    
    public void validateUpdation(SObject[] oldObjects, SObject[] updatedObjects)
    {
        ecListOld=oldObjects;
        ecListNew=updatedObjects;
        for(integer i=0;i<ecListOld.size();i++)
        {
            if(ecListOld[i].Named_Account__c!=ecListNew[i].Named_Account__c)
            {
                endCustnSet.add(ecListOld[i].id);
            }
        }
        if( endCustnSet.size() > 0 ) {
            acctEndCustList=[SELECT Id,Account_Owner__c,End_Customer__c from Account_End_Customer_Junction__c Where End_Customer__c IN : endCustnSet];
            for(Account_End_Customer_Junction__c ae : acctEndCustList)
            {
                accoutOwners.add(ae.Account_Owner__c);
                if(!ownerMap.isEmpty())
                {
                    if(ownerMap.containsKey(ae.End_Customer__c))
                    {
                        ownerNames= ownerMap.get(ae.End_Customer__c);
                        ownerNames=ownerNames+','+ae.Account_Owner__c;
                        ownerMap.put(ae.End_Customer__c,ownerNames);
                    }
                    else
                    {
                        ownerMap.put(ae.End_Customer__c,ae.Account_Owner__c);
                    }
                }
                else
                {
                    ownerMap.put(ae.End_Customer__c,ae.Account_Owner__c);
                }           
            }
            if( accoutOwners.size() > 0 ) {
                usr = [Select Id,Email from User Where Id IN :accoutOwners];
                for(User us: usr)
                {
                    userMap.put(us.Id,us.email);
                }
            }
        }
            
        for(integer i=0;i<ecListOld.size();i++)
        {
          if(ecListOld[i].Named_Account__c!=ecListNew[i].Named_Account__c)
          {
            if(ecListNew[i].Named_Account__c==True)
            {   
                sendNotification(ecListNew[i],'Updated','to mark it as named end customer.');
            }
            else
            {
                sendNotification(ecListNew[i],'Updated','to make it as normal endcustomer.');
            }  
          }
      } 
    }
    public void sendNotification(End_customer__c endCust,String mailfor, String val)
    {
        
        String htmlEmailbody;
        List <String> emailAddress = New List<String>();
        List<String> ownerIds= New List <String>();
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();   
        String ownerNames = ownerMap.get(endCust.Id);
        if(ownerNames!=Null)
        {
        ownerIds = ownerNames.split(',',0);
        for(integer i=0; i< ownerIds.size();i++)
        {
            emailAddress.add(userMap.get(ownerIds[i]));
        }
        String fullFileURL = URL.getSalesforceBaseUrl().toExternalForm() +'/' +endCust.Id;        
        mail.setToAddresses(emailAddress);
        mail.setSubject(notificationTamplate.Subject);
        htmlEmailbody = notificationTamplate.HtmlValue;
        htmlEmailbody = htmlEmailbody.replace('<![CDATA[', '');
        htmlEmailbody = htmlEmailbody.replace('{!End_Customer__c.Name}' , endCust.Name);
        htmlEmailbody = htmlEmailbody.replace('{!End_Customer__c.Link}' , fullFileURL);
        htmlEmailbody = htmlEmailbody.replace('{Action}',mailfor);
        htmlEmailbody = htmlEmailbody.replace('{text}',val);
        htmlEmailbody = htmlEmailbody.replace(']]>', '');
        mail.setHtmlBody(htmlEmailbody);
        Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail }); 
        emailAddress.clear(); 
        ownerIds.clear();
        ownerNames=''; 
        }     
    } 
    
/*
     Update RDS-Deal Hash Fields with Values from Related Endcustomer's Junction Field Values
     Deal Hash :Customer Defining Group ID     
               
*/
   
    public void UpdateCustomerDefiningGroup(SObject[] updatedObjects)
    {
        List<End_Customer__c> ecUpdatedObject = updatedObjects;
        Set <ID> endCustomerIdSet = New set<Id>();
        Map<Id, Opportunity> OppEndCustMap = new Map<Id, Opportunity>();
        List<Deal_Hash__c> dhToUpdateObject = new List<Deal_Hash__c>();
                 
            for(End_Customer__c ec :ecUpdatedObject){
                if(ec.CDG__c != null){
                endCustomerIdSet.add(ec.Id);
                }
            }
        if( endCustomerIdSet.size() > 0 ) {    
        List<Opportunity> oppObject = [Select Id, End_Customer__c, End_Customer__r.CDG__c from Opportunity where End_Customer__c IN:endCustomerIdSet];
            for(Opportunity opp : oppObject){
                OppEndCustMap.put(opp.Id, opp);
            }
        if( OppEndCustMap.size() > 0 ) {
            List<Deal_Hash__c> dhObject = [Select Id, Name, Opportunity__c, Customer_Defining_Group_ID__c from Deal_Hash__c where Opportunity__c IN:OppEndCustMap.keySet()];
                for(Deal_Hash__c dhObj: dhObject){
                    if(dhObj.Customer_Defining_Group_ID__c == NULL){
                    dhObj.Customer_Defining_Group_ID__c = OppEndCustMap.get(dhObj.Opportunity__c).End_Customer__r.CDG__c;
                    dhToUpdateObject.add(dhObj);
                    }
                }
                try{
                update dhToUpdateObject;
                } catch(Exception ex){
                ex.getMessage();
                }
            }
        }
    }  
}