example/secondfile/objects/Account_End_Customer_Junction__c.object
<CustomObject>
    <description>A many-to-many object which holds the information from Account and End customer i.e. One SP Account can have many end customers and One end customer can have multiple SP Accounts</description>
    <fields>
        <fullName>Account_Owner__c</fullName>
        <formula>Account__r.OwnerId</formula>
        <label>Account Owner</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Related End Customers</relationshipLabel>
        <relationshipName>Account_End_Customer_Junction</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>End_Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>End Customer</label>
        <referenceTo>End_Customer__c</referenceTo>
        <relationshipLabel>Related SP Accounts</relationshipLabel>
        <relationshipName>Account_End_Customer_Junction</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Account End Customer - Junction</label>
    <nameField>
        <displayFormat>AEJ-{0000}</displayFormat>
        <label>Account End Customer Junction ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account End Customer - Junction</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

example/secondfile/objects/End_Customer__c.object
<CustomObject>
    <fields>
        <fullName>Named_Account__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Named Account</label>
        <type>Checkbox</type>
    </fields>
    <label>End Customer</label>
    <nameField>
        <label>End Customer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>End Customers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

example/secondfile/classes/SIAcctEndCustJunctionTriggerHandler.cls
public with sharing class SIAcctEndCustJunctionTriggerHandler extends SITriggerOperations.SITriggerImpl
{
    public List <End_Customer__c> endCust= Null;
    map <Id,End_Customer__c> flagMap = New map<Id,End_Customer__c>();
    public List <User> usr= New List<User>();
    map<Id,String> mailMap= New map<Id,String>();
    public List <Account_End_Customer_Junction__c> aeList= New List<Account_End_Customer_Junction__c>();
    public EmailTemplate notificationTamplate=[Select Subject,Name,Id,HtmlValue From EmailTemplate  where Name ='Named Endcustomer Creation Alert' limit 1] ;
    public override boolean onAfterInsert(SObject[] newObjects) {
      validateCreation(newObjects);
        
       //Code for User Story US699119 
      createSharingrule(newObjects);  
      return True;
    }
    public void validateCreation(SObject[] newObjects)
    {
        aeList=newObjects;
        set<id> idSet=New set<id>();
        set<id> acctOwnerSet= New set <id>(); 
        for(Account_End_Customer_Junction__c ae:aeList)
        {
            idSet.add(ae.End_Customer__c);
            acctOwnerSet.add(ae.Account_Owner__c);
        }   
        endCust=[Select Id,Name,Named_Account__c from End_Customer__c Where Id IN : idSet];
        usr = [Select Id,Email from User Where Id IN :acctOwnerSet];
        
        for(End_Customer__c ec: endCust)
        {
            flagMap.Put(ec.Id,ec);
        }
        for(User us:usr)
        {
            mailMap.put(us.Id,us.Email);
        }
        
        
        for(Account_End_Customer_Junction__c ae:aeList)
        {
                if ((flagMap.get(ae.End_Customer__c)).Named_Account__c)
                {
                    sendNotification(ae,'Created','as Named End Customer');
                }
        }
    }
    
    public void sendNotification(Account_End_Customer_Junction__c aecJunc,String mailfor, String val )
    {
        String htmlEmailbody;
       
        //List <Account_End_Customer_Junction__c> acjList= New List<Account_End_Customer_Junction__c>();
        //endCust=[Select Id,Name from End_Customer__c Where End_Customer__c.Id=:aecJunc.End_Customer__c];
        List <Id> uList= New List <Id>();
        List <String> emailAddress = New List<String>();
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage(); 
        emailAddress.add(mailMap.get(aecJunc.Account_Owner__c));        
        String fullFileURL = URL.getSalesforceBaseUrl().toExternalForm() +'/' +aecJunc.End_Customer__c;              
        mail.setToAddresses(emailAddress);
        mail.setSubject(notificationTamplate.Subject);
        htmlEmailbody = notificationTamplate.HtmlValue;
        htmlEmailbody = htmlEmailbody.replace('<![CDATA[', '');
        htmlEmailbody = htmlEmailbody.replace('{!End_Customer__c.Name}' , (flagMap.get(aecJunc.End_Customer__c)).Name);
        htmlEmailbody = htmlEmailbody.replace('{!End_Customer__c.Link}' , fullFileURL);
        htmlEmailbody = htmlEmailbody.replace('{Action}',mailfor);
        htmlEmailbody = htmlEmailbody.replace('{text}',val);
        htmlEmailbody = htmlEmailbody.replace(']]>', '');
        mail.setHtmlBody(htmlEmailbody);
        Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
        emailAddress.clear();        
    }
    
     /* Method to provide Sharing rules */    
    public static void createSharingrule(SObject[] newObjects){  
        
        List<Account_End_Customer_Junction__c> attEndCustomerList =  newObjects;
        Map<Id,Id> endCustomerAccountIDsMap = new Map<Id,Id>();
        for(Account_End_Customer_Junction__c sp: attEndCustomerList){
            if(!String.isEmpty(sp.Account__c))
                endCustomerAccountIDsMap.put(sp.End_Customer__c,sp.Account__c);
        }
        if(!Test.isRunningTest()){
        if(endCustomerAccountIDsMap.size()>0){
            SIHelper.createSPSharingPartnerRule(SIConstants.END_CUSTOMER_SHARE,endCustomerAccountIDsMap);
        }
        }
        
    }
}