example/secondfile/objects/Account_End_Customer_Junction__c.object
<CustomObject>
    <description>A many-to-many object which holds the information from Account and End customer i.e. One SP Account can have many end customers and One end customer can have multiple SP Accounts</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Related End Customers</relationshipLabel>
        <relationshipName>Account_End_Customer_Junction</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>End_Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>End Customer</label>
        <referenceTo>End_Customer__c</referenceTo>
        <relationshipLabel>Related SP Accounts</relationshipLabel>
        <relationshipName>Account_End_Customer_Junction</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Account End Customer - Junction</label>
    <nameField>
        <displayFormat>AEJ-{0000}</displayFormat>
        <label>Account End Customer Junction ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account End Customer - Junction</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

example/secondfile/objects/ATT_LocationMapping__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>AT&amp;T LocationMapping</label>
</CustomObject>

example/secondfile/objects/ATT_StateMapping__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>AT&amp;T State Mapping custom setting maps state name to state code</description>
    <fields>
        <fullName>State_Code__c</fullName>
        <label>State Code</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <label>AT&amp;T State Mapping</label>
</CustomObject>

secondfile/objects/CustomerSite__c.object
<CustomObject>
    <description>Custom object to store customer site information</description>
    <fields>
        <fullName>Account_End_Customer_Junction__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account End Customer - Junction</label>
        <referenceTo>Account_End_Customer_Junction__c</referenceTo>
        <relationshipLabel>AT&amp;T Customer Sites</relationshipLabel>
        <relationshipName>AT_T_Customer_Sites</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Address_Line__c</fullName>
        <label>Street</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>End_Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>End customer is required</inlineHelpText>
        <label>End Customer</label>
        <referenceTo>End_Customer__c</referenceTo>
        <relationshipLabel>AT&amp;T Customer Sites</relationshipLabel>
        <relationshipName>AT_T_Customer_Sites</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <label>Location</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Room</fullName>
                </value>
                <value>
                    <fullName>Suite</fullName>
                </value>
                <value>
                    <fullName>Floor</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>RoomBuildingFloorInput__c</fullName>
        <label>RoomBuildingFloorInput</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Site_Name__c</fullName>
        <label>Site Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AL</fullName>
                </value>
                <value>
                    <fullName>AK</fullName>
                </value>
                <value>
                    <fullName>AZ</fullName>
                </value>
                <value>
                    <fullName>AR</fullName>
                </value>
                <value>
                    <fullName>CA</fullName>
                </value>
                <value>
                    <fullName>CO</fullName>
                </value>
                <value>
                    <fullName>CT</fullName>
                </value>
                <value>
                    <fullName>DE</fullName>
                </value>
                <value>
                    <fullName>FL</fullName>
                </value>
                <value>
                    <fullName>GA</fullName>
                </value>
                <value>
                    <fullName>HI</fullName>
                </value>
                <value>
                    <fullName>ID</fullName>
                </value>
                <value>
                    <fullName>IL</fullName>
                </value>
                <value>
                    <fullName>IN</fullName>
                </value>
                <value>
                    <fullName>IA</fullName>
                </value>
                <value>
                    <fullName>KS</fullName>
                </value>
                <value>
                    <fullName>KY</fullName>
                </value>
                <value>
                    <fullName>LA</fullName>
                </value>
                <value>
                    <fullName>ME</fullName>
                </value>
                <value>
                    <fullName>MD</fullName>
                </value>
                <value>
                    <fullName>MA</fullName>
                </value>
                <value>
                    <fullName>MI</fullName>
                </value>
                <value>
                    <fullName>MN</fullName>
                </value>
                <value>
                    <fullName>MS</fullName>
                </value>
                <value>
                    <fullName>MO</fullName>
                </value>
                <value>
                    <fullName>MT</fullName>
                </value>
                <value>
                    <fullName>NE</fullName>
                </value>
                <value>
                    <fullName>NV</fullName>
                </value>
                <value>
                    <fullName>NH</fullName>
                </value>
                <value>
                    <fullName>NJ</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Zip_Code__c</fullName>
        <label>Zip Code</label>
        <length>5</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>AT&amp;T Customer Site</label>
    <nameField>
        <displayFormat>ADD-{000000}</displayFormat>
        <label>Site #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AT&amp;T Customer Sites</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

example/secondfile/objects/End_Customer__c.object
<CustomObject>
    <fields>
        <fullName>Business_Website__c</fullName>
        <label>Business Website</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Company_Legal_Name__c</fullName>
        <label>Company Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DUNS__c</fullName>
        <label>DUNS #</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Floor__c</fullName>
        <label>Location Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mailing_Street_Address__c</fullName>
        <label>Mailing Street Address</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Office_Phone__c</fullName>
        <label>Office Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>State_Province__c</fullName>
        <label>State</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Suite__c</fullName>
        <label>Location</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Apartments</fullName>
                </value>
                <value>
                    <fullName>Basement</fullName>
                </value>
                <value>
                    <fullName>Building</fullName>
                </value>
                <value>
                    <fullName>Floor</fullName>
                </value>
                <value>
                    <fullName>Hangar</fullName>
                </value>
                <value>
                    <fullName>Lot</fullName>
                </value>
                <value>
                    <fullName>Office</fullName>
                </value>
                <value>
                    <fullName>PH</fullName>
                </value>
                <value>
                    <fullName>Pier</fullName>
                </value>
                <value>
                    <fullName>Room</fullName>
                </value>
                <value>
                    <fullName>Slip</fullName>
                </value>
                <value>
                    <fullName>Space</fullName>
                    <label>SPACE</label>
                </value>
                <value>
                    <fullName>STE</fullName>
                </value>
                <value>
                    <fullName>Stop</fullName>
                </value>
                <value>
                    <fullName>Suite</fullName>
                </value>
                <value>
                    <fullName>Trlr</fullName>
                </value>
                <value>
                    <fullName>Unit</fullName>
                </value>
                <value>
                    <fullName>Wing</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Zip__c</fullName>
        <label>Zip (long)</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <label>End Customer</label>
    <nameField>
        <label>End Customer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>End Customers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

secondfile/classes/AddCustomerController.cls
/********************************************************************************************** 
 Apex Class Name     : AddCustomerController
 Version             : 1.0 
 Created Date        : 18 Oct 2014
 Function            : This class handles the search and create customer functionalities
***********************************************************************************************/
public with sharing class AddCustomerController {

    private final End_Customer__c atomcus;
    public id duplicateId ; 
    public boolean checkbox {get;set;}
    public AddCustomerController(ApexPages.StandardController controller) {
        this.atomcus=(End_Customer__c)controller.getrecord();
        checkbox = true;
    }
    
    /*Cancel Action Method*/
    public PageReference cancelAction(){        
        return null;
    }

    /*Save Action Method*/
    public PageReference saveAction(){
        try{
            set<id>endCustIDSet = new set<id>() ;
            Boolean duplicate = false;
            user lstUser = [select id, Contact.AccountId from User where id=:userInfo.getUserId()];
            
            if(lstUser.Contact.AccountId != null){
                 list<Account_End_Customer_Junction__c> endCs = [select End_Customer__c, Account__c from Account_End_Customer_Junction__c where  Account__c != NULL  and Account__c =: lstUser.Contact.AccountId];
                 for(Account_End_Customer_Junction__c setid  :endCs){
                     endCustIDSet.add(setid.End_Customer__c);
                 }
                 
                 list<End_Customer__c> Endcustomer = [Select Id,City__c, Office_Phone__c,Business_Website__c,Suite__c,Floor__c,First_Name__c,Company_Legal_Name__c,
                                                       Last_Name__c,Name,Email__c,DUNS__c,State__c,Mailing_Street_Address__c,State_Province__c,Zip__c from End_Customer__c where id in: endCustIDSet];
                 System.debug('--->'+endCustIDSet);
                 for(End_Customer__c Check : Endcustomer){
                    if(Check.Name == atomcus.Name){
                        System.debug('--->+duplicate alert'+Check+'    '+atomcus);
                        duplicateId  = Check.id;
                        duplicate = true;
                        break;
                    }
                }
                
                if(duplicate == true){
                    ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,'Duplicate Address Found. Please add a customer with new address'));
                    PageReference pg = System.Page.Buyflow;
                    pg.getParameters().put('existCustRec',duplicateId );            
                    pg.setRedirect(true);
                    return pg;
                }
                else{
                    insert atomcus;
                    Account_End_Customer_Junction__c junc = new Account_End_Customer_Junction__c( account__c = lstUser.Contact.AccountId, End_Customer__c = atomcus.id);
                    insert junc;
                   
                    //Inserting new customer site with as that of new end customer and tagging it to the same End customer
                    CustomerSite__c customerSite = new CustomerSite__c();
                    if(atomcus != null){
                        customerSite.Site_Name__c = atomcus.Name;
                        customerSite.End_Customer__c = atomcus.Id;
                        customerSite.Address_Line__c = atomcus.Mailing_Street_Address__c;
                        customerSite.City__c = atomcus.City__c;
                        customerSite.State__c = atomcus.State__c;
                        customerSite.Zip_Code__c = atomcus.Zip__c;
                        customerSite.Location__c = atomcus.Suite__c;
                        if(atomcus.Floor__c != null){
                            customerSite.RoomBuildingFloorInput__c = atomcus.Floor__c;
                        }
                    }
                    if(junc !=null){
                        customerSite.Account_End_Customer_Junction__c = junc.Id;
                    }
                    insert customerSite;

                    PageReference pg = System.Page.Buyflow;
                    pg.getParameters().put('newCustRec',atomcus.Id);            
                    pg.setRedirect(true);
                    return pg;
                }
            }else{
                list<account>  acc = new list<account>();
                insert atomcus;
                acc = [select id from account where name = 'AT&T_SP'];
                if(acc.size() == 0){
                    account a= new account( name = 'AT&T_SP');
                    insert a;
                    acc.add(a);
                }
                Account_End_Customer_Junction__c junc = new Account_End_Customer_Junction__c( account__c = acc[0].id, End_Customer__c = atomcus.id);
                insert junc;
                
                PageReference pg = System.Page.Buyflow;
                pg.getParameters().put('newCustRec',atomcus.Id);            
                pg.setRedirect(true);
                return pg;
             }
        }catch(Exception e){
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,e.getMessage()));
            ATTException.createException('Error in CreateCustomerController.saveAction', e.getTypeName(), ATTException.constructExceptionMessageString(e));
            return null;
        }
    }


    /*Get values from custom setting for State picklist*/  
    public List<SelectOption> getstatePickList(){
        List<SelectOption> statePickList = new List<SelectOption>();
        List<ATT_StateMapping__c> stateList = ATT_StateMapping__c.getall().values();
        if (stateList!=NULL){
            for(ATT_StateMapping__c item : stateList){
                statePickList.add(new selectoption(item.State_Code__c,item.name));
            }
        }
        statePickList.sort();
        SelectOption placeholderText;
        statePickList.add(0,new SelectOption('','Select'));
        system.debug (' :: ' + statePickList);
        return statePickList;
    }

    /*Get values from custom setting for Location picklist*/    
    public List<SelectOption> getLocationPicklist(){
        try{
            List<SelectOption> locationPicklist = new List<SelectOption>();
            List<ATT_LocationMapping__c> LocationList = ATT_LocationMapping__c.getall().values();
            if (LocationList!=NULL){
                for(ATT_LocationMapping__c item : LocationList){
                    locationPicklist.add(new selectoption(item.name,item.name));
                }
            }
            locationPicklist.sort();
            locationPicklist.add(0,new SelectOption('','Select'));
            return locationPicklist;
        }  
        catch(Exception e){
            ATTException.logException( e.getTypeName(), ATTException.constructExceptionMessageString(e));
            return null;
        }
    }    
}