example/secondfile/objects/Admin_Control__c.object
<CustomObject>
    <fields>
        <fullName>MIS_Add_Sites_Suppression__c</fullName>
        <defaultValue>false</defaultValue>
        <label>MIS Add Sites Suppression</label>
        <type>Checkbox</type>
    </fields>
    <label>Admin Control</label>
    <nameField>
        <displayFormat>AC-{0000}</displayFormat>
        <label>Admin Control Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Admin Control</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

secondfile/objects/Deal_Hash__c.object
<CustomObject>
    <fields>
        <fullName>ASE_MACD_Lock__c</fullName>
        <defaultValue>false</defaultValue>
        <label>ASE MACD Lock</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Action__c</fullName>
        <label>Action</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>NEW</fullName>
                    <default>true</default>
                    <label>NEW</label>
                </value>
                <value>
                    <fullName>UPDATE</fullName>
                </value>
                <value>
                    <fullName>UPDATE_PREMISE</fullName>
                </value>
                <value>
                    <fullName>SOFT_DISCONNECT</fullName>
                </value>
                <value>
                    <fullName>ADD_PREMISE</fullName>
                </value>
                <value>
                    <fullName>CHANGE_FEATURE</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ContractEndDate__c</fullName>
        <formula>TEXT(MONTH(Contract_End_Date_Hidden__c))+&quot;/&quot; +TEXT(DAY(Contract_End_Date_Hidden__c))+&quot;/&quot; +TEXT(YEAR(Contract_End_Date_Hidden__c))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>ContractEndDate</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contract_Action_Tooltips__c</fullName>
        <formula>IF(Contract_Renewal_Status__c &lt;&gt; &apos;Expired&apos;,&quot;Only expired contracts are eligible for renewal.&quot;, 
IF(!IsEligibleForContract__c,&quot;One or more sites has Pending status. All the sites must be Active to renew the contract.&quot;, 
IF(Contract_Renewal_Lock__c,&quot;This contract is currently being worked on by another user. Please try later.&quot;,
IF(TEXT(Contract_Renewal_Stage__c) == &apos;Offline Process Initiated&apos; || TEXT(Contract_Renewal_Stage__c) == &apos;Renewal Request Pending&apos;,&quot;A contract renewal request is currently Pending&quot;, 
IF(TEXT(Contract_Renewal_Stage__c) == &apos;Special Pricing Requested&apos;,&quot;A Special Pricing request is currently Pending.&quot;,&apos;&apos;)))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Contract Action Tooltips</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contract_Renewal_Lock__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Contract Renewal Lock</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Contract_Renewal_Stage__c</fullName>
        <label>Contract Renewal Stage</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Offline Process Initiated</fullName>
                </value>
                <value>
                    <fullName>Special Pricing Requested</fullName>
                </value>
                <value>
                    <fullName>Renewal Request Pending</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contract_Renewal_Status__c</fullName>
        <formula>IF( Contract_End_Date_Hidden__c &gt; TODAY(), &quot;Active&quot;,&quot;Expired&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Contract Renewal Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DH_Quote_Id__c</fullName>
        <label>DH Quote Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DH_Quote_Name__c</fullName>
        <label>DH Quote Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Eligible_Deal_Hash__c</fullName>
        <formula>IF(ServiceType__c == &quot;AVPN&quot; || ServiceType__c ==&quot;MIS&quot; || (ServiceType__c == &quot;ASE&quot; &amp;&amp;  Opportunity__r.Account.ASE_Product__c == true &amp;&amp; INCLUDES(Opportunity__r.Account.Product_Trainings_Completed__c, &quot;ASE&quot;)), true, false)</formula>
        <label>Eligible Deal Hash</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>End_Customer_Name__c</fullName>
        <label>End Customer Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IsDealHashCreationSuccess__c</fullName>
        <defaultValue>false</defaultValue>
        <description>will be true whenever the deal hash creation is successfull.</description>
        <label>IsDealHashCreationSuccess</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsEligibleForContract__c</fullName>
        <formula>IF(((Premise_Count_for_Contract_Renewal__c == Current_Version_Count__c) &amp;&amp; PremiseDetailActiveCount__c &gt; 0), true, false)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>IsEligibleForContract</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ManualFlow__c</fullName>
        <defaultValue>false</defaultValue>
        <description>For backend technical field</description>
        <label>ManualFlow</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Number_of_Sites__c</fullName>
        <formula>IF( ServiceType__c == &quot;ASE&quot;, Opportunity__r.Number_of_Products__c, CountOfRdsPremise__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Number of Sites</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Master Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>RDS-Deal Hash</relationshipLabel>
        <relationshipName>Deal_Hash</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ServiceType__c</fullName>
        <formula>IF(CONTAINS(Contract_Number__c, &quot;AVPN&quot;),&quot;AVPN&quot;, IF(CONTAINS(Contract_Number__c, &quot;MIS&quot;),&quot;MIS&quot;, &quot;ASE&quot;))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>ServiceType</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sub_Account_Number__c</fullName>
        <label>Sub Account Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>isBeginQuotePermission__c</fullName>
        <formula>$User.Begin_Quote__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>isBeginQuotePermission</label>
        <type>Checkbox</type>
    </fields>
    <label>RDS-Deal Hash</label>
    <nameField>
        <displayFormat>DH-{00000}</displayFormat>
        <label>Deal Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RDS-Deal Hash</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

example/secondfile/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>ATOM_Deal__c</fullName>
        <defaultValue>false</defaultValue>
        <label>ATOM Deal</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Account_Contract_Renewal__c</fullName>
        <formula>IF(Service_type__c==&apos;AMIS&apos;,Account.MIS_Contract_Renewal__c,
IF(Service_type__c==&apos;AVPN&apos;,Account.AVPN_Contract_Renewal__c,false))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account Contract Renewal</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>End_Customer_Name__c</fullName>
        <formula>LOWER(TRIM(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(End_Customer__r.Name, &quot;?&quot;, &quot;&quot;), &quot;/&quot;, &quot;&quot;), &quot;.&quot;, &quot;&quot;), &quot;,&quot;, &quot;&quot;), &quot;;&quot;, &quot;&quot;), &quot;:&quot;, &quot;&quot;), &quot; &quot;, &quot;&quot;), &quot;{&quot;, &quot;&quot;), &quot;}&quot;, &quot;&quot;), &quot;[&quot;, &quot;&quot;), &quot;]&quot;, &quot;&quot;), &quot;&apos;&quot;, &quot;&quot;), &quot;=&quot;, &quot;&quot;), &quot;-&quot;, &quot;&quot;), &quot;=&quot;, &quot;&quot;), &quot;^&quot;, &quot;&quot;), &quot;&amp;&quot;, &quot;&quot;), &quot;*&quot;, &quot;&quot;), &quot;(&quot;, &quot;&quot;), &quot;)&quot;, &quot;&quot;), &quot;_&quot;, &quot;+&quot;), &quot;#&quot;, &quot;&quot;), &quot;!&quot;, &quot;&quot;), &quot;`&quot;, &quot;&quot;), &quot;@&quot;, &quot;&quot;), &quot;$&quot;, &quot;&quot;), &quot;%&quot;, &quot;&quot;), &quot;1&quot;, &quot;&quot;), &quot;2&quot;, &quot;&quot;), &quot;3&quot;, &quot;&quot;), &quot;4&quot;, &quot;&quot;), &quot;5&quot;, &quot;&quot;), &quot;6&quot;, &quot;&quot;), &quot;7&quot;, &quot;&quot;), &quot;8&quot;, &quot;&quot;), &quot;9&quot;, &quot;&quot;), &quot;0&quot;, &quot;&quot;)))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>End Customer Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Manualflow__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Flag for Tech ops users to convert an API order into Manual mode so that I can take the order through the manual provisioning flow.</description>
        <inlineHelpText>Please note: Selecting flag will route the order into manual flow. You can not perform Deal Hash related actions once selected. If Deal Hash activities are already kick started, Flag selection will not allow further MACD/ API related activities.</inlineHelpText>
        <label>Manual flow</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

example/secondfile/classes/ManageExistingNetworkSerInvContoller.cls
/************************************************************************************** 
Apex Class Name     : ManageExistingNetworkSerInvContoller
Version             : 2.0  
Created Date        : 29th Mar 2017
Function            : ManageExistingNetworkSerInvContoller
*************************************************************************************/
global with sharing class ManageExistingNetworkSerInvContoller{
    public boolean enableAddSitesOption {get;set;}
    
    public ManageExistingNetworkSerInvContoller(){
        manageNetworkServicesOnload();
    }    
    
    /*
    Method Name: manageNetworkServicesOnload
    Method Description: This method is used MIS Add Sites Suppression
    Method Arguments:  
    Method Return Type: void
    Method Version: 1.0
    */ 
    public void manageNetworkServicesOnload(){
        enableAddSitesOption = [Select Id, MIS_Add_Sites_Suppression__c from Admin_Control__c LIMIT 1].MIS_Add_Sites_Suppression__c;
    }   
    
    
    /*
    Method Name: fetchDealHashAndPremiseRecords
    Method Description: This method is used to query AVPN,MIS and ASE deal hash
    Method Arguments:  
    Method Return Type: List<Deal_Hash__c>
    Method Version: 1.0
    */
    @RemoteAction
    global static List<Deal_Hash__c> fetchDealHashAndPremiseRecords() {
        try{
            User usr = new User();
            usr = [Select Id,ContactId FROM User WHERE id=:userinfo.getuserId()];
            Contact con = new Contact();
            if(usr.ContactId != null) {  
                con = [SELECT Id, AccountId FROM Contact WHERE Id=:usr.ContactId];
            }
            Id accId = con.AccountId;  
            String soql ='select End_Customer_Name__c, Sub_Account_Number__c,ContractEndDate__c, ServiceType__c, Number_of_Sites__c, Action__c, IsDealHashCreationSuccess__c, isBeginQuotePermission__c,ManualFlow__c,DH_Quote_Name__c,DH_Quote_Id__c,ASE_MACD_Lock__c,Contract_Renewal_Status__c, Contract_Renewal_Stage__c,Opportunity__r.Account_Contract_Renewal__c,IsEligibleForContract__c, Contract_Action_Tooltips__c, Contract_Renewal_Lock__c from Deal_Hash__c where Sub_Account_Number__c != null And Opportunity__r.AccountId =: accId And Number_of_Sites__c != 0 AND Eligible_Deal_Hash__c = TRUE AND Opportunity__r.ATOM_Deal__c = TRUE ';
            return Database.query(soql); 
        }
        catch(Exception e){
            ATTException.logException( e.getTypeName(), ATTException.constructExceptionMessageString(e));
            return null;
        }  
    }   
}