example/secondfile/objects/Admin_Control__c.object
<CustomObject>
    <fields>
        <fullName>FlowITPAResponse__c</fullName>
        <label>Flow ITPA Response</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Flow_IGLOO_Response__c</fullName>
        <label>Flow IGLOO Response</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <label>Admin Control</label>
    <nameField>
        <displayFormat>AC-{0000}</displayFormat>
        <label>Admin Control Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Admin Control</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

example/secondfile/classes/WebserviceResponseStub.cls
/************************************************************************************** 
Apex Class Name     : WebserviceResponseStub
Version             : 1.0 
Created Date        : 17 Jan 2017
Function            : Response Stub for REST Webservice Calls
***************************************************************************************/
public class WebserviceResponseStub{

    public static String getFlowIglooResponse(){ 
        Admin_Control__c admin= [select Flow_IGLOO_Response__c from Admin_Control__c limit 1]; 
        return admin.Flow_IGLOO_Response__c;
    }
        
    public static String getFlowITPAResponse(){           
        Admin_Control__c admin= [select FlowITPAResponse__c from Admin_Control__c limit 1]; 
        return admin.FlowITPAResponse__c ;        
    }
}