example/secondfile/objects/Apttus_Proposal__Proposal__c.object
<CustomObject>
</CustomObject>

example/secondfile/objects/AT_T_Customer_Site_Quote__c.object
<CustomObject>
    <description>Junction object setup between Site and Quote objects.</description>
    <fields>
        <fullName>AT_T_Customer_Site__c</fullName>
        <label>AT&amp;T Customer Site</label>
        <referenceTo>CustomerSite__c</referenceTo>
        <relationshipLabel>AT&amp;T Customer Site Quotes</relationshipLabel>
        <relationshipName>AT_T_Customer_Site_Quotes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>AT_T_Quote__c</fullName>
        <label>AT&amp;T Quote</label>
        <referenceTo>Apttus_Proposal__Proposal__c</referenceTo>
        <relationshipLabel>AT&amp;T Customer Site Quotes</relationshipLabel>
        <relationshipName>AT_T_Customer_Site_Quotes</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>AT&amp;T Customer Site Quote</label>
    <nameField>
        <label>AT&amp;T Customer Site Quote Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AT&amp;T Customer Site Quotes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

secondfile/objects/CustomerSite__c.object
<CustomObject>
    <description>Custom object to store customer site information</description>
    <label>AT&amp;T Customer Site</label>
    <nameField>
        <displayFormat>ADD-{000000}</displayFormat>
        <label>Site #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AT&amp;T Customer Sites</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

secondfile/objects/IT_Support_Ticket__c.object
<CustomObject>
    <description>Used to open IT Support Tickets for ATT Maintenance projects.</description>
    <fields>
        <fullName>Impact__c</fullName>
        <label>Impact</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Logged_Date_Time__c</fullName>
        <label>Logged Date/Time</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Related_Customer_Site__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related Customer Site</label>
        <referenceTo>CustomerSite__c</referenceTo>
        <relationshipLabel>IT Support Tickets</relationshipLabel>
        <relationshipName>IT_Support_Tickets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Related_to__c</fullName>
        <label>Related to</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Accounts</fullName>
                </value>
                <value>
                    <fullName>Contacts</fullName>
                </value>
                <value>
                    <fullName>Credit Validations</fullName>
                </value>
                <value>
                    <fullName>Data Access</fullName>
                </value>
                <value>
                    <fullName>Data Mismatch with BID</fullName>
                </value>
                <value>
                    <fullName>Data Mismatch with ROME</fullName>
                </value>
                <value>
                    <fullName>Deal Registration Approval</fullName>
                </value>
                <value>
                    <fullName>Email</fullName>
                </value>
                <value>
                    <fullName>Enhancement</fullName>
                </value>
                <value>
                    <fullName>Force Portal</fullName>
                    <default>true</default>
                    <label>Force Portal</label>
                </value>
                <value>
                    <fullName>General Field Update</fullName>
                </value>
                <value>
                    <fullName>General Process Flow</fullName>
                </value>
                <value>
                    <fullName>Lead Conversion</fullName>
                </value>
                <value>
                    <fullName>On/Off cart deals</fullName>
                </value>
                <value>
                    <fullName>Opportunities</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>SI/VAR-API</fullName>
                </value>
                <value>
                    <fullName>Sign on</fullName>
                </value>
                <value>
                    <fullName>Special Pricing Approval</fullName>
                </value>
                <value>
                    <fullName>SP Products</fullName>
                </value>
                <value>
                    <fullName>User Creation/Deletion</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Severity__c</fullName>
        <label>Severity</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1- Critical</fullName>
                </value>
                <value>
                    <fullName>2 - High</fullName>
                </value>
                <value>
                    <fullName>3 - Medium</fullName>
                    <default>true</default>
                    <label>3 - Medium</label>
                </value>
                <value>
                    <fullName>4 - Low</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>On Hold - Client Input/Verification Needed</fullName>
                </value>
                <value>
                    <fullName>On Hold - Referred to External Application</fullName>
                </value>
                <value>
                    <fullName>On Hold - Targeted for Maintenance Release</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Deferred(CR)</fullName>
                </value>
                <value>
                    <fullName>Not an Issue</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Steps_to_Reproduce_Error__c</fullName>
        <inlineHelpText>Enter step by step instructions for how the error was produced</inlineHelpText>
        <label>Steps to Reproduce Error</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Ticket_Subject__c</fullName>
        <label>Subject</label>
        <length>175</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>IT Support Ticket</label>
    <nameField>
        <displayFormat>ITS-{000000}</displayFormat>
        <label>IT Support Ticket #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>IT Support Tickets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

secondfile/classes/createITSTicketForFailedSites.cls
/*************************************************************************************************** 
 Trigger Name        : createITSTicketForFailedSites
 Version             : 1.0
 Created Date        : 7th Nov 2017
 Created By          : Bhupesh Kumar
 Description         : This class is a generic class to create ITS ticket for the failed sites after 3rd retrigger failure.
 Modified By         : 
 Modified Date       : 
***************************************************************************************************/

public with sharing class createITSTicketForFailedSites {
    
    public static void createITSTickets(set<Id> failedCustomerSiteIds){ 
        
        system.debug('====inside ITS ticket creation class==='+failedCustomerSiteIds);
        
        final string RELATED_TO = 'SI/VAR-API';
        final string TKT_SUBJECT = 'API Failure due to service unavailable';
        final string SEVERITY = '2 - High';
        final string IMPACT = 'API Call Failed Due to Service Unavailable, User is unable to continue in portal for this order and potentially others';
        
        list<IT_Support_Ticket__c> lstItSupportTickets = new list<IT_Support_Ticket__c>();
        
        try{
            if(!failedCustomerSiteIds.isEmpty()) {
                
                //*********** new logic to change the record owner *******************
                Set<Id> parentQuoteIds = new Set<Id>();
            
                map<Id, AT_T_Customer_Site_Quote__c> jnSiteQuoteMap = 
                new map<Id, AT_T_Customer_Site_Quote__c>([SELECT Id, AT_T_Customer_Site__c, AT_T_Quote__c 
                                                          FROM AT_T_Customer_Site_Quote__c 
                                                          WHERE AT_T_Customer_Site__c IN: failedCustomerSiteIds]);
                                                          
                if(!jnSiteQuoteMap.isEmpty()) {
                    for(AT_T_Customer_Site_Quote__c jnSiteQuote : jnSiteQuoteMap.values()){
                        parentQuoteIds.add(jnSiteQuote.AT_T_Quote__c);
                    }
                }  
                
                string quoteOwnerId = '';
                
                if(!parentQuoteIds.isEmpty()){
                    
                    quoteOwnerId = [SELECT Id,ownerId
                                    FROM Apttus_Proposal__Proposal__c
                                    WHERE Id IN : parentQuoteIds limit 1].ownerId;
                                    
                    // The above list will always have only 1 quote.
                
                }
                
                system.debug('===quoteOwnerId==='+quoteOwnerId);
                                                                                         
                //*********** End of New Logic ***************************************                                      
                                     
                list<CustomerSite__c> lstFailedCustomerSite = [SELECT Id,Name,ownerId
                                                               FROM CustomerSite__c
                                                               WHERE Id IN : failedCustomerSiteIds];                                                     
                                                               
                for(CustomerSite__c cSites : lstFailedCustomerSite) {
                    
                    IT_Support_Ticket__c itSupportObj = new IT_Support_Ticket__c();
                    itSupportObj.Related_to__c = RELATED_TO;
                    itSupportObj.Ticket_Subject__c = TKT_SUBJECT;
                    itSupportObj.Severity__c = SEVERITY;
                    itSupportObj.Logged_Date_Time__c = system.now();
                    itSupportObj.Impact__c = IMPACT;
                    itSupportObj.Status__c = Constant.Status_Open;
                    
                    itSupportObj.Steps_to_Reproduce_Error__c = 'Customer Site '+ cSites.Name +' is receiving API failure due to Service being Unavailable for one or more APIs in the system. SP User has tried multiple time to retrigger API in the system.'+'\n'+'Please investigate '+cSites.Name;
                    itSupportObj.Related_Customer_Site__c = cSites.id;
                    itSupportObj.OwnerId = quoteOwnerId;
                    
                    lstItSupportTickets.add(itSupportObj);
                }                                               
            }
            
            if(!lstItSupportTickets.isEmpty()){
                insert lstItSupportTickets;
                
                system.debug('====inside ITS ticket creation class insertion successful==='+lstItSupportTickets);
            }
        }
        catch(exception excep){
            system.debug('===Exception in ITS creation==='+excep.getMessage()+' at line no '+excep.getLineNumber());
        }
    }
    
    @InvocableMethod 
    public static void createITSTicketForQuoteStateFailure( List<Apttus_Proposal__Proposal__c> proposalList){
        System.debug('@@@@@@inside createITSTicketForQuoteStateFailure');
        final string RELATED_TO = 'SI/VAR - API';
        final string SEVERITY = '2 - High';
        final string IMPACT = 'System will not be able to process the request to create quote with or without registration or submit a quote for registration because of this error.';
        
        Set<Id> quoteIDs = new Set<Id>();
        
        if(!proposalList.isEmpty()){
            for(Apttus_Proposal__Proposal__c quote : proposalList){
                quoteIDs.add(quote.Id);
            }
        }
        System.debug('quoteids '+quoteIDs);
        String quoteOwnerId=' ';
        if(!quoteIDs.isEmpty()){
            quoteOwnerId = [SELECT Id,ownerId FROM Apttus_Proposal__Proposal__c WHERE Id IN : quoteIDs limit 1].ownerId;
            
        }
        list<IT_Support_Ticket__c> lstItSupportTickets = new list<IT_Support_Ticket__c>();
        
        for(Apttus_Proposal__Proposal__c quoteObj : proposalList) {
            IT_Support_Ticket__c itSupportObj = new IT_Support_Ticket__c();
            itSupportObj.Related_to__c = RELATED_TO;
            itSupportObj.Ticket_Subject__c = 'Create Quote – QuoteId:'+'  '+quoteObj.Name+' '+'Quote State updated to Failure';
            itSupportObj.Severity__c = SEVERITY;
            itSupportObj.Logged_Date_Time__c = system.now();
            itSupportObj.Impact__c = IMPACT;
            itSupportObj.Status__c = Constant.Status_Open;
            itSupportObj.Steps_to_Reproduce_Error__c = 'Create Quote -> QuoteId:'+'  '+quoteObj.Name+' '+'Quote State updated to Failure after quote is created.';
            itSupportObj.OwnerId = quoteOwnerId;
            lstItSupportTickets.add(itSupportObj);
        }   

        if(!lstItSupportTickets.isEmpty()){
                insert lstItSupportTickets;
                
                system.debug('====it support tickets insertion successful==='+lstItSupportTickets);
            }
        
        
        
        
        
    }
}