example/secondfile/objects/Apttus_Proposal__Proposal__c.object
<CustomObject>
    <fields>
        <fullName>Product_Name__c</fullName>
        <formula>Product__r.Name</formula>
        <label>Product Name</label>
        <type>Text</type>
    </fields>
</CustomObject>

example/secondfile/objects/Apttus_Proposal__Proposal_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>AT_T_Customer_Site__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>AT&amp;T Customer Site</label>
        <referenceTo>CustomerSite__c</referenceTo>
        <relationshipLabel>Proposal Line Items</relationshipLabel>
        <relationshipName>Proposal_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Bill_Display_Name__c</fullName>
        <label>Bill Display Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Option_Group__c</fullName>
        <formula>Apttus_QPConfig__ProductOptionId__r.Apttus_Config2__ProductOptionGroupId__r.Apttus_Config2__OptionGroupId__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Option Group</label>
        <type>Text</type>
    </fields>
</CustomObject>

example/secondfile/objects/AT_T_Customer_Site_Quote__c.object
<CustomObject>
    <description>Junction object setup between Site and Quote objects.</description>
    <fields>
        <fullName>AT_T_Customer_Site__c</fullName>
        <label>AT&amp;T Customer Site</label>
        <referenceTo>CustomerSite__c</referenceTo>
        <relationshipLabel>AT&amp;T Customer Site Quotes</relationshipLabel>
        <relationshipName>AT_T_Customer_Site_Quotes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>AT&amp;T Customer Site Quote</label>
    <nameField>
        <label>AT&amp;T Customer Site Quote Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AT&amp;T Customer Site Quotes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

example/secondfile/objects/Product_Mapping__c.object
<CustomObject>
    <fields>
        <fullName>BEID__c</fullName>
        <label>BEID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Bill_Display_Name__c</fullName>
        <label>Bill Display Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Combination__c</fullName>
        <formula>IF(ISBLANK(Associated_Product_Three_Selected__c), Associated_Price_List__r.Name &amp; &quot; + &quot; &amp; Associated_Product_One_Selected__r.Name &amp; &quot; + &quot; &amp; Associated_Product_Two_Selected__r.Name, Associated_Price_List__r.Name &amp; &quot; + &quot; &amp; Associated_Product_One_Selected__r.Name &amp; &quot; + &quot; &amp; Associated_Product_Two_Selected__r.Name &amp; &quot; + &quot; &amp; Associated_Product_Three_Selected__r.Name)</formula>
        <label>Combination</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Determinant_Set_Id__c</fullName>
        <label>Determinant Set Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PBIID__c</fullName>
        <label>PBIID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Product Mapping</label>
    <nameField>
        <displayFormat>PM-{0000}</displayFormat>
        <label>Product Mapping Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Mappings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

secondfile/objects/Product_Pricing__c.object
<CustomObject>
    <fields>
        <fullName>BEID__c</fullName>
        <label>BEID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Determinant_Set_ID__c</fullName>
        <label>Determinant Set ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PBI_Number__c</fullName>
        <label>PBI Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SP_Product__c</fullName>
        <label>SP Product</label>
        <referenceTo>SPProduct__c</referenceTo>
        <relationshipLabel>Product Pricing</relationshipLabel>
        <relationshipName>Product_Pricing</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>list_price__c</fullName>
        <defaultValue>0.00</defaultValue>
        <label>List Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>product_name__c</fullName>
        <label>Product Name</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>type__c</fullName>
        <label>Type</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Product Pricing</label>
    <nameField>
        <displayFormat>P-{00000}</displayFormat>
        <label>Pricing ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Pricing</pluralLabel>
    <recordTypes>
        <fullName>Access</fullName>
        <active>true</active>
        <description>Access for Products</description>
        <label>Access</label>
    </recordTypes>
    <recordTypes>
        <fullName>Feature</fullName>
        <active>true</active>
        <description>Features for Products</description>
        <label>Feature</label>
    </recordTypes>
    <recordTypes>
        <fullName>Port</fullName>
        <active>true</active>
        <description>Ports for Products</description>
        <label>Port</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

example/secondfile/objects/SPProduct__c.object
<CustomObject>
    <description>Contains the information of the products like AVPN,CaaS and StaaS</description>
    <fields>
        <fullName>CustomerSiteID__c</fullName>
        <description>This is used in RDS mapping. For identifying Spproduct  based on the site.</description>
        <label>CustomerSiteID</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>List_Price__c</fullName>
        <label>List Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Product_Name__c</fullName>
        <label>Product Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>SPProduct</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>SP Product ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SP Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

example/secondfile/classes/AIACOUP.cls
public class AIACOUP {
    
    public static Boolean executeAIAOnce = false; 
  

    public static void createSPProductsForQuotes(Set<Id> qList, List<SPProduct__c> spProductList, List<AT_T_Customer_Site_Quote__c> cJunSiteList, List<Apttus_Proposal__Proposal_Line_Item__c> proposalLineItem, List<Product_Mapping__c> prodMapList){
        List<Apttus_Proposal__Proposal__c> quoteLst = new List<Apttus_Proposal__Proposal__c>();
        Map<String,List<Apttus_Proposal__Proposal_Line_Item__c> > mapProposalLineItem = new Map<String,List<Apttus_Proposal__Proposal_Line_Item__c> >();
        boolean isSuccess = false;
        executeAIAOnce = true;
        try{
            Double listPrice = 0.0;
            
            Map<String,List<Apttus_Proposal__Proposal_Line_Item__c>> quoteLineItemMap = new Map<String,List<Apttus_Proposal__Proposal_Line_Item__c>>();
            
            Boolean isVLAN = false;
            
            // Creating map based on the site .
            // Map for identifer such as VLAN, COS and Port Type.
            
            for(Apttus_Proposal__Proposal_Line_Item__c p : proposalLineItem){
                if(quoteLineItemMap.containskey(p.AT_T_Customer_Site__c)){
                    quoteLineItemMap.get(p.AT_T_Customer_Site__c).add(p);                   
                }else{
                    quoteLineItemMap.put(p.AT_T_Customer_Site__c,new List<Apttus_Proposal__Proposal_Line_Item__c>{p});
                }
            }
            
            List<Apttus_Proposal__Proposal_Line_Item__c> proposalList = new List<Apttus_Proposal__Proposal_Line_Item__c>(); 
            List<Apttus_Proposal__Proposal_Line_Item__c> quoteProposalList = new List<Apttus_Proposal__Proposal_Line_Item__c>(); 
            
            Map<Id, Id> siteSPProduct = new Map<Id, Id>(); // Site--> SP Prodcut ID
            for(SPProduct__c sp1: spProductList){
                siteSPProduct.put(sp1.CustomerSiteID__c, sp1.ID);
            }
            System.debug('siteSPProduct --- ' + siteSPProduct);
            
            Map<String,Product_Mapping__c> mapProductMap = new Map<String,Product_Mapping__c>();
            
            for(Product_Mapping__c prodMap : prodMapList){
                mapProductMap.put(prodMap.Combination__c,prodMap);
            }
            
            for(AT_T_Customer_Site_Quote__c prop : cJunSiteList){
                List<Product_Pricing__c> pPricingList = new List<Product_Pricing__c>();
                if(quoteLineItemMap.containsKey(prop.AT_T_Customer_Site__c)){               
                    listPrice = 0.0;
                    proposalList = quoteLineItemMap.get(prop.AT_T_Customer_Site__c);
                    
                  
                   
                    
                    for(Apttus_Proposal__Proposal_Line_Item__c pLine : proposalList){ 
                        if (pLine.Apttus_QPConfig__OptionId__c != NULL && pLine.Option_Group__c != 'Access Type' && pLine.Option_Group__c != 'Port Type' && pLine.Option_Group__c != 'Interface Type'&& pLine.Option_Group__c != 'Installation Options')
                        {
                            System.debug('pLine ----- ' + pLine);
                            System.debug('siteSPProduct.get(prop.AT_T_Customer_Site__c) ----- ' + siteSPProduct.get(prop.AT_T_Customer_Site__c));
                            
                            Product_Pricing__c  pPricicng = new Product_Pricing__c();
                              pPricicng.Determinant_Set_ID__c = pLine.Apttus_QPConfig__PriceListItemId__r.Determinant_Set_Id__c;
                                pPricicng.BEID__c =  pLine.Apttus_QPConfig__PriceListItemId__r.BEID__c;
                                pPricicng.PBI_Number__c = String.valueOf(pLine.Apttus_QPConfig__PriceListItemId__r.PBIID__c);
                                pPricicng.product_name__c = pLine.Apttus_QPConfig__PriceListItemId__r.Bill_Display_Name__c; 
                                if(pline.Apttus_QPConfig__PriceType__c == ATT_Constant.PRICETYPE){
                                    pPricicng.type__c = ATT_Constant.MRCTYPE;
                                }else if(pline.Apttus_QPConfig__PriceType__c == ATT_Constant.ONETIMEPRICE){
                                    pPricicng.type__c = ATT_Constant.NRCTYPE;
                                }
                                pPricicng.list_price__c = pLine.Apttus_QPConfig__NetPrice__c;
                                pPricicng.SP_Product__c = siteSPProduct.get(prop.AT_T_Customer_Site__c);            
                                pPricicng.RecordTypeId = Schema.SObjectType.Product_Pricing__c.getRecordTypeInfosByName().get('Feature').getRecordTypeId();
                                pPricingList.add(pPricicng);
                                System.debug('------- ELSE ---- ');
                                
                            
                            
                        }
                    }
                }
                System.debug('pPricingList ---- ' + pPricingList);
                insert pPricingList;
            }
            
        }catch(Exception e){
            system.debug('  Line number - > '+e.getLineNumber()+ '  Message - >'+ e.getMessage());
            ATTException.createException('Error in ApttusServiceUtilityHelper.createSPProductsForQuotes', e.getTypeName(), ATTException.constructExceptionMessageString(e));             
        }
    }
}