example/secondfile/objects/Apttus_Config2__LineItem__c.object
<CustomObject>
    <fields>
        <fullName>AT_T_Customer_Site__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used to Link Customer Site ; VASA Region and Line Item based on VASA Response</description>
        <label>AT&amp;T Customer Site</label>
        <referenceTo>CustomerSite__c</referenceTo>
        <relationshipLabel>Line Items</relationshipLabel>
        <relationshipName>Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>isPricingApplied__c</fullName>
        <defaultValue>false</defaultValue>
        <label>isPricingApplied</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

example/secondfile/objects/AT_T_Customer_Site_Quote__c.object
<CustomObject>
    <description>Junction object setup between Site and Quote objects.</description>
    <fields>
        <fullName>AT_T_Customer_Site__c</fullName>
        <label>AT&amp;T Customer Site</label>
        <referenceTo>CustomerSite__c</referenceTo>
        <relationshipLabel>AT&amp;T Customer Site Quotes</relationshipLabel>
        <relationshipName>AT_T_Customer_Site_Quotes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>AT_T_Quote__c</fullName>
        <label>AT&amp;T Quote</label>
        <referenceTo>Apttus_Proposal__Proposal__c</referenceTo>
        <relationshipLabel>AT&amp;T Customer Site Quotes</relationshipLabel>
        <relationshipName>AT_T_Customer_Site_Quotes</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Wireline_Promotion_Id_After__c</fullName>
        <label>Wireline Promotion Id After</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Wireline_Promotion_Id_Applied__c</fullName>
        <label>Wireline Promotion Id Applied</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Wireline_Promotion_Id_Sorted__c</fullName>
        <label>Wireline Promotion Id Sorted</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>isPricingApplied__c</fullName>
        <defaultValue>false</defaultValue>
        <label>isPricingApplied</label>
        <type>Checkbox</type>
    </fields>
    <label>AT&amp;T Customer Site Quote</label>
    <nameField>
        <label>AT&amp;T Customer Site Quote Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AT&amp;T Customer Site Quotes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

example/secondfile/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Discount_Percentage__c</fullName>
        <label>Discount Percentage</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
</CustomObject>

secondfile/objects/Wireline_Promotion_Rules__c.object
<CustomObject>
    <description>Master Promotions object to store all the promotions created so that Promotion Engine can consume them part of execution.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Promos are only active when tested and certified. Certified Promos will be made Active/Deactive by the system on Start/End Date(s).</description>
        <inlineHelpText>Promos are only active when tested and certified. Certified Promos will be made Active/Deactive by the system on Start/End Date(s).</inlineHelpText>
        <label>Promotion Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Configured_Fields_After__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Configured Fields After</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Configured_Fields_Before__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Configured Fields Before</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Configured_Fields_Number__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Configured Fields Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Discount_Percentage__c</fullName>
        <inlineHelpText>Mandatory: Discount Percentage applicable for promotion. Enter up to 2 decimal places.</inlineHelpText>
        <label>Discount Percentage</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Display_Promotion_End_Date__c</fullName>
        <defaultValue>true</defaultValue>
        <description>When checked, promotion end date is displayed to SP users.</description>
        <inlineHelpText>When checked, promotion end date is displayed to SP users.</inlineHelpText>
        <label>Display Promotion End Date</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Do_Not_Run__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This deactivates promotion regardless of other promotion parameters.</description>
        <inlineHelpText>This deactivates promotion regardless of other promotion parameters.</inlineHelpText>
        <label>Stop Promotion Now</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <description>Mandatory: Last day on which promotion will be active in portal and APIs.</description>
        <inlineHelpText>Mandatory: Last day on which promotion will be active in portal and APIs.</inlineHelpText>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Expiry_Notification__c</fullName>
        <defaultValue>true</defaultValue>
        <description>When checked, SP users will receive notification of the promotion’s pending expiration in their portal dashboards.</description>
        <inlineHelpText>When checked, SP users will receive notification of the promotion’s pending expiration in their portal dashboards.</inlineHelpText>
        <label>Dashboard Notifications</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Field_Inputs__c</fullName>
        <inlineHelpText>This will hold the key value pairs for each dynamic field configured for this promotion</inlineHelpText>
        <label>Field Inputs</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Field_input_values_JSON__c</fullName>
        <label>Field input values JSON</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>For_Testing__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Promos will be applied to test accounts only. NOTE: All promotions must be tested and certified before activation.</description>
        <inlineHelpText>Promos will be applied to test accounts only. NOTE: All promotions must be tested and certified before activation.</inlineHelpText>
        <label>Test Accounts Only</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Hierarchy__c</fullName>
        <description>Read-Only: Populated with Map/Site/Deal based on Promo Type selected</description>
        <inlineHelpText>Read-Only: Populated with Map/Site/Deal based on Promo Type selected</inlineHelpText>
        <label>Hierarchy</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Priority_Number__c</fullName>
        <defaultValue>1</defaultValue>
        <description>Read-Only: Populated with 1/2/3/4/5/6/7/8/9 based on Promo Type selected</description>
        <inlineHelpText>Read-Only: Populated with 1/2/3/4/5/6/7/8/9 based on Promo Type selected</inlineHelpText>
        <label>Priority Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Priority__c</fullName>
        <description>Read-Only: Populated with M1/M2/S1/S2/S3/S4/D1/D2/D3 based on Promo Type selected</description>
        <inlineHelpText>Read-Only: Populated with M1/M2/S1/S2/S3/S4/D1/D2/D3 based on Promo Type selected</inlineHelpText>
        <label>Priority</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Promo_Configurator_Lookup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Dummy lookup relationship with Promo Meta Data Object</inlineHelpText>
        <label>Promo Configurator Lookup</label>
        <referenceTo>Wireline_Promo_Meta_Data__c</referenceTo>
        <relationshipLabel>Wireline Promotion Rules</relationshipLabel>
        <relationshipName>Wireline_Promotion_Rules</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Promo_Configured_Fields__c</fullName>
        <inlineHelpText>Comma separated API Names of the dynamic fields configured for the promotion</inlineHelpText>
        <label>Promo Configured Fields</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Promo_Type__c</fullName>
        <inlineHelpText>Type of Promotion</inlineHelpText>
        <label>Promotion Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Rate Card Map</fullName>
                </value>
                <value>
                    <fullName>SP Tier-Term</fullName>
                </value>
                <value>
                    <fullName>Port</fullName>
                </value>
                <value>
                    <fullName>Access</fullName>
                </value>
                <value>
                    <fullName>Feature</fullName>
                </value>
                <value>
                    <fullName>One-Time Charge</fullName>
                </value>
                <value>
                    <fullName>SP</fullName>
                </value>
                <value>
                    <fullName>Order</fullName>
                </value>
                <value>
                    <fullName>Deal Reg</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Promotion_Certified_By__c</fullName>
        <description>Name of user who approved the promotion</description>
        <inlineHelpText>Name of user who approved the promotion</inlineHelpText>
        <label>Promotion Certified By</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Promotion_Certified__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Once tested, a promotion must be certified by checking this box. NOTE: This is required for promotion to become active.</description>
        <inlineHelpText>Once tested, a promotion must be certified by checking this box. NOTE: This is required for promotion to become active.</inlineHelpText>
        <label>Promotion Certified</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Promotion_Name__c</fullName>
        <inlineHelpText>Mandatory: 20 Characters limit. Visible to all SP users in portal and APIs.</inlineHelpText>
        <label>Promotion Name</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Promotion_Notification__c</fullName>
        <defaultValue>false</defaultValue>
        <description>When checked, promotion name and discount percentage is displayed to SP users.</description>
        <inlineHelpText>When checked, promotion name and discount percentage is displayed to SP users.</inlineHelpText>
        <label>Display Promotion</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Rank__c</fullName>
        <inlineHelpText>Mandatory: Order in which Promotions are applied within the selected Promo Type. Ranks of existing Promos will automatically adjust.</inlineHelpText>
        <label>Rank</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Rule_Description__c</fullName>
        <inlineHelpText>Mandatory: 1000 Characters limit. Visible to internal users only.</inlineHelpText>
        <label>Promotion Description</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Select_Fields_Json__c</fullName>
        <label>Select Fields for Json</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Selected_Fields__c</fullName>
        <label>Selected Fields</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Stackable__c</fullName>
        <defaultValue>false</defaultValue>
        <description>When checked, the promotion can be applied in combination with other promotions within the promo type.</description>
        <inlineHelpText>When checked, the promotion can be applied in combination with other promotions within the promo type.</inlineHelpText>
        <label>Stackable</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <description>Mandatory: Date on which promotion will become active in portal and APIs.</description>
        <inlineHelpText>Mandatory: Date on which promotion will become active in portal and APIs.</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Test_SP__c</fullName>
        <inlineHelpText>Test SPs to which the promotion will be applied if For Testing flag is set to true</inlineHelpText>
        <label>Test SP</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <label>Wireline Promotion Rules</label>
    <nameField>
        <displayFormat>Promo-{0000}</displayFormat>
        <label>Promotion ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Wireline Promotion Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

example/secondfile/classes/ApplyPromotionsForEligibleSites.cls
/*************************************************************************************************** 
 Apex Class Name     : ApplyPromotionsForEligibleSites
 Version             : 1.0
 Created Date        : 25 October 2017
 Description         : Applying promotion for all the Eligible Sites
 Modified By         : 
 Modified Date       : 
***************************************************************************************************/

global class ApplyPromotionsForEligibleSites implements Database.Batchable<sObject> {
    
    global final list<Integer> lineNumbers;
    global final set<Id> IglooAvId ; 
    global final String cartId;
    global final Integer iglooAvSize; 
    global final list<Apttus_Config2__LineItem__c>  lineItems = new list<Apttus_Config2__LineItem__c>();
    global final String quoteId;
    global final string siteQuoteJunctionId; 
     
    global ApplyPromotionsForEligibleSites(list<Integer> lineNumbers, String cartId , set<id> IglooAvId ,list<Apttus_Config2__LineItem__c>  lineItems ,string quoteId){
        this.iglooAvSize = IglooAvId.size();
        this.lineNumbers = lineNumbers;
        this.cartId = cartId;
        this.IglooAvId = IglooAvId;
        this.lineItems.addAll(lineItems);
        this.quoteId = quoteId;
    }
    
    global ApplyPromotionsForEligibleSites(list<Integer> lineNumbers, String cartId , set<id> IglooAvId ,list<Apttus_Config2__LineItem__c>  lineItems ,string quoteId ,string siteQuoteJunctionId){
        this.iglooAvSize = IglooAvId.size();
        this.lineNumbers = lineNumbers;
        this.cartId = cartId;
        this.IglooAvId = IglooAvId;
        this.lineItems.addAll(lineItems);
        this.quoteId = quoteId;
        this.siteQuoteJunctionId = siteQuoteJunctionId;
    }
   
    /* 
    *Name: start
    *Description: This is the start method of the Batch Class, which is used to retrieve the records based on the query.
                  The list of retrieved records will be passed to the execute method for the further processing.
    */
    global Database.QueryLocator start(Database.BatchableContext BC){
        try{
            String Query = 'Select id,AT_T_Quote__c,Wireline_Promotion_Id_After__c, AT_T_Customer_Site__c,Wireline_Promotion_Id_Sorted__c FROM AT_T_Customer_Site_Quote__c WHERE AT_T_Quote__c=:quoteId AND AT_T_Customer_Site__c IN (Select AT_T_Customer_Site__c FROM Apttus_Config2__LineItem__c  WHERE  Apttus_Config2__LineNumber__c IN: lineNumbers '+' and Apttus_Config2__ConfigurationId__c='+'\''+cartId+'\')';
            return Database.getQueryLocator(query);
        }
        catch( Exception ex ){    
            system.debug('@@Exception caught in ApplyPromotionsForEligibleSites : '+ex.getMessage()+' :Line number: '+ex.getlineNumber());  
            return null;
        } 
    }

    /* 
    *Name: execute
    *Description: This is the execute method of the Batch Class, which is used to process the records passed from the Start method.
    */  
    global void execute(Database.BatchableContext BC,List<AT_T_Customer_Site_Quote__c> customerJuncList){    
        System.debug('execute');  
        system.debug('@@@Customer Junc List: ' + customerJuncList);
        map<ID,ID> siteAVIDMap = new map<ID,ID>();
        list<Id> siteIdList = new list<Id>();
        List<Id> avIdLst = new list<Id>();
        for(Apttus_Config2__LineItem__c lineItem : lineItems){
            siteAVIDMap.put(lineItem.AT_T_Customer_Site__c , lineItem.Apttus_Config2__AttributeValueId__c);
        }
        for(AT_T_Customer_Site_Quote__c junc : customerJuncList){        
            ID avId = siteAVIDMap.get(junc.AT_T_Customer_Site__c);
            siteIdlist.add(junc.AT_T_Customer_Site__c);
            avIdLst.add(avId); 
        }
        
        PromotionQualifierUtil qualifier = new PromotionQualifierUtil();
        if(!Test.isRunningTest()){ 
            for(Id siteId:siteIdlist){
                qualifier.determinePromotionAtSiteLevel(siteId,quoteId);
            }
            qualifier.appliedPromotionsCalcuationList(quoteId, siteIdlist, avIDLst);
        }
        
        for(AT_T_Customer_Site_Quote__c junc : customerJuncList){
            list<Wireline_Promotion_Rules__c> wirelinePromoRuleList = new list<Wireline_Promotion_Rules__c>();
            WirelinePromoCalculationHelper wirelinePromoHelper = new WirelinePromoCalculationHelper();            
            Map<String,List<Wireline_Promotion_Rules__c>> junctionPromoRulesListMap = new Map<String,List<Wireline_Promotion_Rules__c>>();
            set<Id> promoIdSet = new set<Id>();
            List<String> promoIdTypeSet = new List<String>();
            AT_T_Customer_Site_Quote__c attQuoteSite = [select id, Wireline_Promotion_Id_Applied__c,  AT_T_Customer_Site__c ,Wireline_Promotion_Id_Sorted__c from  AT_T_Customer_Site_Quote__c  where id =:junc.id ];
            
            system.debug('@@@Wireline Promotion Id Applied for : '+attQuoteSite.Id + ':' +attQuoteSite.Wireline_Promotion_Id_Applied__c);
            if(promoIdTypeSet != null){
                if(attQuoteSite.Wireline_Promotion_Id_Applied__c != null){
                    promoIdTypeSet = attQuoteSite.Wireline_Promotion_Id_Applied__c.split(',');
                }
                for(String promo : promoIdTypeSet){
                     promoIdSet.add(ID.valueOf((promo.split('_')[0]).deleteWhiteSpace()));
                }
                wirelinePromoRuleList = [SELECT Id,Name,Active__c,Configured_Fields_After__c,Configured_Fields_Before__c,Configured_Fields_Number__c,Discount_Percentage__c,Display_Promotion_End_Date__c,Do_Not_Run__c,End_Date__c,Expiry_Notification__c,Field_Inputs__c,Field_input_values_JSON__c,For_Testing__c,Hierarchy__c,Priority_Number__c,Priority__c,Promotion_Certified_By__c,Promotion_Certified__c,Promotion_Name__c,Promotion_Notification__c,Promo_Configurator_Lookup__c,Promo_Configured_Fields__c,Promo_Type__c,Rank__c,Rule_Description__c,Selected_Fields__c,Select_Fields_Json__c,Stackable__c,Start_Date__c,Test_SP__c FROM Wireline_Promotion_Rules__c where id in: promoIdSet];                    
                system.debug('@@@WirelinePromoRuleList: ' + wirelinePromoRuleList);
                if(wirelinePromoRuleList !=null){
                    junctionPromoRulesListMap.put(String.valueOf(attQuoteSite.Id),wirelinePromoRuleList);
                    system.debug('@@@before calculatePromotions');              
                    wirelinePromoHelper.calculatePromotions(junctionPromoRulesListMap);
                    system.debug('@@@After calculatePromotions');
                }
            }
        } 
    }
    
    /* 
    *Name: finish
    *Description: This is the finish method of the Batch Class, which will be called once execute method is completed.
    */ 
    global void finish(Database.BatchableContext BC){
        System.debug('finish');
        Map<String,String> siteAndRegionMap = new Map<String,String>();
        for( Apttus_Config2__LineItem__c lineItem : lineItems ){         
            if(lineItem.Apttus_Config2__AttributeValueId__r.IGLOO_Speed_Unavailable__c == false && lineitem.Apttus_Config2__AttributeValueId__r.IGLOO_Call_Failure__c == false){         
                lineItem.isPricingApplied__c = true; 
            }
            lineItem.IsBatchUpdate__c = true;
            siteAndRegionMap.put(lineitem.AT_T_Customer_Site__r.id,lineitem.Apttus_Config2__AttributeValueId__r.VASA_Region__c);
        }
        if(!Test.isRunningTest()){ 
            update lineItems;   
        }
    
        //Igloo Quote Stage Updates      
        if(!lineItems.isEmpty() && String.isNotBlank(lineItems[0].Apttus_Config2__AttributeValueId__r.QuoteId__c)){
            Apttus_Proposal__Proposal__c quoteObj = [Select Id,Renewal_Contract__c,Is_Offline_Config_Completed__c,Apttus_Proposal__Opportunity__c,Send_Email_on_Rate_Refresh__c,isRateRefreshBatchProcessing__c,Buyflow_Step__c,Rate_Card_Effective_Date__c,Apttus_QPConfig__PriceListId__r.Apttus_Config2__EffectiveDate__c, Apttus_Proposal__Approval_Stage__c,applyAllFlag__c FROM Apttus_Proposal__Proposal__c WHERE Id =:quoteId  LIMIT 1];
            if(quoteObj.Is_Offline_Config_Completed__c){  
                quoteObj.Is_Offline_Config_Completed__c = false;
                update quoteObj;
            }
                        
            //After IGLOO offline processing, stage will only be updated to Bulk Service Availability Completed if all the sites have got Successful IGLOO response
            Boolean offlineProcessingComplete = false;            
            system.debug('@@@@(date.parse(quoteObj.Rate_Card_Effective_Date__c).daysBetween(quoteObj.Apttus_QPConfig__PriceListId__r.Apttus_Config2__EffectiveDate__c.date())' + (date.parse(quoteObj.Rate_Card_Effective_Date__c).daysBetween(quoteObj.Apttus_QPConfig__PriceListId__r.Apttus_Config2__EffectiveDate__c.date())));
            if(quoteObj.Renewal_Contract__c == false && (quoteObj.Rate_Card_Effective_Date__c != null && quoteObj.Apttus_QPConfig__PriceListId__r.Apttus_Config2__EffectiveDate__c != null && (date.parse(quoteObj.Rate_Card_Effective_Date__c).daysBetween(quoteObj.Apttus_QPConfig__PriceListId__r.Apttus_Config2__EffectiveDate__c.date()) == 0 || date.parse(quoteObj.Rate_Card_Effective_Date__c).daysBetween(quoteObj.Apttus_QPConfig__PriceListId__r.Apttus_Config2__EffectiveDate__c.date()) == 1 || date.parse(quoteObj.Rate_Card_Effective_Date__c).daysBetween(quoteObj.Apttus_QPConfig__PriceListId__r.Apttus_Config2__EffectiveDate__c.date()) == -1 ))  && (quoteObj.Apttus_Proposal__Approval_Stage__c.equalsIgnoreCase(BuyflowConstant.BULKSERVICE_AVAILABILITY_REQUESTED) || quoteObj.Apttus_Proposal__Approval_Stage__c.equalsIgnoreCase('Bulk Service Availability Requested'))){
                quoteObj.Apttus_Proposal__Approval_Stage__c = BuyflowConstant.BULKSERVICE_AVAILABILITY_COMPLETED;
                offlineProcessingComplete = true;
                system.debug('@@@Bulk Processing Completed!!!');
            }
            quoteObj.applyAllFlag__c = true; 
           
            //Rate Refresh Logic            
            if(quoteObj.Renewal_Contract__c == false && quoteObj.Rate_Card_Effective_Date__c != null && quoteObj.Apttus_QPConfig__PriceListId__r.Apttus_Config2__EffectiveDate__c != null && date.parse(quoteObj.Rate_Card_Effective_Date__c).daysBetween(quoteObj.Apttus_QPConfig__PriceListId__r.Apttus_Config2__EffectiveDate__c.date())>1){  
                
                if(quoteObj.Apttus_Proposal__Approval_Stage__c.equalsIgnoreCase(BuyflowConstant.BULKSERVICE_AVAILABILITY_REQUESTED)){
                    quoteObj.Apttus_Proposal__Approval_Stage__c = BuyflowConstant.BULKSERVICE_AVAILABILITY_COMPLETED;
                    update quoteObj;
                } 
                else{
                    quoteObj.Apttus_Proposal__Approval_Stage__c = 'Draft';
                }
                quoteObj.isRateRefreshBatchProcessing__c = false; 
                quoteObj.Rate_Card_Effective_Date__c = quoteObj.Apttus_QPConfig__PriceListId__r.Apttus_Config2__EffectiveDate__c.format('M/dd/yyyy');
                List<Opportunity> opp=new List<Opportunity>();
                opp=[select id,stageName from Opportunity  where id =: quoteObj.Apttus_Proposal__Opportunity__c];
                
                if(quoteObj.Buyflow_Step__c!=null && quoteObj.Buyflow_Step__c!= ATTConstants.CONFIGURE_SITES && iglooAvSize>0){
                    quoteObj.Buyflow_Step__c = ATTConstants.CONFIGURE_SITES;
                    quoteObj.Apttus_Proposal__Approval_Stage__c = 'Draft'; 
                    if(opp!=null && opp.size()>0){
                        opp[0].stageName='Saved';
                        update opp[0];
                    }
                }
                else{
                    if(opp!=null && opp.size()>0){
                        if(opp[0].StageName!=null && opp[0].StageName!='' && (opp[0].StageName=='Deal Reg Approved' || opp[0].StageName=='Deal Reg Auto-Approved')){
                            quoteObj.Apttus_Proposal__Approval_Stage__c = 'Deal Reg Approved'; 
                        }
                        else if(opp[0].StageName!=null && opp[0].StageName!='' && opp[0].StageName=='Deal Registration Requested'){
                            quoteObj.Apttus_Proposal__Approval_Stage__c = 'Pending Deal Reg';
                        }
                        else if(opp[0].StageName!=null && opp[0].StageName!='' && opp[0].StageName=='Pricing Schedule Pending'){
                            quoteObj.Send_Email_on_Rate_Refresh__c=true;
                      }                      
                  }
              }     
            }
            else if(offlineProcessingComplete == true){                        
                quoteObj.Is_Offline_Config_Completed__c = true;
            } 
            
            //Contract Renewal Logic
            if(quoteObj.Renewal_Contract__c == true){
                quoteObj.Apttus_Proposal__Approval_Stage__c = 'Pending Deal Reg';                
            }                   
            update quoteObj;
            if(quoteObj.Renewal_Contract__c == true){
                ApttusServiceUtilityHelper helper = new ApttusServiceUtilityHelper();
                if(!test.isrunningTest()){
                    helper.createContractRenewalDeal(quoteObj.Id);
                }
            }          
        }  
    }
}