example/secondfile/objects/Apttus_Proposal__Proposal__c.object
<CustomObject>
    <fields>
        <fullName>Product_Name__c</fullName>
        <formula>Product__r.Name</formula>
        <label>Product Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Quote_Expiration_Date__c</fullName>
        <formula>Apttus_Proposal__Opportunity__r.Quote_Expiration_Date__c</formula>
        <label>Quote Expiration Date</label>
        <type>Date</type>
    </fields>
</CustomObject>

example/secondfile/objects/Canvas_Debug_log__c.object
<CustomObject>
    <description>This Object will store the User, Quote ID details</description>
    <fields>
        <fullName>Product_Type__c</fullName>
        <label>Product Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Quote_Id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Look up to the Quote record</description>
        <label>Quote Id</label>
        <referenceTo>Apttus_Proposal__Proposal__c</referenceTo>
        <relationshipLabel>Canvas Debug logs</relationshipLabel>
        <relationshipName>Canvas_Debug_logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quote_Name__c</fullName>
        <label>Quote Name</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Look up field for the name of the user</description>
        <label>User Name</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Canvas_Debug_logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Canvas Debug log</label>
    <nameField>
        <displayFormat>CDL-{0000000}</displayFormat>
        <label>Canvas Debug log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Canvas Debug logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

example/secondfile/objects/Canvas_Debug_Log_Control__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>To control the logging of Canvas Parameters</description>
    <fields>
        <fullName>Enable_Parameter_Logging__c</fullName>
        <defaultValue>false</defaultValue>
        <description>To enable or disable the logging of parameters sent to canvas App</description>
        <label>Enable Parameter Logging</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>TimeOut_Value__c</fullName>
        <label>TimeOut Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Canvas Debug Log Control</label>
</CustomObject>

example/secondfile/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Calculated_Discount_Percentage__c</fullName>
        <label>Calculated Discount Percentage</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Cumulative_OTC_Discount_Price__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Cumulative OTC Discount Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Custom_Deal_Reg_Percentage__c</fullName>
        <label>Custom Deal Reg Percentage</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Deal_Reg_Approval_Date__c</fullName>
        <label>Deal Reg Approval Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Discount_Amount__c</fullName>
        <label>Discount Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Discounted_Percentage__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Deal Registration Discounted Percentage</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Discounted_Price__c</fullName>
        <label>Discounted Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Opportunity_ID__c</fullName>
        <displayFormat>{000000}</displayFormat>
        <label>SFDC Opportunity ID</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>Product_Name__c</fullName>
        <label>Product Name</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AVPN</fullName>
                </value>
                <value>
                    <fullName>CaaS</fullName>
                </value>
                <value>
                    <fullName>StaaS</fullName>
                </value>
                <value>
                    <fullName>MIS</fullName>
                </value>
                <value>
                    <fullName>IPFlex</fullName>
                </value>
                <value>
                    <fullName>Ethernet (Opt-E-Man)</fullName>
                </value>
                <value>
                    <fullName>Mobility DR</fullName>
                </value>
                <value>
                    <fullName>IPDSL</fullName>
                </value>
                <value>
                    <fullName>AT&amp;T Connect</fullName>
                </value>
                <value>
                    <fullName>Hosting</fullName>
                </value>
                <value>
                    <fullName>Mobility CRU</fullName>
                </value>
                <value>
                    <fullName>Mobile Toggle</fullName>
                </value>
                <value>
                    <fullName>Mobile Device Management</fullName>
                </value>
                <value>
                    <fullName>ANIRA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Quote_Expiration_Date__c</fullName>
        <label>Quote Expiration Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Quote_ID__c</fullName>
        <description>This is used to display proposal id and display in email template.</description>
        <label>Quote ID</label>
        <length>40</length>
        <type>Text</type>
    </fields>
</CustomObject>

secondfile/objects/Product_Pricing__c.object
<CustomObject>
    <fields>
        <fullName>SP_Discount_Percentage__c</fullName>
        <description>This is special Pricing Field</description>
        <label>Special Pricing Discount %</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SP_Product__c</fullName>
        <label>SP Product</label>
        <referenceTo>SPProduct__c</referenceTo>
        <relationshipLabel>Product Pricing</relationshipLabel>
        <relationshipName>Product_Pricing</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>discount_price__c</fullName>
        <label>Discount Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>discounted_price__c</fullName>
        <label>Discounted Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>product_name__c</fullName>
        <label>Product Name</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <label>Product Pricing</label>
    <nameField>
        <displayFormat>P-{00000}</displayFormat>
        <label>Pricing ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Pricing</pluralLabel>
    <recordTypes>
        <fullName>Feature</fullName>
        <active>true</active>
        <description>Features for Products</description>
        <label>Feature</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

example/secondfile/objects/SPProduct__c.object
<CustomObject>
    <description>Contains the information of the products like AVPN,CaaS and StaaS</description>
    <fields>
        <fullName>Deal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Deal</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>SP Products</relationshipLabel>
        <relationshipName>SPProducts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Discount_Amount__c</fullName>
        <description>1. If Percentage discount method is chosen:
a.  Populate the field based on
i.  Discount Amount = List Price * (Discount Percentage) / 100
2.  If Fixed Price method is chosen:
a.  Populate the field based
i.  Discount Amount = List Price – Fixed Discounted Price</description>
        <label>Special Pricing Discount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Discounted_Percentage__c</fullName>
        <description>1. If Percentage discount method is chosen:
a.  Populate the field based on “Discount Percentage” value
b.  Discounted Percentage = Discount Percentage
2.  If Fixed Price method is chosen:
a.  Populate the field based on
i.  Discounted Percentage = (List Price – Fixed Discounted Price) / (List Price) * 100</description>
        <label>Special Pricing Percentage</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Discounted_Price__c</fullName>
        <label>Discounted Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>One_Time_Revenue_Discount_Price__c</fullName>
        <defaultValue>0</defaultValue>
        <label>One Time Revenue Discount Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Product_Name__c</fullName>
        <label>Product Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Quote_Expiration_Date__c</fullName>
        <label>Quote Expiration Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SP_Discount_Percentage__c</fullName>
        <label>Special Pricing Discount %</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <label>SPProduct</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>SP Product ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SP Products</pluralLabel>
    <recordTypes>
        <fullName>Anira</fullName>
        <active>true</active>
        <description>Contains product &apos;Anira&apos;</description>
        <label>Anira</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

example/secondfile/classes/AIA_JSONGenerator.cls
/**********************************************************
Apex Class to Generate JSON for the Quote/Proposal record
and log parameters being sent to Canvas.See object Canvas 
Debug Log Control Object for Parameter logging
**********************************************************/
public class AIA_JSONGenerator{
    public string recordId{get; set;}
    public String jsonContent {get; set;}
    public String timeOutValue  {get; set;}
    public String canvasHeight{get; set;}
    public String canvasWidth{get; set;}
    public list<Apttus_Proposal__Proposal__c> proposalObj = new list<Apttus_Proposal__Proposal__c>();
    
    public AIA_JSONGenerator(ApexPages.StandardController controller) {
        //To fetch Quote Id from the URL
        recordId = ApexPages.currentPage().getParameters().get('quoteId');
       // getJSONContent();    
    }
    //Method to generate JSON 
    public void getJSONContent() {
        //Query to fetch fields from the Proposal Object for generating JSON 
        
        proposalObj = [select id, name, Product_Name__c,Apttus_Proposal__Proposal_Name__c from Apttus_Proposal__Proposal__c where id=:recordId limit 1];
        JSONGenerator gen = JSON.createGenerator(true);
        gen.writeStartObject();
        gen.writeStringField('Record Id ', proposalObj[0].id );
        gen.writeStringField('Proposal ID ', proposalObj[0].name );
        if(proposalObj[0].Apttus_Proposal__Proposal_Name__c != null && proposalObj[0].Apttus_Proposal__Proposal_Name__c != '') {
          gen.writeStringField('Proposal Name ', proposalObj[0].Apttus_Proposal__Proposal_Name__c );
        } else {
          gen.writeStringField('Proposal Name ', proposalObj[0].name );
        }        
        
        if(canvasHeight != null && canvasHeight !=''){
            gen.writeStringField('height ', canvasHeight );
        }
        if(canvasWidth != null && canvasWidth !=''){
            gen.writeStringField('width ', canvasWidth );
        }
        gen.writeEndObject();
        jsonContent = gen.getAsString();
        system.debug('This is the generated JSON : ' + jsonContent);
    }
    
    /************************************************************************************
    * Method : logCanvasParameters()
    * Return type :  void
    * Logic: To log the parameters in custom object "Canvas Debug Log Control". Logic is 
    *        controlled by custom setting as a switch.
    *************************************************************************************/
    public void logCanvasParameters(){
        getJSONContent();
        //Custom Setting to enable / disable parameter logging feature
        Canvas_Debug_Log_Control__c cdlcObj = Canvas_Debug_Log_Control__c.getvalues('Canvas Parameter Logging');
        boolean enableParameterLog = cdlcObj.Enable_Parameter_Logging__c;
        timeOutValue = cdlcObj.TimeOut_Value__c;
        if(enableParameterLog){
            list<Canvas_Debug_log__c> cdlList = new list<Canvas_Debug_log__c>();
          //  proposalObj = [select id, name, Apttus_Proposal__Proposal_Name__c from Apttus_Proposal__Proposal__c where id=:recordId limit 1];
            system.debug('This is the Proposal fetched: ' + proposalObj);
            Canvas_Debug_log__c cdlObj = new Canvas_Debug_log__c();
            cdlObj.Quote_Id__c = proposalObj[0].id;
            cdlObj.Quote_Name__c = proposalObj[0].Apttus_Proposal__Proposal_Name__c;
            cdlObj.User_Name__c = userInfo.getUserId();
            if(proposalObj[0].Product_Name__c != null)
            cdlObj.Product_Type__c = proposalObj[0].Product_Name__c;
            cdlList.add(cdlObj);
            if(!cdlList.isEmpty()){
                try{
                    database.insert(cdlList);
                } Catch (DmlException e){
                    system.debug('Failed to insert the Parameters' + e);
                }
            }
        }
    }
    
   /************************************************************************************
    * Method : clearDiscount()
    * Return type :  void
    * Logic:  
    * 1.Opportunity Status changes to  'Saved'
    * 2.clear's discounts for ANIRA When clicked on reconfigured 
    *************************************************************************************/
     @RemoteAction
      public Static void clearDiscount(String recordId){
        try{
            
            
            Apttus_Proposal__Proposal__c objProposal= [Select Id,Apttus_Proposal__Approval_Stage__c,Name,Apttus_Proposal__Proposal_Name__c,Apttus_Proposal__Opportunity__c,Apttus_Proposal__Opportunity__r.Opportunity_ID__c, Apttus_Proposal__Account__c,Apttus_Proposal__Account__r.Name from Apttus_Proposal__Proposal__c where id=:recordId];    
           system.debug('!!!objProposal: '+objProposal);
           system.debug('!!!objProposal: '+objProposal.id);
           
            //Update Opportunity
            
          Opportunity objOpp= [Select Id,Name,StageName,Discounted_Percentage__c, Custom_Deal_Reg_Percentage__c, Discounted_Price__c, Calculated_Discount_Percentage__c, Discount_Amount__c, Cumulative_OTC_Discount_Price__c from Opportunity where id=:objProposal.Apttus_Proposal__Opportunity__c Limit 2];
            system.debug('######objOpp  before : '+objOpp);
            
            objOpp.stageName = 'Saved';
            objOpp.Custom_Deal_Reg_Percentage__c =0;
            objOpp.Discounted_Price__c =0;
            objOpp.Calculated_Discount_Percentage__c = 0;
            objOpp.Cumulative_OTC_Discount_Price__c = 0;
            objOpp.Discounted_Percentage__c = 0.00;
            objOpp.Discount_Amount__c = 0;
            objOpp.Quote_Expiration_Date__c = null;
            objOpp.Deal_Reg_Approval_Date__c = null;
            
            update objOpp;
            system.debug('######lstSPProduct after : '+objOpp);
            system.debug('####objOppLst.id'+objOpp.id);

            //Update SPProduct
            List<spProduct__C> lstSPProduct = [Select id,Deal__c,Discounted_Price__c, One_Time_Revenue_Discount_Price__c FROM spProduct__C WHERE Deal__c = :objOpp.id];
            system.debug('######lstSPProduct before : '+lstSPProduct);
            system.debug('####objOppLst.id'+objOpp.id);
            
            for(spProduct__C objSPP : lstSPProduct){
                objSPP.Discounted_Price__c =0;
                objSPP.One_Time_Revenue_Discount_Price__c = 0;
            }
            if(!lstSPProduct.isEmpty()) update lstSPProduct;
            system.debug('#######lstSPProduct after : '+lstSPProduct);
            
            //Product Pricing
            List<Product_Pricing__c> lstPP = [Select id, SP_Discount_Percentage__c, discounted_price__c,discount_price__c FROM Product_Pricing__c WHERE SP_Product__c =: lstSPProduct];
            system.debug('######lstPP before : '+lstPP);
            for(Product_Pricing__c objPP : lstPP){
                objPP.SP_Discount_Percentage__c =0;
                objPP.discounted_price__c = 0;
                objPP.discount_price__c=0;
            }
            if(!lstPP.isEmpty()) update lstPP;
            system.debug('#######lstPP after : '+lstPP);
            
            
        
        }catch(Exception ae){
            System.debug('**** Exception occured ' + ae.getMessage());
        }
        
    }   
 
}