example/secondfile/objects/Apttus_Proposal__Proposal__c.object
<CustomObject>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>35</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Send_Email_on_Service_Complete__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Send Email on Service Complete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zip_Code__c</fullName>
        <label>Zip Code</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

secondfile/objects/CustomerSite__c.object
<CustomObject>
    <description>Custom object to store customer site information</description>
    <fields>
        <fullName>ASE_ITPA_Processing_Complete__c</fullName>
        <defaultValue>true</defaultValue>
        <label>ASE ITPA Processing Complete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ASE_ITPA_Request_Time__c</fullName>
        <label>ASE ITPA Request Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>ASE_ITPA_Response_Status__c</fullName>
        <label>ASE ITPA Response Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ASE_ITPA_Response__c</fullName>
        <label>ASE ITPA Response</label>
        <length>131072</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Address_Line__c</fullName>
        <label>Street</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Level__c</fullName>
        <label>Level</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Avail_Key__c</fullName>
        <formula>LOWER(SUBSTITUTE(Address_Line__c, &quot; &quot;, &quot;&quot;)+SUBSTITUTE(City__c, &quot; &quot;, &quot;&quot;)+SUBSTITUTE(TEXT(State__c), &quot; &quot;, &quot;&quot;)+SUBSTITUTE(Zip_Code__c, &quot; &quot;, &quot;&quot;))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Service Avail Key</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AL</fullName>
                </value>
                <value>
                    <fullName>AK</fullName>
                </value>
                <value>
                    <fullName>AZ</fullName>
                </value>
                <value>
                    <fullName>AR</fullName>
                </value>
                <value>
                    <fullName>CA</fullName>
                </value>
                <value>
                    <fullName>CO</fullName>
                </value>
                <value>
                    <fullName>CT</fullName>
                </value>
                <value>
                    <fullName>DE</fullName>
                </value>
                <value>
                    <fullName>FL</fullName>
                </value>
                <value>
                    <fullName>GA</fullName>
                </value>
                <value>
                    <fullName>HI</fullName>
                </value>
                <value>
                    <fullName>ID</fullName>
                </value>
                <value>
                    <fullName>IL</fullName>
                </value>
                <value>
                    <fullName>IN</fullName>
                </value>
                <value>
                    <fullName>IA</fullName>
                </value>
                <value>
                    <fullName>KS</fullName>
                </value>
                <value>
                    <fullName>KY</fullName>
                </value>
                <value>
                    <fullName>LA</fullName>
                </value>
                <value>
                    <fullName>ME</fullName>
                </value>
                <value>
                    <fullName>MD</fullName>
                </value>
                <value>
                    <fullName>MA</fullName>
                </value>
                <value>
                    <fullName>MI</fullName>
                </value>
                <value>
                    <fullName>MN</fullName>
                </value>
                <value>
                    <fullName>MS</fullName>
                </value>
                <value>
                    <fullName>MO</fullName>
                </value>
                <value>
                    <fullName>MT</fullName>
                </value>
                <value>
                    <fullName>NE</fullName>
                </value>
                <value>
                    <fullName>NV</fullName>
                </value>
                <value>
                    <fullName>NH</fullName>
                </value>
                <value>
                    <fullName>NJ</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Structure__c</fullName>
        <label>Structure</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Unit__c</fullName>
        <label>Unit</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zip_Code__c</fullName>
        <label>Zip Code</label>
        <length>5</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>AT&amp;T Customer Site</label>
    <nameField>
        <displayFormat>ADD-{000000}</displayFormat>
        <label>Site #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AT&amp;T Customer Sites</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

example/secondfile/objects/Max_Sites_Allowed_For_ITPA__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Max Sites Allowed For ITPA</description>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Max Sites Allowed For ITPA</label>
</CustomObject>

example/secondfile/objects/Max_Validity_for_ITPA__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Max Validity for ITPA</label>
</CustomObject>

secondfile/classes/ASEITPAServiceAvailabilityUtil.cls
/************************************************************************************** 
 Apex Class Name     : ASEITPAServiceAvailabilityUtil
 Version             : 1.0 
 Created Date        : 13 November 2016
 Function            : Util class for ASE ITPA Service Availability 
*************************************************************************************/
public with sharing class ASEITPAServiceAvailabilityUtil{
    /*Check Service Availability for ASE ITPA*/  
    public static Boolean doASEITPACall(List<CustomerSite__c>validSiteList,ASEITPAServiceAvailResponseBean ASEITPAresponse,String quoteId){
        // Service Availability Check for selected and valid customer sites 
        Map <Integer, List<CustomerSite__c>> ITPAAvailMap  = new Map<Integer,List<CustomerSite__c>>();
        Integer keyIndex = 0;
        boolean ITPAAvailFlag = false;
        boolean isEmailSelected = false;
        Map<Id, CustomerSite__c> custSiteIdCustSiteObjMap = new Map<Id, CustomerSite__c>();
        for (CustomerSite__c item : [Select Id, ASE_ITPA_Response__c, ASE_ITPA_Response_Status__c, ASE_ITPA_Request_Time__c, ASE_ITPA_Processing_Complete__c From CustomerSite__c Where Id In: validSiteList]){
            custSiteIdCustSiteObjMap.put(item.Id, item);            
        }
        if(quoteid != null){
            list<Apttus_Proposal__Proposal__c> quoteList = [select id,Send_Email_on_Service_Complete__c from Apttus_Proposal__Proposal__c where id =:quoteid];
            isEmailSelected = quoteList[0].Send_Email_on_Service_Complete__c;    
        }       
        Integer max_sites = Integer.valueOf(Max_Sites_Allowed_For_ITPA__c.getValues('ASE_ITPA_Max_Sites') != null ? Max_Sites_Allowed_For_ITPA__c.getValues('ASE_ITPA_Max_Sites').value__c: 30);
        Integer max_days = Integer.valueOf(Max_Validity_for_ITPA__c.getValues('ASE_ITPA_Max_Days') != null ? Max_Validity_for_ITPA__c.getValues('ASE_ITPA_Max_Days').value__c: 20);
        Set<Id> validSiteSet = new Set<Id>();
        for (CustomerSite__c item : validSiteList) {           
            if (validSiteList.size() <= Max_sites && custSiteIdCustSiteObjMap.get(item.Id) != null &&
                (custSiteIdCustSiteObjMap.get(item.Id).ASE_ITPA_Response__c == NULL  || 
                   custSiteIdCustSiteObjMap.get(item.Id).ASE_ITPA_Processing_Complete__c == false ||
                    (custSiteIdCustSiteObjMap.get(item.Id).ASE_ITPA_Response__c != NULL 
                        && custSiteIdCustSiteObjMap.get(item.Id).ASE_ITPA_Request_Time__c != NULL 
                         && ((custSiteIdCustSiteObjMap.get(item.Id).ASE_ITPA_Request_Time__c.date().daysBetween(system.now().date())) > max_days || isEmailSelected)) )){
                ITPAAvailFlag = true;
                if(!ITPAAvailMap.containsKey(keyIndex)) {                  
                    ITPAAvailMap.put(keyIndex,new List<CustomerSite__c>{item});
                } else {
                    if (ITPAAvailMap.get(keyIndex).size() == 3) {
                        keyIndex ++;
                        ITPAAvailMap.put(keyIndex,new List<CustomerSite__c>{item}); 
                    } else {
                        ITPAAvailMap.get(keyIndex).add(item);
                    }    
                }
            } else if (validSiteList.size() <= Max_sites 
                        && custSiteIdCustSiteObjMap.get(item.Id) != null  
                        && custSiteIdCustSiteObjMap.get(item.Id).ASE_ITPA_Response__c != NULL 
                        && custSiteIdCustSiteObjMap.get(item.Id).ASE_ITPA_Request_Time__c != NULL 
                        && (custSiteIdCustSiteObjMap.get(item.Id).ASE_ITPA_Request_Time__c.date().daysBetween(system.now().date())) <= max_days ) {
                validSiteSet.add(item.Id);
            } else if(validSiteList.size()>Max_sites) {
                ITPAAvailFlag = true;
                if (!ITPAAvailMap.containsKey(keyIndex)) {                  
                    ITPAAvailMap.put(keyIndex,new List<CustomerSite__c>{item});
                } else {
                    if (ITPAAvailMap.get(keyIndex).size()==3){
                        keyIndex ++;
                        ITPAAvailMap.put(keyIndex,new List<CustomerSite__c>{item}); 
                    }else{
                        ITPAAvailMap.get(keyIndex).add(item);
                    }    
                }
            } else {
            }
        }    
        //In case there is no Customer Site which require to get the ASE ITPA request i.e. the ASE ITPA request time is less than 20 days
        if(!ITPAAvailFlag) {
            return true;
        }
      
        List<ASEITPAServiceAvailInfoBean> beanList = new List<ASEITPAServiceAvailInfoBean>();    
        Map<String, List<CustomerSite__c>> updateServiceAvailResponseMap = new Map<String,List<CustomerSite__c>>();          
        ASEITPAServiceAvailService serviceObj = new ASEITPAServiceAvailService();    
        ASEITPAServiceAvailInfoBean.InquireTransportProductAvailabilityRequest InquireTransportProductAvailabilityRequestObj = new ASEITPAServiceAvailInfoBean.InquireTransportProductAvailabilityRequest();
        List <ASEITPAServiceAvailInfoBean.addresses> AddressList = new List <ASEITPAServiceAvailInfoBean.addresses>();
        ASEITPAServiceAvailIntegrationHandler handler = new ASEITPAServiceAvailIntegrationHandler();
        ASEITPAServiceAvailInfoBean bean = new ASEITPAServiceAvailInfoBean();                 
        if (ITPAAvailMap!=NULL && ITPAAvailMap.size()>0){      
            for (Integer key: ITPAAvailMap.keyset()) {               
                for(CustomerSite__c item : ITPAAvailMap.get(key)) {     
                    if(!updateServiceAvailResponseMap.containsKey(item.Service_Avail_Key__c)) {
                        updateServiceAvailResponseMap.put(item.id,new List<CustomerSite__c>{item});
                    }else {
                        updateServiceAvailResponseMap.get(item.id).add(item);
                    } 
                    
                    ASEITPAServiceAvailInfoBean.additionalRequestData additionalRequestDataObj = new ASEITPAServiceAvailInfoBean.additionalRequestData();
                    additionalRequestDataObj.productType = 'SDN';
                    additionalRequestDataObj.fiberCheckIndicator = true;
                    additionalRequestDataObj.aseLSCheckIndicator = true;
                    additionalRequestDataObj.aseCopperCheckIndicator = true;
                    
                    ASEITPAServiceAvailInfoBean.ase aseObj = new ASEITPAServiceAvailInfoBean.ase();
                    aseObj.aseIndicator = true;
                    aseObj.additionalRequestData = additionalRequestDataObj;
                    
                    ASEITPAServiceAvailInfoBean.requestedProducts requestedProductsObj = new ASEITPAServiceAvailInfoBean.requestedProducts();
                    requestedProductsObj.ase = aseObj;
                    
                    ASEITPAServiceAvailInfoBean.validationOptions validationOptionsObj = new ASEITPAServiceAvailInfoBean.validationOptions();
                    validationOptionsObj.glidLookup = 3;
                    validationOptionsObj.maxAlternativeReturn = 10;                 
                   
                    ASEITPAServiceAvailInfoBean.unfieldedAddress unfieldedAddressObj = new ASEITPAServiceAvailInfoBean.unfieldedAddress();
                    unfieldedAddressObj.addressLine = item.Address_Line__c;
                    unfieldedAddressObj.structureValue = item.Structure__c;
                    unfieldedAddressObj.levelValue = item.Level__c;
                    unfieldedAddressObj.unitValue = item.Unit__c;
                    unfieldedAddressObj.city = item.City__c;
                    unfieldedAddressObj.state = item.State__c;
                    unfieldedAddressObj.postalCode = String.valueof(item.Zip_Code__c);
                    
                    ASEITPAServiceAvailInfoBean.locationOptions locationOptionsObj = new ASEITPAServiceAvailInfoBean.locationOptions();
                    locationOptionsObj.unfieldedAddress = unfieldedAddressObj;
                   
                    ASEITPAServiceAvailInfoBean.location locationObj = new ASEITPAServiceAvailInfoBean.location();
                    locationObj.locationOptions = locationOptionsObj;
                    locationObj.validationOptions = validationOptionsObj;
                    
                    ASEITPAServiceAvailInfoBean.addresses addressesObj = new ASEITPAServiceAvailInfoBean.addresses();
                    addressesObj.siteId = item.Id;
                    addressesObj.location = locationObj;
                    addressesObj.requestedProducts = requestedProductsObj;
                    AddressList.add(addressesObj);                      
                }                
            }
            InquireTransportProductAvailabilityRequestObj.quoteId = (quoteId!=null)? quoteId : ''; 
            InquireTransportProductAvailabilityRequestObj.addresses = AddressList;     
            bean.InquireTransportProductAvailabilityRequest = InquireTransportProductAvailabilityRequestObj; 
        }    
        try{     
            if (bean!=null  && validSiteList.size() <= Max_sites && ITPAAvailFlag && isEmailSelected == false){                
                ASEITPAresponse = (ASEITPAServiceAvailResponseBean)serviceObj.handleAddressValidationServiceAvailabilityRequest(bean, null);
            }else if((bean!=null  && validSiteList.size() >Max_sites && ITPAAvailFlag ) || isEmailSelected){
                ASEITPAresponse = (ASEITPAServiceAvailResponseBean)serviceObj.handleAddressValidationServiceAvailabilityRequest(bean, null);
                //if(resBeanAsync!=null && !string.isBlank(resBeanAsync.message) && resBeanAsync.message.equalsIgnoreCase(BuyflowConstant.SUBMITTED)) {       
                return true;
                //}
            }      
        }catch(Exception e) {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,e.getMessage()));
            ATTException.logException( e.getTypeName(), ATTException.constructExceptionMessageString(e));
        }
        try{
            if (ASEITPAresponse != NULL && ASEITPAresponse.InquireTransportProductAvailabilityResponse != NULL && validSiteList!=NULL) {
                ITPAServiceAvailResponseBean respBean = new ITPAServiceAvailResponseBean();
                if(respBean != null){
                    system.debug('@@@@response'+JSON.serialize(respBean));
                }
            }   
        }catch(Exception e) {
            system.debug('Exception in ASEITPAServiceAvailabilityUtil.doITPACall'+e);
        }    
        return false;
    }   
}