example/secondfile/objects/Apttus_Proposal__Proposal__c.object
<CustomObject>
    <fields>
        <fullName>Deal_Registration_Expire_Date__c</fullName>
        <description>Returns current date plus 6 months.</description>
        <formula>IF 
( 
MONTH( TODAY() ) &gt; 6 
, 
DATE 
( 
YEAR( TODAY() ) + 1, 
MOD( MONTH( TODAY() ) + 6 , 12 ), 
DAY( TODAY() ) 
) 
, 
DATE 
( 
YEAR( TODAY() ), 
MONTH( TODAY() ) + 6, 
DAY( TODAY() ) 
) 
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Returns current date plus 6 months.</inlineHelpText>
        <label>Deal Registration Expire Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>End_Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>End Customer</label>
        <referenceTo>End_Customer__c</referenceTo>
        <relationshipLabel>Proposals</relationshipLabel>
        <relationshipName>Proposals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>QuoteExpirationDate__c</fullName>
        <label>Quote Expiration Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Service_Type__c</fullName>
        <label>Service Type</label>
        <length>100</length>
        <type>Text</type>
    </fields>
</CustomObject>

example/secondfile/objects/End_Customer__c.object
<CustomObject>
    <fields>
        <fullName>Anira_Custom_Discount__c</fullName>
        <label>Anira Custom Discount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>End Customer</label>
    <nameField>
        <label>End Customer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>End Customers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

example/secondfile/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>ATOM_Deal__c</fullName>
        <defaultValue>false</defaultValue>
        <label>ATOM Deal</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Apply_Promotions__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This check box is used to trigger promotions logic on post EBM Decisions.</description>
        <label>Apply_Promotions</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Batch_Deal_Reg_Approved__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Batch Deal Reg Approved</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>BroadBand_Product__c</fullName>
        <defaultValue>false</defaultValue>
        <label>BroadBand Product</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Cumulative_List_Price__c</fullName>
        <label>Cumulative List Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Cumulative_OTC_Discount_Price__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Cumulative OTC Discount Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Cumulative_OTC_Price__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Cumulative OTC Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Custom_Deal_Reg_Percentage__c</fullName>
        <label>Custom Deal Reg Percentage</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Deal_Reg_Approved__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Deal Reg Approved</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Discount_Amount__c</fullName>
        <label>Discount Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Discount_Percentage__c</fullName>
        <label>Discount Percentage</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Discounted_Percentage__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Deal Registration Discounted Percentage</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Discounted_Price__c</fullName>
        <label>Discounted Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>End_Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>End Customer</label>
        <referenceTo>End_Customer__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>List_Price__c</fullName>
        <label>List Price</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MIS_Product__c</fullName>
        <defaultValue>false</defaultValue>
        <label>MIS Product</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Mobility__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This Flag is used for Attwireless product.</description>
        <label>Attwireless Flag</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Number_of_Products__c</fullName>
        <label>Number of Products</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>OTC_Discount_Amount__c</fullName>
        <label>OTC Discount Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Promo_Deal_Reg__c</fullName>
        <defaultValue>&quot;True&quot;</defaultValue>
        <label>Promo Deal Reg</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_type__c</fullName>
        <label>Service type</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Standard_Discount_Percentage__c</fullName>
        <label>Standard Discount Percentage</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>X3rd_Party_Flag__c</fullName>
        <defaultValue>false</defaultValue>
        <label>3rd Party Flag</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

secondfile/objects/Product_Pricing__c.object
<CustomObject>
    <fields>
        <fullName>ATOM_Deal__c</fullName>
        <formula>SP_Product__r.Deal__r.ATOM_Deal__c</formula>
        <label>ATOM Deal</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Discountable__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Non-Discountable</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SP_Product__c</fullName>
        <label>SP Product</label>
        <referenceTo>SPProduct__c</referenceTo>
        <relationshipLabel>Product Pricing</relationshipLabel>
        <relationshipName>Product_Pricing</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>X3rd_Party_Flag__c</fullName>
        <formula>SP_Product__r.X3rd_Party_Flag__c</formula>
        <label>3rd Party Flag</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>discounted_price__c</fullName>
        <label>Discounted Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>list_price__c</fullName>
        <defaultValue>0.00</defaultValue>
        <label>List Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>type__c</fullName>
        <label>Type</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Product Pricing</label>
    <nameField>
        <displayFormat>P-{00000}</displayFormat>
        <label>Pricing ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Pricing</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

secondfile/objects/Promotion_Engine_Junction__c.object
<CustomObject>
    <fields>
        <fullName>Custom_Deal_Reg_Percentage__c</fullName>
        <formula>Opportunity__r.Deal_Reg_Discount_Percentage__c</formula>
        <label>Custom Deal Reg Percentage</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Discount_Percentage__c</fullName>
        <label>Discount Percentage</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Eligible__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Eligible</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Promotion Engine Junction</relationshipLabel>
        <relationshipName>Promotion_Engine_Junction</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Rank__c</fullName>
        <label>Rank</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Promotion Engine Junction</label>
    <nameField>
        <displayFormat>PEJ-{00000}</displayFormat>
        <label>Promotion Engine Junction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Promotion Engine Junction</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

example/secondfile/objects/SPProduct__c.object
<CustomObject>
    <description>Contains the information of the products like AVPN,CaaS and StaaS</description>
    <fields>
        <fullName>ATOM_Deal__c</fullName>
        <formula>Deal__r.ATOM_Deal__c</formula>
        <label>ATOM Deal</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Deal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Deal</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>SP Products</relationshipLabel>
        <relationshipName>SPProducts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Discount_Amount__c</fullName>
        <description>1. If Percentage discount method is chosen:
a.  Populate the field based on
i.  Discount Amount = List Price * (Discount Percentage) / 100
2.  If Fixed Price method is chosen:
a.  Populate the field based
i.  Discount Amount = List Price – Fixed Discounted Price</description>
        <label>Special Pricing Discount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Discount_Percentage__c</fullName>
        <label>Discount Percentage</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Discounted_Percentage__c</fullName>
        <description>1. If Percentage discount method is chosen:
a.  Populate the field based on “Discount Percentage” value
b.  Discounted Percentage = Discount Percentage
2.  If Fixed Price method is chosen:
a.  Populate the field based on
i.  Discounted Percentage = (List Price – Fixed Discounted Price) / (List Price) * 100</description>
        <label>Special Pricing Percentage</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Discounted_Price__c</fullName>
        <label>Discounted Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>End_Customer__c</fullName>
        <formula>Deal__r.End_Customer__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>End Customer</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>List_Price__c</fullName>
        <label>List Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>OTC_Discount_Amount__c</fullName>
        <defaultValue>0</defaultValue>
        <label>OTC Discount Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Service_Type__c</fullName>
        <label>Service Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>X3rd_Party_Flag__c</fullName>
        <formula>Deal__r.X3rd_Party_Flag__c</formula>
        <label>3rd Party Flag</label>
        <type>Checkbox</type>
    </fields>
    <label>SPProduct</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>SP Product ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SP Products</pluralLabel>
    <recordTypes>
        <fullName>Anira</fullName>
        <active>true</active>
        <description>Contains product &apos;Anira&apos;</description>
        <label>Anira</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

secondfile/classes/ATOMDealRegApprovalBatchProcess.cls
global class ATOMDealRegApprovalBatchProcess implements Database.Batchable<sObject> {

    global String opptyId;
    global Boolean discountable;
    global Boolean isAutoDealApproval;
    global Decimal customDiscountPercentage;

    global ATOMDealRegApprovalBatchProcess ( String oppId, Boolean discountable, Boolean isAutoDealApproval, Decimal customDiscountPercentage) {
        this.opptyId = oppId;
        this.discountable = discountable ;
        this.isAutoDealApproval = isAutoDealApproval;
        this.customDiscountPercentage = customDiscountPercentage;
        System.debug('@@@@opptyId'+opptyId);
        System.debug('@@@@discountable'+discountable);
        System.debug('@@@@isAutoDealApproval '+isAutoDealApproval);
        System.debug('@@@@customDiscountPercentage'+customDiscountPercentage);
    }
    
    global Database.QueryLocator start(Database.BatchableContext BC){
        String queryString = 'SELECT ID ,StageName, End_Customer__c, Service_type__c, X3rd_Party_Flag__c, AccountId, BroadBand_Product__c, MIS_Product__c, Cumulative_List_Price__c, Discount_Amount__c, OTC_Discount_Amount__c, Cumulative_OTC_Price__c, Cumulative_OTC_Discount_Price__c, Discounted_Price__c, Discounted_Percentage__c, Mobility__c, ATOM_Deal__c, Batch_Deal_Reg_Approved__c,Custom_Deal_Reg_Percentage__c,Number_of_Products__c FROM Opportunity WHERE Id='+'\''+opptyId+'\'';
        System.debug('@@@@Query'+queryString);
        return Database.getQueryLocator(queryString);
    }
    
    global void execute( Database.BatchableContext BC, List<Opportunity> opptyList ){
        System.debug('@@@@inside execute: opptyId'+opptyId);
        System.debug('@@@@inside execute: discountable'+discountable);
        System.debug('@@@@inside execute: isAutoDealApproval '+isAutoDealApproval );
        System.debug('@@@@inside execute: customDiscountPercentage'+customDiscountPercentage);
        
        Opportunity Opty;
        list <Apttus_Proposal__Proposal__c> proposalList = new list <Apttus_Proposal__Proposal__c>();        
        
        Opty= [SELECT ID ,StageName, End_Customer__c,Service_type__c, X3rd_Party_Flag__c, AccountId, BroadBand_Product__c, MIS_Product__c, Cumulative_List_Price__c, Discount_Amount__c, OTC_Discount_Amount__c, Cumulative_OTC_Price__c, Cumulative_OTC_Discount_Price__c, Discounted_Price__c, Discounted_Percentage__c, Mobility__c, ATOM_Deal__c, Batch_Deal_Reg_Approved__c,Custom_Deal_Reg_Percentage__c,Number_of_Products__c FROM Opportunity WHERE ID =: opptyId];      
        proposalList=[Select Id,QuoteExpirationDate__c,Deal_Registration_Expire_Date__c,Apttus_Proposal__Opportunity__r.Id from Apttus_Proposal__Proposal__c where Apttus_Proposal__Opportunity__r.Id=:opptyId];
        if(customDiscountPercentage != null){
            opty.Custom_Deal_Reg_Percentage__c = customDiscountPercentage;
        }  
        
        if (!Opty.X3rd_Party_Flag__c){
            if(isAutoDealApproval){
                Opty.StageName = SIConstants.OPTY_DEAL_Auto_Approved;
            }else{
                Opty.StageName = SIConstants.OPTY_DEAL_APPROVED;    
            }
        }
        if(discountable == true){
            if(Opty.Custom_Deal_Reg_Percentage__c  != null)
            {
                Opty.Standard_Discount_Percentage__c = null;
            }
            opty.Apply_Promotions__c=true;
            opty.Promo_Deal_Reg__c='True';
            opty.Deal_Reg_Approved__c = true; 
            update opty;
            Date newdate = Date.today().addmonths(6);
            proposalList[0].QuoteExpirationDate__c= newdate;
            update proposalList;
           
            list<Promotion_Engine_Junction__c> PEJRank4 = new list<Promotion_Engine_Junction__c>();
            PEJRank4 = [select Id,Discount_Percentage__c from Promotion_Engine_Junction__c where Eligible__c = true and Rank__c = 4 and Opportunity__c =:opty.Id limit 1];
            if(PEJRank4.size()>0)
            {
                if(Opty.Custom_Deal_Reg_Percentage__c  != null)
                {
                    PEJRank4.get(0).Discount_Percentage__c = Opty.Custom_Deal_Reg_Percentage__c;
                }
                else
                {
                    PEJRank4.get(0).Discount_Percentage__c = Opty.Standard_Discount_Percentage__c;
                }
                update PEJRank4;
           }
          
           if(opty.Service_type__c == 'ANIRA') {
                list<End_Customer__c> endCust = new list<End_Customer__c>();
                endCust = [SELECT Anira_Custom_Discount__c FROM End_Customer__c WHERE ID=:opty.End_Customer__c limit 1];
               
                if(Opty.Custom_Deal_Reg_Percentage__c  != null) {
                    endCust.get(0).Anira_Custom_Discount__c = opty.Custom_Deal_Reg_Percentage__c;
                }
                if(endCust.size() > 0) {
                    update endCust;
                }
                
            }    
        }
        else{
            Double discountableListPrice=0;
            Double nonDiscountableListPrice=0;
            Double discountableOTCPrice=0;
            Double nonDiscountableOTCPrice=0;
            AggregateResult[] groupedResults = [SELECT SUM(list_price__c) sumValue,Type__c,Discountable__c FROM Product_Pricing__c pr WHERE pr.SP_Product__c IN (SELECT Id FROM SPProduct__c WHERE Deal__c = :opptyId) GROUP BY Type__c, Discountable__c];
       
            if(!groupedResults.isEmpty() && groupedResults!=null)
            {
                for(AggregateResult agr: groupedResults)
                {
                    if(((agr.get('Type__c'))=='MRC') && ((agr.get('Discountable__c'))==false))
                    {
                        discountableListPrice = Double.ValueOf(agr.get('sumValue'));
                    }
                    else if(((agr.get('Type__c'))=='MRC') && ((agr.get('Discountable__c'))==true))
                    {
                        nonDiscountableListPrice = Double.ValueOf(agr.get('sumValue'));
                    }
                    else if(((agr.get('Type__c'))=='NRC') && ((agr.get('Discountable__c'))==false))
                    {
                        discountableOTCPrice = Double.ValueOf(agr.get('sumValue'));
                    }
                    else if (((agr.get('Type__c'))=='NRC') && ((agr.get('Discountable__c'))==true))
                    {
                        nonDiscountableOTCPrice = Double.ValueOf(agr.get('sumValue'));
                    }
                }
            }
            Opty.Discount_Amount__c = null;
            Opty.Discounted_Percentage__c = null;
            Opty.Custom_Deal_Reg_Percentage__c = null;
            Opty.Standard_Discount_Percentage__c =null;
            Opty.OTC_Discount_Amount__c = null;
            Opty.Discounted_Price__c =nonDiscountableListPrice+discountableListPrice;
            Opty.Cumulative_OTC_Discount_Price__c = nonDiscountableOTCPrice+discountableOTCPrice;
            opty.Apply_Promotions__c=true;
            opty.Promo_Deal_Reg__c='False';
            opty.Deal_Reg_Approved__c = true; 
            update Opty;
            Date newdate = Date.today().addmonths(6);
            proposalList[0].QuoteExpirationDate__c= newdate;
            update proposalList;
            SIConstants.isDealRegApproval =true;           
        }
    }

    global void finish(Database.BatchableContext BC){            
        
        list <Opportunity> oppUpdateList =new list<Opportunity>();                    
        if(opptyId != null)
        {
            oppUpdateList = [SELECT Id,Batch_Deal_Reg_Approved__c FROM Opportunity WHERE Id =: opptyId];
            for(Opportunity opty: oppUpdateList){
                opty.Batch_Deal_Reg_Approved__c = true;
            }
            update oppUpdateList;
        }                 
    }  
}