example/secondfile/objects/Apttus_Proposal__Proposal__c.object
<CustomObject>
    <fields>
        <fullName>RelatedQuote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related Quote</label>
        <referenceTo>Apttus_Proposal__Proposal__c</referenceTo>
        <relationshipLabel>Proposals (RelatedQuote)</relationshipLabel>
        <relationshipName>Proposals</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

secondfile/objects/Deal_Hash__c.object
<CustomObject>
    <fields>
        <fullName>RDS_object_status__c</fullName>
        <label>RDS Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Received</fullName>
                </value>
                <value>
                    <fullName>Review in progress</fullName>
                </value>
                <value>
                    <fullName>Edit period expired</fullName>
                </value>
                <value>
                    <fullName>Review completed</fullName>
                </value>
                <value>
                    <fullName>Deal Hash Creation API in Progress</fullName>
                </value>
                <value>
                    <fullName>Deal Hash Creation API Successful</fullName>
                </value>
                <value>
                    <fullName>Deal Hash Creation API Failed</fullName>
                </value>
                <value>
                    <fullName>SA Contract Subscription API Failed</fullName>
                </value>
                <value>
                    <fullName>SA Contract Subscription API in Progress</fullName>
                </value>
                <value>
                    <fullName>SA Contract Subscription API Successful</fullName>
                </value>
                <value>
                    <fullName>Deal Hash Update - Cancel API In Progress</fullName>
                </value>
                <value>
                    <fullName>Deal Hash Update - Cancel API Successful</fullName>
                </value>
                <value>
                    <fullName>Deal Hash Update - Cancel API Failed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Renewal_Contract_Quote_Name__c</fullName>
        <formula>RenewedQuote__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Renewal Contract Quote Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RenewedQuote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>This is a techical Field</inlineHelpText>
        <label>Renewed Quote</label>
        <referenceTo>Apttus_Proposal__Proposal__c</referenceTo>
        <relationshipLabel>RDS-Deal Hash (Renewed Quote)</relationshipLabel>
        <relationshipName>RDS_Deal_Hash1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>RDS-Deal Hash</label>
    <nameField>
        <displayFormat>DH-{00000}</displayFormat>
        <label>Deal Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RDS-Deal Hash</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

example/secondfile/objects/DHStatus_Update_Deal_Hash_Details__c.object
<CustomObject>
    <fields>
        <fullName>Deal_Hash_Created_By__c</fullName>
        <formula>RDS_Deal_Hash__r.CreatedById</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Deal Hash Created By</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Deal_Hash_Name__c</fullName>
        <formula>RDS_Deal_Hash__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Deal Hash Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Renewal_Contract_Quote_Name__c</fullName>
        <formula>RDS_Deal_Hash__r.Renewal_Contract_Quote_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Renewal Contract Quote Name</label>
        <type>Text</type>
    </fields>
    <label>DHStatus-Update Deal Hash Details</label>
    <nameField>
        <displayFormat>DHS-{0000}</displayFormat>
        <label>DHStatus-RDS Update Deal Hash Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DHStatus-Update Deal Hash Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

secondfile/objects/IT_Support_Ticket__c.object
<CustomObject>
    <description>Used to open IT Support Tickets for ATT Maintenance projects.</description>
    <fields>
        <fullName>Error_Message_Received__c</fullName>
        <inlineHelpText>If you see an error message for your issue, please copy/paste here.</inlineHelpText>
        <label>Error Message Received</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Impact__c</fullName>
        <label>Impact</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Logged_Date_Time__c</fullName>
        <label>Logged Date/Time</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>RelatedQuote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>US799054 - Helps track the tickets created for the SIVAR - API failure</description>
        <label>Related Quote/Proposal</label>
        <referenceTo>Apttus_Proposal__Proposal__c</referenceTo>
        <relationshipLabel>IT Support Tickets</relationshipLabel>
        <relationshipName>APIFailureSupportTickets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Related_Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Added as part of RDS Excel failure exception handling to tag ITS tickets to its related opportunity</description>
        <label>Related Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>IT Support Tickets</relationshipLabel>
        <relationshipName>IT_Support_Tickets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Related_to__c</fullName>
        <label>Related to</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Accounts</fullName>
                </value>
                <value>
                    <fullName>Contacts</fullName>
                </value>
                <value>
                    <fullName>Credit Validations</fullName>
                </value>
                <value>
                    <fullName>Data Access</fullName>
                </value>
                <value>
                    <fullName>Data Mismatch with BID</fullName>
                </value>
                <value>
                    <fullName>Data Mismatch with ROME</fullName>
                </value>
                <value>
                    <fullName>Deal Registration Approval</fullName>
                </value>
                <value>
                    <fullName>Email</fullName>
                </value>
                <value>
                    <fullName>Enhancement</fullName>
                </value>
                <value>
                    <fullName>Force Portal</fullName>
                    <default>true</default>
                    <label>Force Portal</label>
                </value>
                <value>
                    <fullName>General Field Update</fullName>
                </value>
                <value>
                    <fullName>General Process Flow</fullName>
                </value>
                <value>
                    <fullName>Lead Conversion</fullName>
                </value>
                <value>
                    <fullName>On/Off cart deals</fullName>
                </value>
                <value>
                    <fullName>Opportunities</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>SI/VAR-API</fullName>
                </value>
                <value>
                    <fullName>Sign on</fullName>
                </value>
                <value>
                    <fullName>Special Pricing Approval</fullName>
                </value>
                <value>
                    <fullName>SP Products</fullName>
                </value>
                <value>
                    <fullName>User Creation/Deletion</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Severity__c</fullName>
        <label>Severity</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1- Critical</fullName>
                </value>
                <value>
                    <fullName>2 - High</fullName>
                </value>
                <value>
                    <fullName>3 - Medium</fullName>
                    <default>true</default>
                    <label>3 - Medium</label>
                </value>
                <value>
                    <fullName>4 - Low</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>On Hold - Client Input/Verification Needed</fullName>
                </value>
                <value>
                    <fullName>On Hold - Referred to External Application</fullName>
                </value>
                <value>
                    <fullName>On Hold - Targeted for Maintenance Release</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Deferred(CR)</fullName>
                </value>
                <value>
                    <fullName>Not an Issue</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Steps_to_Reproduce_Error__c</fullName>
        <inlineHelpText>Enter step by step instructions for how the error was produced</inlineHelpText>
        <label>Steps to Reproduce Error</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Ticket_Subject__c</fullName>
        <label>Subject</label>
        <length>175</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>IT Support Ticket</label>
    <nameField>
        <displayFormat>ITS-{000000}</displayFormat>
        <label>IT Support Ticket #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>IT Support Tickets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

example/secondfile/objects/ITS_Ticket_Flag__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>TS Ticket for RDS Excel Failure</description>
    <fields>
        <fullName>Create_ITS__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Create ITS</label>
        <type>Checkbox</type>
    </fields>
    <label>ITS Ticket for RDS Excel Failure</label>
</CustomObject>

example/secondfile/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>BID_ID__c</fullName>
        <externalId>true</externalId>
        <label>Deal Registration Number</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Quote_ID__c</fullName>
        <description>This is used to display proposal id and display in email template.</description>
        <label>Quote ID</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RDS_Excel_failure_reason__c</fullName>
        <description>RDS Excel failure reason</description>
        <label>RDS Excel failure reason</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>RDS_Excel_status__c</fullName>
        <description>RDS Excel status</description>
        <label>RDS Excel status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

secondfile/objects/RDS_Premise_Details__c.object
<CustomObject>
    <fields>
        <fullName>Deal_Hash_name__c</fullName>
        <formula>DealHash__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Deal Hash name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RelatedQuote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Quote/Proposal</label>
        <referenceTo>Apttus_Proposal__Proposal__c</referenceTo>
        <relationshipLabel>RDS-Premise Details (Quote/Proposal)</relationshipLabel>
        <relationshipName>RDS_Premise_Details2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Renewal_Contract_Deal_Hash__c</fullName>
        <formula>DealHash__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Renewal Contract Deal Hash</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Renewal_Contract_Quote__c</fullName>
        <formula>RelatedQuote__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Renewal Contract Quote</label>
        <type>Text</type>
    </fields>
    <label>RDS-Premise Details</label>
    <nameField>
        <displayFormat>P - {000000}</displayFormat>
        <label>Premise Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RDS-Premise Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

secondfile/classes/RDSExcelExceptionHandling.cls
/*************************************************************************************************************************************** 
Apex Class Name     : RDSExcelExceptionHandling
Version             : 1.0 
Created Date        : 1 Feb 2016 
Function            : This class handles exception handling for RDS/API Calls/Contract Renewal flows
****************************************************************************************************************************************/
public class RDSExcelExceptionHandling{
    Opportunity Opp ;
    ITS_Ticket_Flag__c itsFlag= ITS_Ticket_Flag__c.getInstance();
    
    /*Method to create ITS Support Ticket for RDS Excel Creation Failure*/    
    public void changeOpptyStatus(Id oppId, string ExcelStat,string failReason,string quoteName){
        try{             
            Opp = [select Id,Name,BID_ID__c,RDS_Excel_status__c,RDS_Excel_failure_reason__c from Opportunity where Id =: oppId];
            Opp.RDS_Excel_status__c = ExcelStat;
            Opp.RDS_Excel_failure_reason__c = failReason;
            update Opp;
            //Custom Setting to on/off the ITS ticket creation
            if(itsFlag.Create_ITS__c && !string.isBlank(failReason)){
                createITS(failReason,Opp.BID_ID__c,Opp.Id);
            }                 
        }
        catch(exception e){
            failReason='Catch changing status of Oppty: '+e.getLinenumber();
            if(itsFlag.Create_ITS__c && !string.isBlank(failReason)){
                createITS(failReason,Opp.BID_ID__c,Opp.Id);
            }
            system.debug('Exception while changing status of Oppty: '+e.getLinenumber());
        }
    }
        
    /*Create ITS Support Ticket for RDS Excel Creation*/     
    public void createITS(string failedR, string sname, Id opptyId){
        IT_Support_Ticket__c itss = new IT_Support_Ticket__c();
        itss.Related_to__c = 'Force Portal/BID Portal';
        itss.Logged_Date_Time__c = System.Now();
        itss.Ticket_Subject__c = 'RDS Excel Creation Failed for Quote Id: '+sname ;
        itss.Impact__c = 'High';
        itss.Severity__c = '2 - High';
        string err = 'Excel Failure for Quote Id: '+sname+'\n'+failedR;
        itss.Error_Message_Received__c = err;
        itss.Related_Opportunity__c = opptyId;
        insert itss;
    }
    
    /*Create ITS Support Ticket in case of API Call Failure*/    
    public void createAPITicket(map<id,Apttus_Proposal__Proposal__c> failedAPICallMap){
        final string RELATED_TO = 'SI/VAR-API';
        final string TKT_SUBJECT = 'API Failure due to service unavailable';
        final string SEVERITY = '2 - High';
        final string IMPACT = 'API Call Failed Due to Service Unavailable, User is unable to continue in portal for this order and potentially others';
        list<IT_Support_Ticket__c> insertITSList = new list<IT_Support_Ticket__c>();
        try{
            for(Apttus_Proposal__Proposal__c apObj : failedAPICallMap.values()){
                IT_Support_Ticket__c itObj = new IT_Support_Ticket__c();                    
                itObj.Related_to__c = RELATED_TO ;
                itObj.Ticket_Subject__c = TKT_SUBJECT;
                itObj.Severity__c = SEVERITY;
                itObj.Steps_to_Reproduce_Error__c = 'Order '+ apObj.Name +' is receiving API failure due to Service being Unavailable for one or more APIs in the system. SP User has tried multiple time to retrigger API in the system.'+'\n'+'Please investigate '+apObj.Name;  
                itObj.Impact__c = IMPACT;
                itObj.Status__c = Constant.Status_Open;
                itObj.RelatedQuote__c = apObj.id;
                itObj.Logged_Date_Time__c = System.Now();
                itObj.OwnerId = apObj.ownerId;
                insertITSList.add(itObj);                    
            }
            if(!insertITSList.isEmpty()){
                insert insertITSList;
            }
        }
        catch(Exception exce){
            string exceptionString = ATTException.constructExceptionMessageString(exce);
            ATTException.createExceptionWithoutFuture( 'RDSExcelExceptionHandling createAPITicket',exceptionString, exce.getMessage());        
        }   
    }
        
    /*Create ITS Support Ticket in case of Deal Rate Plan Failure for Contract Renewal Flow*/
    public void createContractRenewalITSTicket(map<id,Opportunity> renewalContractOpptyMap){
        final string RELATED_TO = RenewConstant.RENEW_SIVAR_API;
        final string TKT_SUBJECT = RenewConstant.RENEW_DEALRATE_PLAN_API_FAILURE;
        final string SEVERITY = RenewConstant.RENEW_HIGH;
        final string IMPACT = RenewConstant.RENEW_ITS_API_IMPACT_MSG;
        list<IT_Support_Ticket__c> insertITSList = new list<IT_Support_Ticket__c>();
        try{
            for(Opportunity oppty : renewalContractOpptyMap.values()){
                IT_Support_Ticket__c itObj = new IT_Support_Ticket__c();                    
                itObj.Related_to__c = RELATED_TO;                
                itObj.Ticket_Subject__c = TKT_SUBJECT;
                itObj.Severity__c = SEVERITY;
                itObj.Steps_to_Reproduce_Error__c = RenewConstant.RENEW_DEALRATE_PLAN_API_FAILURE+'\n'+RenewConstant.RENEW_REPRODUCE_ERR_MSG2+oppty.Quote_ID__c+RenewConstant.RENEW_REPRODUCE_ERR_MSG3;  
                itObj.Impact__c = IMPACT;
                itObj.Status__c = RenewConstant.RENEW_ITS_API_STATUS;
                itObj.Logged_Date_Time__c = System.Now();
                itObj.OwnerId = oppty.createdById;
                itObj.Related_Opportunity__c = oppty.Id;
                insertITSList.add(itObj);                    
            }
            if(!insertITSList.isEmpty()){
                insert insertITSList;
            }
        }
        catch(Exception exce){
            string exceptionString = ATTException.constructExceptionMessageString(exce);
            ATTException.createExceptionWithoutFuture( 'RDSExcelExceptionHandling createContractRenewalITSTicket',exceptionString, exce.getMessage());            
        }   
    }
    
    /*201945 Contract Renewal  ITS Ticket Creation  IDH Failure After WFE Push Notification*/
    public void createContractRenewalIDHITSTicket(map<id,RDS_Premise_Details__c> renewalContractPremiseMap){
        list<IT_Support_Ticket__c> insertITSList = new list<IT_Support_Ticket__c>();
        try{
            for(RDS_Premise_Details__c premise : renewalContractPremiseMap.values()){
                IT_Support_Ticket__c itObj = new IT_Support_Ticket__c();                    
                itObj.Related_to__c = RenewConstant.RENEW_SIVAR_API;                
                itObj.Ticket_Subject__c = RenewConstant.RENEW_IDHAFTER_PUSH_NOTI_FAILURE;
                itObj.Severity__c = RenewConstant.RENEW_HIGH;
                itObj.Steps_to_Reproduce_Error__c = RenewConstant.RENEW_IDHAFTER_PUSH_NOTI_FAILURE+'\n'+RenewConstant.RENEW_REPRODUCE_ERR_MSG2+premise.Renewal_Contract_Quote__c+RenewConstant.RENEW_OR+premise.Renewal_Contract_Deal_Hash__c+RenewConstant.RENEW_REPRODUCE_ERR_MSG3;  
                itObj.Impact__c = RenewConstant.RENEW_IDH_PUSH_NOTI_FAILURE_IMPACT_MSG;
                itObj.Status__c = RenewConstant.RENEW_ITS_API_STATUS;
                itObj.Logged_Date_Time__c = System.Now();
                itObj.OwnerId = premise.createdById;
                itObj.RelatedQuote__c = premise.RelatedQuote__c;
                insertITSList.add(itObj);                    
            }
            if(!insertITSList.isEmpty()){
                insert insertITSList;
            }
        }
        catch(Exception exce){
            string exceptionString = ATTException.constructExceptionMessageString(exce);
            ATTException.createExceptionWithoutFuture( 'RDSExcelExceptionHandling createContractRenewalIDHITSTicket',exceptionString, exce.getMessage());            
        }   
    }
    
    /*201972 Contract Renewal  ITS Ticket Creation & Email Notification  Automatic MACD Update Deal Hash Failure - Scenario one : DH MACD Update Status */
    public void createContractRenewalDHITSTicket(Map<id,Deal_Hash__c> renewalContractDealHashMap){
        list<IT_Support_Ticket__c> insertITSList = new list<IT_Support_Ticket__c>();
        try{
            for(Deal_Hash__c dealHashObj : renewalContractDealHashMap.values()){
                IT_Support_Ticket__c itObj = new IT_Support_Ticket__c();                    
                itObj.Related_to__c = RenewConstant.RENEW_SIVAR_API; 
                if(dealHashObj.RDS_object_status__c!=null && dealHashObj.RDS_object_status__c.equalsIgnoreCase('Deal Hash Creation API Failed'))
                {               
                    itObj.Ticket_Subject__c = 'Contract Renewal – Automatic Update Deal Hash Failure';
                    itObj.Steps_to_Reproduce_Error__c = 'Contract Renewal – Automatic Update Deal Hash Failure'+'\n'+RenewConstant.RENEW_REPRODUCE_ERR_MSG2+dealHashObj.Renewal_Contract_Quote_Name__c+RenewConstant.RENEW_OR+dealHashObj.Name+RenewConstant.RENEW_REPRODUCE_ERR_MSG3;  
                } 
                else
                {
                    itObj.Ticket_Subject__c = RenewConstant.RENEW_MACDUPDATE_FAILURE;
                     itObj.Steps_to_Reproduce_Error__c = RenewConstant.RENEW_MACDUPDATE_FAILURE+'\n'+RenewConstant.RENEW_REPRODUCE_ERR_MSG2+dealHashObj.Renewal_Contract_Quote_Name__c+RenewConstant.RENEW_OR+dealHashObj.Name+RenewConstant.RENEW_REPRODUCE_ERR_MSG3;  
                }
                itObj.Severity__c = RenewConstant.RENEW_HIGH;
               
                itObj.Impact__c = RenewConstant.RENEW_MACDUPDATE_IMPACT_MSG;
                itObj.Status__c = RenewConstant.RENEW_ITS_API_STATUS;
                itObj.Logged_Date_Time__c = System.Now();
                itObj.OwnerId = dealHashObj.createdById;
                itObj.RelatedQuote__c = dealHashObj.RenewedQuote__c;
                insertITSList.add(itObj);                    
            }
            if(!insertITSList.isEmpty()){
                insert insertITSList;
            }
        }
        catch(Exception exce){
            string exceptionString = ATTException.constructExceptionMessageString(exce);
            ATTException.createExceptionWithoutFuture( 'RDSExcelExceptionHandling createContractRenewalMACDUpdateITSTicket',exceptionString, exce.getMessage());            
        }   
    }
    
    /*201972 Contract Renewal  ITS Ticket Creation & Email Notification  Automatic MACD Update Deal Hash Failure - Scenario one : DHS API Process Status    */
    public void createContractRenewalDHSITSTicket(Map<id,DHStatus_Update_Deal_Hash_Details__c> renewalContractDhStatusMap){
        list<IT_Support_Ticket__c> insertITSList = new list<IT_Support_Ticket__c>();
        try{
            for(DHStatus_Update_Deal_Hash_Details__c dhStatusObj : renewalContractDhStatusMap.values()){
                IT_Support_Ticket__c itObj = new IT_Support_Ticket__c();                    
                itObj.Related_to__c = RenewConstant.RENEW_SIVAR_API;   
                           
                itObj.Ticket_Subject__c = RenewConstant.RENEW_MACDUPDATE_FAILURE;
                itObj.Severity__c = RenewConstant.RENEW_HIGH;
                itObj.Steps_to_Reproduce_Error__c = RenewConstant.RENEW_MACDUPDATE_FAILURE+'\n'+RenewConstant.RENEW_REPRODUCE_ERR_MSG2+dhStatusObj.Renewal_Contract_Quote_Name__c+RenewConstant.RENEW_OR+dhStatusObj.Deal_Hash_Name__c+RenewConstant.RENEW_REPRODUCE_ERR_MSG3;  
                itObj.Impact__c = RenewConstant.RENEW_MACDUPDATE_IMPACT_MSG;
                itObj.Status__c = RenewConstant.RENEW_ITS_API_STATUS;
                itObj.Logged_Date_Time__c = System.Now();
                itObj.OwnerId = Id.ValueOf(dhStatusObj.Deal_Hash_Created_By__c);
                itObj.RelatedQuote__c = dhStatusObj.Renewed_Quote__c;
                insertITSList.add(itObj);                    
            }
            if(!insertITSList.isEmpty()){
                insert insertITSList;
            }
        }
        catch(Exception exce){
            string exceptionString = ATTException.constructExceptionMessageString(exce);
            ATTException.createExceptionWithoutFuture( 'RDSExcelExceptionHandling createContractRenewalMACDUpdateITSTicket',exceptionString, exce.getMessage());            
        }   
    }
}