example/secondfile/objects/Apttus_Config2__LineItem__c.object
<CustomObject>
    <fields>
        <fullName>AT_T_Customer_Site__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used to Link Customer Site ; VASA Region and Line Item based on VASA Response</description>
        <label>AT&amp;T Customer Site</label>
        <referenceTo>CustomerSite__c</referenceTo>
        <relationshipLabel>Line Items</relationshipLabel>
        <relationshipName>Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Alternate_Access_IGLOO_Access_Price__c</fullName>
        <label>Alternate Access IGLOO Access Price</label>
        <precision>18</precision>
        <scale>5</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>isPricingApplied__c</fullName>
        <defaultValue>false</defaultValue>
        <label>isPricingApplied</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

example/secondfile/objects/Apttus_Proposal__Proposal__c.object
<CustomObject>
    <fields>
        <fullName>Product_Name__c</fullName>
        <formula>Product__r.Name</formula>
        <label>Product Name</label>
        <type>Text</type>
    </fields>
</CustomObject>

example/secondfile/objects/AT_T_Customer_Site_Quote__c.object
<CustomObject>
    <description>Junction object setup between Site and Quote objects.</description>
    <fields>
        <fullName>AT_T_Customer_Site__c</fullName>
        <label>AT&amp;T Customer Site</label>
        <referenceTo>CustomerSite__c</referenceTo>
        <relationshipLabel>AT&amp;T Customer Site Quotes</relationshipLabel>
        <relationshipName>AT_T_Customer_Site_Quotes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>AT_T_Quote__c</fullName>
        <label>AT&amp;T Quote</label>
        <referenceTo>Apttus_Proposal__Proposal__c</referenceTo>
        <relationshipLabel>AT&amp;T Customer Site Quotes</relationshipLabel>
        <relationshipName>AT_T_Customer_Site_Quotes</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Alternate_Access_IGLOO_Access_Price__c</fullName>
        <label>Alternate Access IGLOO Access Price</label>
        <precision>18</precision>
        <scale>5</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Alternate_Access_ITPA_Response_Status__c</fullName>
        <description>Reporting Fields</description>
        <formula>AT_T_Customer_Site__r.Alternate_Access_ITPA_Response_Status__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Alternate Access ITPA Response Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Hub__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Hub</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Iglow_Response_Received_Date__c</fullName>
        <label>Igloo Response Received Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>VASA_Response_Status__c</fullName>
        <formula>TEXT(AT_T_Customer_Site__r.VASA_Response_Status__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>VASA Response Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>isPricingApplied__c</fullName>
        <defaultValue>false</defaultValue>
        <label>isPricingApplied</label>
        <type>Checkbox</type>
    </fields>
    <label>AT&amp;T Customer Site Quote</label>
    <nameField>
        <label>AT&amp;T Customer Site Quote Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AT&amp;T Customer Site Quotes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

secondfile/objects/CustomerSite__c.object
<CustomObject>
    <description>Custom object to store customer site information</description>
    <fields>
        <fullName>ACC_ITPA_Call_Status__c</fullName>
        <label>ACC ITPA Call Status</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Alternate_Access_ITPA_Response_Status__c</fullName>
        <label>Alternate Access ITPA Response Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Hub__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Hub</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>VASA_Request_Time__c</fullName>
        <label>Service Availability Request Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>VASA_Response_Status__c</fullName>
        <label>Service Availability Response Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>ADDRESS RECORD CREATED</fullName>
                    <default>true</default>
                    <label>ADDRESS RECORD CREATED</label>
                </value>
                <value>
                    <fullName>ADDRESS EXACT MATCH</fullName>
                </value>
                <value>
                    <fullName>ADDRESS NO MATCH</fullName>
                </value>
                <value>
                    <fullName>POSSIBLE MATCHES</fullName>
                </value>
                <value>
                    <fullName>SERVICE AVAILABILITY CHECKED</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>AT&amp;T Customer Site</label>
    <nameField>
        <displayFormat>ADD-{000000}</displayFormat>
        <label>Site #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AT&amp;T Customer Sites</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

example/secondfile/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Clear_Special_Pricing__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Clear Special Pricing</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Cumulative_List_Price__c</fullName>
        <label>Cumulative List Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Cumulative_OTC_Discount_Price__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Cumulative OTC Discount Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Cumulative_OTC_Price__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Cumulative OTC Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Discounted_Price__c</fullName>
        <label>Discounted Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>List_Price__c</fullName>
        <label>List Price</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Product_Name__c</fullName>
        <label>Product Name</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AVPN</fullName>
                </value>
                <value>
                    <fullName>CaaS</fullName>
                </value>
                <value>
                    <fullName>StaaS</fullName>
                </value>
                <value>
                    <fullName>MIS</fullName>
                </value>
                <value>
                    <fullName>IPFlex</fullName>
                </value>
                <value>
                    <fullName>Ethernet (Opt-E-Man)</fullName>
                </value>
                <value>
                    <fullName>Mobility DR</fullName>
                </value>
                <value>
                    <fullName>IPDSL</fullName>
                </value>
                <value>
                    <fullName>AT&amp;T Connect</fullName>
                </value>
                <value>
                    <fullName>Hosting</fullName>
                </value>
                <value>
                    <fullName>Mobility CRU</fullName>
                </value>
                <value>
                    <fullName>Mobile Toggle</fullName>
                </value>
                <value>
                    <fullName>Mobile Device Management</fullName>
                </value>
                <value>
                    <fullName>ANIRA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Special_Pricing_Approved__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Special Pricing Approved</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

secondfile/objects/Product_Pricing__c.object
<CustomObject>
    <fields>
        <fullName>Clear_Special_Pricing__c</fullName>
        <formula>SP_Product__r.Deal__r.Clear_Special_Pricing__c</formula>
        <label>Clear Special Pricing</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Discount_Type__c</fullName>
        <label>Discount Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Fixed Price</fullName>
                </value>
                <value>
                    <fullName>Discount %</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Discountable__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Non-Discountable</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Product_Record_Type__c</fullName>
        <formula>SP_Product__r.RecordType.Name</formula>
        <label>Product Record Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Record_Type__c</fullName>
        <formula>RecordType.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Record Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SP_Product__c</fullName>
        <label>SP Product</label>
        <referenceTo>SPProduct__c</referenceTo>
        <relationshipLabel>Product Pricing</relationshipLabel>
        <relationshipName>Product_Pricing</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>discount_price__c</fullName>
        <label>Discount Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>discounted_price__c</fullName>
        <label>Discounted Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>list_price__c</fullName>
        <defaultValue>0.00</defaultValue>
        <label>List Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>product_name__c</fullName>
        <label>Product Name</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>type__c</fullName>
        <label>Type</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Product Pricing</label>
    <nameField>
        <displayFormat>P-{00000}</displayFormat>
        <label>Pricing ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Pricing</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

example/secondfile/objects/SPProduct__c.object
<CustomObject>
    <description>Contains the information of the products like AVPN,CaaS and StaaS</description>
    <fields>
        <fullName>Competitive_Pricing_Status__c</fullName>
        <label>Special Pricing Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Special Pricing Denied</fullName>
                </value>
                <value>
                    <fullName>Special Pricing Approved</fullName>
                </value>
                <value>
                    <fullName>Special Pricing Requested</fullName>
                </value>
                <value>
                    <fullName>Special Pricing Incomplete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Discount_Type__c</fullName>
        <label>Discount Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Fixed Price</fullName>
                </value>
                <value>
                    <fullName>Discount %</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Discounted_Price__c</fullName>
        <label>Discounted Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>List_Price__c</fullName>
        <label>List Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Product_Name__c</fullName>
        <label>Product Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>SPProduct</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>SP Product ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SP Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

example/secondfile/classes/BuyflowUtil.cls
/************************************************************************************** 
 Apex Class Name     : BuyflowUtil
 Version             : 1.0 
 Created Date        : 02/20/2017
 Function            : This class tracks the portal constants
 Modification Log    :
* Developer                   Date                   Description
* ----------------------------------------------------------------------------                 
* US827483             02/20/2017                    Original Version
*************************************************************************************/

public class BuyflowUtil{
    
    /*
    @Method :returnVASAFAILRecords
    @Returns : list<AT_T_Customer_Site_Quote__c> 
    @Paramenter : string quoteId    
    */ 
    public static list<AT_T_Customer_Site_Quote__c> returnVASAFAILRecords(string quoteId){
        datetime myDateTime = datetime.now().addDays(-30);
        system.debug('myDateTime : ' +myDateTime );
        list<AT_T_Customer_Site_Quote__c> addRecCreatedSites = new list<AT_T_Customer_Site_Quote__c>();
        addRecCreatedSites = [select id, AT_T_Customer_Site__r.VASA_Request_Time__c from AT_T_Customer_Site_Quote__c where AT_T_Quote__c =: quoteId and  (AT_T_Customer_Site__r.VASA_Response_Status__c =: BuyflowConstant.ADDRESS_RECORD_CREATED or AT_T_Customer_Site__r.VASA_Request_Time__c <: myDateTime)];
        
        return addRecCreatedSites;
        
    }   
    /*******************************************************************
    * Method 		: returnITPAFAILRecords
    * Description 	: Return ITPA Failed site records 
    * Returns 		: list<AT_T_Customer_Site_Quote__c> 
    * Paramenter 	: string quoteId
    *******************************************************************/  
    public static list<AT_T_Customer_Site_Quote__c> returnITPAFAILRecords(string quoteId){
        
        set<string> errorStringSet = sendITPASuccessCodes();       
        
        list<AT_T_Customer_Site_Quote__c> addRecCreatedSites = new list<AT_T_Customer_Site_Quote__c>();
        addRecCreatedSites = [select id from AT_T_Customer_Site_Quote__c where AT_T_Quote__c =: quoteId and (AT_T_Customer_Site__r.Alternate_Access_ITPA_Response_Status__c != NULL AND  AT_T_Customer_Site__r.Alternate_Access_ITPA_Response_Status__c  NOT IN : errorStringSet) ];
        //addRecCreatedSites = [select id,ACC_ITPA_Call_Status__c from AT_T_Customer_Site_Quote__c where AT_T_Quote__c =: quoteId and (AT_T_Quote__r.ACC_ITPA_Call_Status__c ='Failed' OR(AT_T_Quote__r.ACC_ITPA_Call_Status__c  !='Failed' AND  AT_T_Customer_Site__r.Alternate_Access_ITPA_Response_Status__c  NOT IN : errorStringSet)) ];
        
        return addRecCreatedSites;
        
    }
   /*******************************************************************
    * Method name : sendITPASuccessCodes
    * Description : Sends out the codes for error consideration
    * Return Type : set<string>
    * Parameters  : None.
    *******************************************************************/        
    public static set<string> sendITPASuccessCodes(){
        set<string> errorStringSet = new set<string>();
        errorStringSet.add('200'); 
        errorStringSet.add('900');        
        return errorStringSet ;
    }
    
    /*******************************************************************
    * Method name : returnApexMessage
    * Description : Error text values for the retrail failures
    * Return Type : apexpages.message
    * Parameters  : integer
    * Used in : API_MACD_SiteAddInfoController & SiteAddressInformationController 
    *******************************************************************/    
    public static ApexPages.Message returnApexMessage(integer trialCount){
        ApexPages.Message flashMsg ; 
        if(trialCount >= 4){
            flashMsg = new ApexPages.Message(ApexPages.Severity.INFO, BuyflowConstant.VASA_VALIDATION_ERROR2 );
        }else{
            flashMsg = new ApexPages.Message(ApexPages.Severity.INFO, BuyflowConstant.VASA_VALIDATION_ERROR );
        }
        return flashMsg;
    }
    /*******************************************************************
    * Method name : returnApConfigLineItems
    * Description : Return the apptus config line items which are configured for switched ethernet
    * Return Type : list<Apttus_Config2__LineItem__c>
    * Parameters  : None.
    *******************************************************************/      
    public static list<Apttus_Config2__LineItem__c> returnApConfigLineItems(set<string> siteIdSet, string prodConfigId){
        list<Apttus_Config2__LineItem__c> lineItemList = new  list<Apttus_Config2__LineItem__c>();
        if(!siteIdSet.isEmpty()){
            lineItemList = [SELECT Id,Alternate_Access_IGLOO_Access_Price__c, Apttus_Config2__AttributeValueId__r.Port_Type_AVPN__c,Apttus_Config2__AdjustedPrice__c,Apttus_Config2__ExtendedPrice__c, Apttus_Config2__AttributeValueId__r.Port_Type_MIS__c, Apttus_Config2__BaseExtendedPrice__c,Apttus_Config2__BasePrice__c,Apttus_Config2__NetPrice__c, Apttus_Config2__AttributeValueId__c,  Apttus_Config2__ConfigurationId__c, Apttus_Config2__ChargeType__c,AT_T_Customer_Site__c FROM Apttus_Config2__LineItem__c WHERE Apttus_Config2__ConfigurationId__c=: prodConfigId AND AT_T_Customer_Site__c IN : siteIdSet AND ( (Apttus_Config2__AttributeValueId__r.Port_Type_AVPN__c !=null AND Apttus_Config2__AttributeValueId__r.Port_Type_AVPN__c  = 'Switched Ethernet')OR (Apttus_Config2__AttributeValueId__r.Port_Type_MIS__c != null AND Apttus_Config2__AttributeValueId__r.Port_Type_MIS__c = 'Switched Ethernet'))];
            
        }
        return lineItemList;
    }
    /*******************************************************************
    * Method name : returnApConfigLineItems
    * Description : Return the apptus config line items which are configured for switched ethernet
    * Return Type : list<Apttus_Config2__LineItem__c>
    * Parameters  : None.
    *******************************************************************/      
    public static map<string,string> returnEligibleSiteJunctions(string quoteId){
        integer IglooExpirationDays = 90; 
        map<string,string> custSiteJuncMap = new map<string,string>();
        list<AT_T_Customer_Site_Quote__c> lineItemList = new  list<AT_T_Customer_Site_Quote__c>();
        if(string.isNOTBlank(quoteId)){
            for(AT_T_Customer_Site_Quote__c custSiteQuote:[select id,AT_T_Customer_Site__c,Iglow_Response_Received_Date__c, AT_T_Quote__c,Hub__c from AT_T_Customer_Site_Quote__c where AT_T_Quote__c=:quoteId ]){
                if(custSiteQuote.Iglow_Response_Received_Date__c != null && custSiteQuote.Iglow_Response_Received_Date__c.daysBetween(system.now().date()) > IglooExpirationDays ){
                    //expiredSiteJunctionIdSet.add(custSiteQuote.AT_T_Customer_Site__c);
                    custSiteJuncMap.put(custSiteQuote.AT_T_Customer_Site__c,custSiteQuote.id);
                }
            }
        }
        return custSiteJuncMap;
    }
    
    /*******************************************************************
    * Method name : retrieveExistingCartId
    * Description : Sends out the codes for error consideration
    * Return Type : Apttus_Config2__ProductConfiguration__c 
    * Parameters  : String
    *******************************************************************/    
     public static Apttus_Config2__ProductConfiguration__c retrieveExistingCartId(string quoteId){
        system.debug('\n Inside buyflowUtil retrieveExistingCartId method------');
        string cartId = null;
        Apttus_Config2__ProductConfiguration__c prodConfig = null;
        list<Apttus_Config2__ProductConfiguration__c> prodConfigLst = null;        
        List<String> statusList = new List<String>();
        ApttusServiceUtilityHelper helper = new ApttusServiceUtilityHelper();
        statusList.add(SpecialCharacterConstant.NEW_CAPS_LITERAL);
        statusList.add(BuyflowConstant.SAVED);
        statusList.add(BuyflowConstant.FINALIZED);
        try{
            prodConfigLst = [select id, Apttus_QPConfig__Proposald__c, Apttus_Config2__Status__c,(Select Id, isPricingApplied__c,Apttus_Config2__ChargeType__c, AT_T_Customer_Site__c,Apttus_Config2__OptionId__c,Apttus_Config2__ProductId__c,Apttus_Config2__LineNumber__c,Apttus_Config2__Description__c,Apttus_Config2__OptionGroupLabel__c,Apttus_Config2__LineType__c,Apttus_Config2__NetPrice__c,Apttus_Config2__OptionId__r.Name,Apttus_Config2__PricingStatus__c, Apttus_Config2__ProductOptionId__c,Apttus_Config2__AttributeValueId__c, Apttus_Config2__ListPrice__c, Apttus_Config2__Quantity__c,Apttus_Config2__PriceType__c  From Apttus_Config2__LineItems__r) from Apttus_Config2__ProductConfiguration__c where Apttus_QPConfig__Proposald__c =: quoteId AND  Apttus_Config2__Status__c IN: statusList order by CreatedDate desc];
            if(prodConfigLst.size() > 0){
                prodConfig = prodConfigLst[0];                               
            }
        }catch(Exception e){
            ATTException.logException( e.getTypeName(), ATTException.constructExceptionMessageString(e));
        }
        return prodConfig;
    }
    /*******************************************************************
    * Method name : offsetSPOnOppty
    * Description : Removes any additional pricing applied
    * Return Type : void
    * Parameters  : Id
    *******************************************************************/ 
    public static void offsetSPOnOppty(Id OpptyId){
    
        Opportunity OpUpdate = new Opportunity();
        OpUpdate.id = OpptyId;
        OpUpdate.Special_Pricing_Approved__c = false;
        OpUpdate.Clear_Special_Pricing__c = true;
        //OpUpdate.Cumulative_List_Price__c = 0;
        //OpUpdate.Discounted_Price__c=0;
        //OpUpdate.Cumulative_OTC_Price__c =0;
        //OpUpdate.Cumulative_OTC_Discount_Price__c=0;
        update OpUpdate ;   
    }
    /*******************************************************************
    * Method name : returnConfigSiteReference
    * Description : Returns buyflow page reference
    * Return Type : void
    * Parameters  : pagereference
    *******************************************************************/ 
    public static pagereference returnConfigSiteReference(string quoteId){
        pagereference redirectToConfigPage = page.PortalDesign_Buyflow ;
        redirectToConfigPage.getparameters().put('mode','confsites');                
        redirectToConfigPage.getparameters().put('quoteid',quoteId);
        redirectToConfigPage.setredirect(true);  
        return redirectToConfigPage;    
    }
    /*******************************************************************
    * Method name : returnConfigSiteAddSiteReference
    * Description : Returns buyflow page reference
    * Return Type : void
    * Parameters  : pagereference
    *******************************************************************/ 
    public static pagereference returnConfigSiteAddSiteReference(string quoteId){
        pagereference redirectToConfigPage = page.API_MACD_PortalDesign_AVPN_MIS_BuyFlow; //api_macd_dealreg // API_MACD_PortalDesign_AVPN_MIS_BuyFlow
        redirectToConfigPage.getparameters().put('mode','confsites');                
        redirectToConfigPage.getparameters().put('quoteid',quoteId);
        redirectToConfigPage.setredirect(true);  
        return redirectToConfigPage;    
    }    
    /*******************************************************************
    * Method name : offSetProductPricing
    * Description : Removes any additional pricing applied
    * Return Type : void
    * Parameters  : Id
    *******************************************************************/ 
    public static void offSetProductPricing(Id OpptyId){
        list<Product_Pricing__c> ProdPricingUpdateList = new list<Product_Pricing__c>();
        for(Product_Pricing__c ppObj : [Select Id, Name, Record_Type__c,list_price__c, discounted_price__c,Discount_Price__c,   Product_Record_Type__c, Product_Name__c, Discount_Type__c, SP_Product__r.Competitive_Pricing_Status__c,Discountable__c,Type__c
                        from Product_Pricing__c where SP_Product__r.Deal__c =: OpptyId AND SP_Product__r.Competitive_Pricing_Status__c != null Order By Name ASC]){
            ppObj.discount_Price__c = 0;
            ppObj.discounted_Price__c = 0;
            ppObj.Discount_Type__c = '';
            ppObj.SP_Discount_Percentage__c = 0;
            ProdPricingUpdateList.add(ppObj);
        }
        if(!ProdPricingUpdateList.isEmpty()){
            update ProdPricingUpdateList;                                
        }
    }
}