example/secondfile/objects/DHStatus_Private_Line__c.object
<CustomObject>
    <description>RDS-Premise Details - DHStatus-Update Deal Hash Details - DHStatus-PhysicalProvisioning-DHStatus-Private Line</description>
    <fields>
        <fullName>DHStatus_Update_Deal_Hash_Details__c</fullName>
        <formula>DHStatus_Physical_Provisioning__r.DHStatus_Update_Deal_Hash_Details__r.Id</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>DHStatus-Update Deal Hash Details</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Design__c</fullName>
        <description>RDS-Premise Details - DHStatus-Update Deal Hash Details - DHStatus-PhysicalProvisioning-DHStatus-Private Line-Design</description>
        <label>Design</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>DHStatus-Private Line</label>
    <nameField>
        <displayFormat>PL-{0000}</displayFormat>
        <label>DHStatus-Private Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DHStatus-Private Line</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

example/secondfile/objects/DHStatus_Update_Deal_Hash_Details__c.object
<CustomObject>
    <fields>
        <fullName>Circuit_Facility_Assignment_TimeReceived__c</fullName>
        <label>Circuit Facility Assignment Received?</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>DHStatus-Update Deal Hash Details</label>
    <nameField>
        <displayFormat>DHS-{0000}</displayFormat>
        <label>DHStatus-RDS Update Deal Hash Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DHStatus-Update Deal Hash Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

example/secondfile/objects/DHStatus_Update_IDH__c.object
<CustomObject>
    <fields>
        <fullName>Circuit_Facility_Assignment_TimeReceived__c</fullName>
        <label>Circuit Facility Assignment Received?</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DHStatus_Update_Deal_Hash_Details__c</fullName>
        <label>DHStatus-Update Deal Hash Details</label>
        <referenceTo>DHStatus_Update_Deal_Hash_Details__c</referenceTo>
        <relationshipLabel>DHStatus – Update IDHs</relationshipLabel>
        <relationshipName>DHStatus_Update_IDHs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>DHStatus – Update IDH</label>
    <nameField>
        <displayFormat>DH-IDH-{000000}</displayFormat>
        <label>DHStatus – Update IDH  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DHStatus – Update IDHs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

example/secondfile/classes/API_PrivateLineTriggerHandler.cls
public with sharing Class API_PrivateLineTriggerHandler extends SITriggerOperations.SITriggerImpl{
    /*public override boolean onBeforeInsert (SObject[] newObjects)
    {
    }*/
    public override boolean onAfterInsert (SObject[] newObjects)
    {   try{
            populateFacilityInEffectDate(newObjects);
        }
        catch (exception e)
        {
            e.getMessage();        
        } 
         return true; 
    }
    public override boolean onAfterUpdate(SObject[] oldObjects, SObject[] newObjects, Map<Id, SObject>  newObjectsMap)
    {
         try{
                populateFacilityInEffectDate(newObjects);
               }        
            catch (exception e){ 
                   e.getMessage();        
             }
            return true;    
    }
       public override boolean onAfterDelete(SObject[] oldObjects, Map<Id, SObject>  oldObjectsMap){        
         try{ 
             clearInEffectDate(oldObjects);
            }        
         catch (exception e){
                e.getMessage();        
          } 
         return true;    
      } 
    public void populateFacilityInEffectDate(SObject[] newObjects){
    
    List<DHStatus_Private_Line__c> listOfnewPrivateLine = newObjects;
    Map<Id,DHStatus_Private_Line__c> mapOfIdAndPrivateLine = new Map<Id,DHStatus_Private_Line__c>();
    List<DHStatus_Update_IDH__c> dhStatusList = new List<DHStatus_Update_IDH__c>();
    List<DHStatus_Update_IDH__c> dhStatusListToUpdate = new List<DHStatus_Update_IDH__c>();
    
    
        for(DHStatus_Private_Line__c privateline :listOfnewPrivateLine)
        {
            mapOfIdAndPrivateLine.put(privateline.DHStatus_Update_Deal_Hash_Details__c,privateline);
        }
        
        if((mapOfIdAndPrivateLine!= null)|| (!mapOfIdAndPrivateLine.isEmpty())){
            for(DHStatus_Update_IDH__c dhs :[select id,Circuit_Facility_Assignment_TimeReceived__c, DHStatus_Update_Deal_Hash_Details__c from DHStatus_Update_IDH__c where id in :mapOfIdAndPrivateLine.keySet()])
            {
                if(mapOfIdAndPrivateLine.get(dhs.DHStatus_Update_Deal_Hash_Details__c).Design__c!=null)
                {
                        dhs.Circuit_Facility_Assignment_TimeReceived__c = 'Yes';
                        dhStatusListToUpdate.add(dhs);
                }
                else{                
                        dhs.Circuit_Facility_Assignment_TimeReceived__c = 'No';
                        dhStatusListToUpdate.add(dhs);       
                    }
            }
        }
       
        
        if(dhStatusListToUpdate.size()>0){
            try{
                update dhStatusListToUpdate;
            }Catch(DMLException e){
                e.getMessage();
            }
        
        }
        
        }
        public void clearInEffectDate(SObject[] oldObjects){
        List<DHStatus_Private_Line__c> listOfnewPrivateLine = oldObjects;
        Map<Id,DHStatus_Private_Line__c> mapOfIdAndPrivateLine = new Map<Id,DHStatus_Private_Line__c>();
        List<DHStatus_Update_IDH__c> dhStatusList = new List<DHStatus_Update_IDH__c>();
        List<DHStatus_Update_IDH__c> dhStatusListToUpdate = new List<DHStatus_Update_IDH__c>();
    
    
        for(DHStatus_Private_Line__c privateline :listOfnewPrivateLine)
        {
            mapOfIdAndPrivateLine.put(privateline.DHStatus_Update_Deal_Hash_Details__c,privateline);
        }
        
        if((mapOfIdAndPrivateLine!= null)|| (!mapOfIdAndPrivateLine.isEmpty())){
            for(DHStatus_Update_IDH__c dhs :[select id,Circuit_Facility_Assignment_TimeReceived__c from DHStatus_Update_IDH__c where id in :mapOfIdAndPrivateLine.keySet()])
            {
                dhs.Circuit_Facility_Assignment_TimeReceived__c = '';
                dhStatusListToUpdate.add(dhs);                
            }
        }
       
        
        if(dhStatusListToUpdate.size()>0){
            try{
                update dhStatusListToUpdate;
            }Catch(DMLException e){
                e.getMessage();
            }
        
        }
        
        
        }
    }