example/secondfile/objects/DHStatus_Billing_Update_Details__c.object
<CustomObject>
    <description>RDS-Premise Details - DHStatus-Update Deal Hash Details - DHStatus-Billing Update Details</description>
    <fields>
        <fullName>Access_Billing_Details__c</fullName>
        <description>RDS-Premise Details - DHStatus-Update Deal Hash Details - DHStatus-Billing Update Details-Circuit Billing Details-Access Billing Details</description>
        <label>Access Billing Effective Date</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Competitive_Access_DiscountEffectiveDate__c</fullName>
        <description>RDS-Premise Details - DHStatus-Update Deal Hash Details - DHStatus-Billing Update Details-Circuit Billing Details-Competitive Access DiscountEffectiveDate</description>
        <label>Competitive Access Discount Effective Dt</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DHStatusUpdateDealHashDetailsID__c</fullName>
        <formula>DHStatus_Update_IDH__r.DHStatus_Update_Deal_Hash_Details__r.Id</formula>
        <label>DHStatusUpdateDealHashDetailsID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DHStatusUpdateDealHashPremiseNumber__c</fullName>
        <formula>DHStatus_Update_IDH__r.DHStatus_Update_Deal_Hash_Details__r.RDS_Premise_Details_For_DHStatus__r.Premise_Number__c</formula>
        <label>DHStatusUpdateDealHashPremiseNumber</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DHStatus_IDH_Data_Type__c</fullName>
        <formula>DHStatus_Update_IDH__r.Data_Type__c</formula>
        <label>DHStatus IDH Data Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DHStatus_Update_Deal_Hash_Details__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>DHStatus - Update Deal Hash Details</label>
        <referenceTo>DHStatus_Update_Deal_Hash_Details__c</referenceTo>
        <relationshipLabel>DHStatus-Billing Update Details</relationshipLabel>
        <relationshipName>DHStatus_Billing_Update_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>DHStatus-Billing Update Details</label>
    <nameField>
        <displayFormat>BUD-{00000}</displayFormat>
        <label>DHStatus-Billing Update Details Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DHStatus-Billing Update Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

example/secondfile/objects/DHStatus_Update_Deal_Hash_Details__c.object
<CustomObject>
    <fields>
        <fullName>Circuit_Billing_Activation_2_EfCDate__c</fullName>
        <label>Circuit Billing Activation 2 EfC Date</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Circuit_Billing_Activation_EffectiveDate__c</fullName>
        <label>Circuit Billing Activation EffectiveDate</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Circuit_Competitive_Discounts_2_EfC_Date__c</fullName>
        <label>Circuit Competitive Discounts 2 EfC Date</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Circuit_Competitive_Discounts_EfC_Date__c</fullName>
        <label>Circuit Competitive Discounts EfC Date</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Premise_Number__c</fullName>
        <label>Premise Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>DHStatus-Update Deal Hash Details</label>
    <nameField>
        <displayFormat>DHS-{0000}</displayFormat>
        <label>DHStatus-RDS Update Deal Hash Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DHStatus-Update Deal Hash Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

example/secondfile/classes/API_DHStatusBillingDetailsHandler.cls
/* Component Name :API_DHStatusBillingUpdateDetailsHandler   
Requirement/User Story Number : Provisioning Milestone Report      
Requirement Description:Update DHStatus-Update Deal Hash Details Fields
Component Author:Accenture IDC     
Created Date: 25th november 2014      
Version:1.0     
*/   
 
public with sharing class API_DHStatusBillingDetailsHandler extends SITriggerOperations.SITriggerImpl{

public override boolean onAfterInsert(SObject[] newObjects){        
         try{ 
            UpdateDHStatusUpdateDealHashDetailsFields(newObjects);
            }        
         catch (exception e){
                e.getMessage();        
          } 
         return true;    
      } 
      
public override boolean onAfterUpdate(SObject[] oldObjects, SObject[] newObjects, Map<Id, SObject>  newObjectsMap){
            try{
              
               }        
            catch (exception e){ 
                   e.getMessage();        
             }
            return true;    
      } 
    public override boolean onBeforeDelete(SObject[] oldObjects, Map<Id, SObject>  oldObjectsMap){        
         try{ 
             //ClearDHStatusUpdateDealHashFields(oldObjects);
            }        
         catch (exception e){
                e.getMessage();        
          } 
         return true;    
      }
          
      
      public override boolean onAfterDelete(SObject[] oldObjects, Map<Id, SObject>  oldObjectsMap){        
         try{ 
             ClearDHStatusUpdateDealHashFields(oldObjects);
            }        
         catch (exception e){
                e.getMessage();        
          } 
         return true;    
      }
//populating Circuit Billing Activation EffectiveDate,Circuit Competitive Discounts EfC Date on DHStatus-Update Deal Hash Details from DHStatus-Status Update Details  
public void UpdateDHStatusUpdateDealHashDetailsFields(SObject[] newObjects)
{
        List<DHStatus_Billing_Update_Details__c> DHStatusLPList=newObjects;
        Set<String> DHStatusUDHDIDSet=new Set<String>();
        Set<String> DHStatusUDHDPremiseNumberSet=new Set<String>();
        List<DHStatus_Update_Deal_Hash_Details__c> DHStatusUDHDList=new List<DHStatus_Update_Deal_Hash_Details__c>();        
        Map<Id,DHStatus_Update_Deal_Hash_Details__c> DHStatusUDHDMap=new Map<Id,DHStatus_Update_Deal_Hash_Details__c>();
        for(DHStatus_Billing_Update_Details__c bup:DHStatusLPList)
        {
           
                DHStatusUDHDIDSet.add(bup.DHStatusUpdateDealHashDetailsID__c);
                DHStatusUDHDPremiseNumberSet.add(bup.DHStatusUpdateDealHashPremiseNumber__c);
                
        }
                        
        if(DHStatusUDHDIDSet.size()>0 && DHStatusUDHDPremiseNumberSet.size()>0)
        {
            DHStatusUDHDList=[select Id,Premise_Number__c,Circuit_Billing_Activation_EffectiveDate__c,Circuit_Competitive_Discounts_EfC_Date__c from DHStatus_Update_Deal_Hash_Details__c WHERE Id IN:DHStatusUDHDIDSet AND Premise_Number__c IN:DHStatusUDHDPremiseNumberSet];
        } 
        if(DHStatusUDHDList.size()>0)
        {
            for(DHStatus_Update_Deal_Hash_Details__c udhd:DHStatusUDHDList)
            {
                for(DHStatus_Billing_Update_Details__c dhud:DHStatusLPList)
                {
                    if(udhd.Id==dhud.DHStatusUpdateDealHashDetailsID__c && udhd.Premise_Number__c==dhud.DHStatusUpdateDealHashPremiseNumber__c && dhud.DHStatus_IDH_Data_Type__c=='Port')
                        {
                          udhd.Circuit_Billing_Activation_EffectiveDate__c=dhud.Access_Billing_Details__c;
                          udhd.Circuit_Competitive_Discounts_EfC_Date__c=dhud.Competitive_Access_DiscountEffectiveDate__c;
                          DHStatusUDHDMap.put(udhd.Id,udhd);  
                        }
                    else if(udhd.Id==dhud.DHStatusUpdateDealHashDetailsID__c && udhd.Premise_Number__c==dhud.DHStatusUpdateDealHashPremiseNumber__c && dhud.DHStatus_IDH_Data_Type__c=='Billing')
                        {
                          udhd.Circuit_Billing_Activation_2_EfCDate__c=dhud.Access_Billing_Details__c; //GCS
                          udhd.Circuit_Competitive_Discounts_2_EfC_Date__c=dhud.Competitive_Access_DiscountEffectiveDate__c; //GCS
                          DHStatusUDHDMap.put(udhd.Id,udhd);                    
                        }                              
                }
            }
        }
      if(DHStatusUDHDMap.size()>0)
      {
          try
          {
          update DHStatusUDHDMap.Values();
          }
          Catch(Exception e)
          {
          }
      }         
  }  
  
  //clear Corresponding DHStatusUpdateDealHash fields after deleting the DHStatus-Status Update Details
   public void ClearDHStatusUpdateDealHashFields(SObject[] oldObjects)
     {
        List<DHStatus_Billing_Update_Details__c> DeleteDHStatusBUList=oldObjects;
        Map<String,DHStatus_Billing_Update_Details__c> DHStatusBUMap=new  Map<String,DHStatus_Billing_Update_Details__c>();
        Map<Id,DHStatus_Update_Deal_Hash_Details__c> DHStatusUDHDMap=new Map<Id,DHStatus_Update_Deal_Hash_Details__c>();
        
            for(DHStatus_Billing_Update_Details__c dbu:DeleteDHStatusBUList)
            {
                DHStatusBUMap.put(dbu.DHStatusUpdateDealHashDetailsID__c,dbu);
                system.debug('--@@--'+DHStatusBUMap);
            }          
            if(DHStatusBUMap!=NULL || !DHStatusBUMap.isEmpty())
            {
                for(DHStatus_Update_Deal_Hash_Details__c udhd:[select Id,Premise_Number__c,Circuit_Billing_Activation_EffectiveDate__c,Circuit_Competitive_Discounts_EfC_Date__c, Circuit_Billing_Activation_2_EfCDate__c, Circuit_Competitive_Discounts_2_EfC_Date__c from DHStatus_Update_Deal_Hash_Details__c WHERE Id IN:DHStatusBUMap.keySet()])
                {
                    udhd.Circuit_Billing_Activation_EffectiveDate__c=NULL;
                    udhd.Circuit_Competitive_Discounts_EfC_Date__c=NULL;
                    udhd.Circuit_Billing_Activation_2_EfCDate__c=NULL; //GCS
                    udhd.Circuit_Competitive_Discounts_2_EfC_Date__c=NULL; //GCS
                    DHStatusUDHDMap.put(udhd.Id,udhd);
                }
            }
           if(DHStatusUDHDMap.size()>0)
           {
               try
               {
                   update DHStatusUDHDMap.values();
               }
               Catch(Exception e)
               {
               }
           }                            
      }            
}