example/secondfile/objects/DHStatus_Access_Test_Status_Details__c.object
<CustomObject>
    <description>RDS-Deal Hash-Update Deal Hash Details- ASR Details- Access Test Status Details</description>
    <fields>
        <fullName>DHStatus_Update_Deal_Hash_Details__c</fullName>
        <formula>CASESAFEID(DHStatus_ASR_Details__r.DHStatus_Update_IDH__r.Id)</formula>
        <label>DHStatus-Update Deal Hash Details</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Record_Type__c</fullName>
        <description>RDS-Deal Hash-Update Deal Hash Details- ASR Details- Access Test Status Details-Record Type</description>
        <label>Record Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>DHStatus-Access Test Status Details</label>
    <nameField>
        <displayFormat>AT-{0000}</displayFormat>
        <label>DHStatus-Access Test Status Details Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DHStatus-Access Test Status Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

example/secondfile/objects/DHStatus_Completion_Details__c.object
<CustomObject>
    <description>RDS-Deal Hash-Update Deal Hash Details- ASR Details-Access Test Status Details-Message Details-DHStatus- Completion Details</description>
    <fields>
        <fullName>DHStatus_Update_Deal_Hash_Details__c</fullName>
        <formula>CASESAFEID( DHStatus_Message_Details__r.DHStatus_Access_Test_Status_Details__r.DHStatus_ASR_Details__r.DHStatus_Update_IDH__r.Id)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>DHStatus Update Deal Hash Details</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Provider_Circuit_ID__c</fullName>
        <description>RDS-Deal Hash-Update Deal Hash Details-ASR Details-Access Test Status Details-Message Details-Completion Details-Provider Circuit ID</description>
        <label>Provider Circuit ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Record_Type__c</fullName>
        <formula>DHStatus_Message_Details__r.DHStatus_Access_Test_Status_Details__r.Record_Type__c</formula>
        <label>Record Type</label>
        <type>Text</type>
    </fields>
    <label>DHStatus-Completion Details</label>
    <nameField>
        <displayFormat>CD-{00000}</displayFormat>
        <label>DHStatus-Completion Details Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DHStatus-Completion Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

example/secondfile/objects/DHStatus_Update_Deal_Hash_Details__c.object
<CustomObject>
    <label>DHStatus-Update Deal Hash Details</label>
    <nameField>
        <displayFormat>DHS-{0000}</displayFormat>
        <label>DHStatus-RDS Update Deal Hash Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DHStatus-Update Deal Hash Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

example/secondfile/objects/DHStatus_Update_IDH__c.object
<CustomObject>
    <fields>
        <fullName>DHStatus_Update_Deal_Hash_Details__c</fullName>
        <label>DHStatus-Update Deal Hash Details</label>
        <referenceTo>DHStatus_Update_Deal_Hash_Details__c</referenceTo>
        <relationshipLabel>DHStatus – Update IDHs</relationshipLabel>
        <relationshipName>DHStatus_Update_IDHs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Data_Type__c</fullName>
        <label>Data Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LEC_Circuit_ID__c</fullName>
        <label>LEC Circuit ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>DHStatus – Update IDH</label>
    <nameField>
        <displayFormat>DH-IDH-{000000}</displayFormat>
        <label>DHStatus – Update IDH  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DHStatus – Update IDHs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

secondfile/classes/API_DHStatusCompletionDetailsHandler.cls
/* Component Name :API_DHStatusEthernetTriggerHandler      
Requirement/User Story Number : US311424      
Requirement Description:Update Field(Facility in Effect Date) on DHStatus-Update Deal Hash Details Object from DHStatus-Ethernet object
Component Author:Accenture IDC     
Created Date: 1st September 2014      
Version:1.0     
*/   
 
public with sharing class API_DHStatusCompletionDetailsHandler extends SITriggerOperations.SITriggerImpl{
    public override boolean onAfterInsert (SObject[] newObjects){        
         try{ 
            //String event = 'insert';
            //updateLECcircuitId(newObjects,event); 
            UpdateDHStatusIDHFields(newObjects);
            }        
         catch (exception e){
                e.getMessage();        
          } 
         return true;    
      } 
      
    /* public override boolean onAfterUpdate(SObject[] oldObjects, SObject[] newObjects, Map<Id, SObject>  newObjectsMap){
            try{
                //updateProvisioningDates(newObjects);
               }        
            catch (exception e){ 
                   e.getMessage();        
             }
            return true;    
      }*/
      
     public override boolean onAfterDelete(SObject[] oldObjects, Map<Id, SObject>  oldObjectsMap){        
         try{ 
            //String event = 'delete';
            //updateLECcircuitId(oldObjects,event); 
            clearDHStatusIDHFields(oldObjects);
            }        
         catch (exception e){
                e.getMessage();        
          } 
         return true;    
      }  
     /*public void updateLECcircuitId(SObject[] newObjects,String event){
     List<DHStatus_Completion_Details__c> newCompList = newObjects;
     Map<Id,DHStatus_Completion_Details__c> compMap = new Map<Id,DHStatus_Completion_Details__c> (); 
     List<DHStatus_Update_IDH__c> idhList= new List<DHStatus_Update_IDH__c>(); 
     List<DHStatus_Update_IDH__c> idhListToUpdate= new List<DHStatus_Update_IDH__c>();
     List<DHStatus_Access_Test_Status_Details__c> accessList = new List<DHStatus_Access_Test_Status_Details__c>(); 
     //List<DHStatus_Completion_Details__c> listOfCompletion = new List<DHStatus_Completion_Details__c>();
     Set<Id> setofIdh = new Set<Id>();
         for(DHStatus_Completion_Details__c comp :newCompList){
             if(comp.Provider_Circuit_ID__c!=null){
                 compMap.put(comp.DHStatus_Update_Deal_Hash_Details__c,comp);    
             }        
         }
         if(compMap!=null || !compMap.isEmpty()){
             idhList = [Select id,LEC_Circuit_ID__c,Data_Type__c from DHStatus_Update_IDH__c where id in:compMap.keySet()];
             system.debug('idhList ....'+idhList );
             if(idhList.size()>0){
                 for(DHStatus_Update_IDH__c idh:idhList){
                 setofIdh.add(idh.id);
                 }
                 system.debug('setofIdh....'+setofIdh);
             }
             accessList = [Select id,Record_Type__c,DHStatus_Update_Deal_Hash_Details__c from DHStatus_Access_Test_Status_Details__c where DHStatus_Update_Deal_Hash_Details__c in: setofIdh and Record_Type__c = 'C'];
         }
         system.debug('accesslist....'+accessList);
         if(accessList.size()>0){
             for(DHStatus_Update_IDH__c idh:idhList){
                 for(DHStatus_Access_Test_Status_Details__c acc:accessList){
                     for(DHStatus_Completion_Details__c com:compMap.values()){
                         if(event == 'insert'){
                             if(com.Provider_Circuit_ID__c!=null && acc.DHStatus_Update_Deal_Hash_Details__c == com.DHStatus_Update_Deal_Hash_Details__c && com.DHStatus_Update_Deal_Hash_Details__c == idh.id && idh.Data_Type__c == 'Port'){
                                 system.debug('Hurrrayyyy!!');
                                 idh.LEC_Circuit_ID__c = com.Provider_Circuit_ID__c;
                                 idhListToUpdate.add(idh);
                             }
                         }
                         else if(event == 'delete'){
                             idh.LEC_Circuit_ID__c = '';
                             idhListToUpdate.add(idh);
                         }
                     }
                 }
                               
             }
                
         }
          if(idhListToUpdate.size()>0){
             try{
                 update idhListToUpdate;
             }
             catch(DMLException e){
                   e.getMessage();
             }
          }  
     }*/ 
public void UpdateDHStatusIDHFields(SObject[] newObjects)
{
    List<DHStatus_Completion_Details__c> DHStatusCDList=newObjects;
    Set<String> DHStatusIDSet=new Set<String>();
    List<DHStatus_Update_IDH__c> IDHList=new List<DHStatus_Update_IDH__c>();
    Map<Id,DHStatus_Update_IDH__c> IDHMap=new Map<Id,DHStatus_Update_IDH__c>();
    for(DHStatus_Completion_Details__c dhcd:DHStatusCDList)
    {
        if(dhcd.Provider_Circuit_ID__c!=NULL && dhcd.Record_Type__c=='C')
        {
            DHStatusIDSet.add(dhcd.DHStatus_Update_Deal_Hash_Details__c);
        }
    }
    
    if(DHStatusIDSet.size()>0)
    {
       IDHList=[select Id,LEC_Circuit_ID__c,Data_Type__c from DHStatus_Update_IDH__c WHERE Id IN:DHStatusIDSet]; 
    }
    if(IDHList.size()>0)
    {
        for(DHStatus_Update_IDH__c idh:IDHList)
        {
            for(DHStatus_Completion_Details__c cd:DHStatusCDList)
            {
                if(idh.id==cd.DHStatus_Update_Deal_Hash_Details__c && idh.Data_Type__c=='Port' && cd.Record_Type__c=='C')
                {
                    idh.LEC_Circuit_ID__c=cd.Provider_Circuit_ID__c;
                    IDHMap.put(idh.Id,idh);
                }
            }
        }
    }
    if(IDHMap.size()>0)
    {
        try
        {
            update IDHMap.values();
        }
        Catch(Exception e)
        {
        }
    }
        
} 

public void clearDHStatusIDHFields(SObject[] oldObjects)
{
    List<DHStatus_Completion_Details__c> DeleteDHStatusCDList=oldObjects;
    Map<String,DHStatus_Completion_Details__c> DHCDMap=new Map<String,DHStatus_Completion_Details__c>();
    List<DHStatus_Update_IDH__c> IDHList=new List<DHStatus_Update_IDH__c>();
    Map<Id,DHStatus_Update_IDH__c> IDHMap=new Map<Id,DHStatus_Update_IDH__c>();
    for(DHStatus_Completion_Details__c dhcd:DeleteDHStatusCDList)
    {
        DHCDMap.put(dhcd.DHStatus_Update_Deal_Hash_Details__c,dhcd);
    }
    if(DHCDMap!=NULL && !DHCDMap.isEmpty())
    {
       IDHList=[select Id,LEC_Circuit_ID__c,Data_Type__c from DHStatus_Update_IDH__c WHERE Id IN:DHCDMap.keySet() AND Data_Type__c='Port']; 
    }
    if(IDHList.size()>0)
    {
        for(DHStatus_Update_IDH__c idh:IDHList)
        {
            for(DHStatus_Completion_Details__c dc:DeleteDHStatusCDList)
            {
                if(idh.id==dc.DHStatus_Update_Deal_Hash_Details__c && idh.Data_Type__c=='Port')
                {
                    idh.LEC_Circuit_ID__c=NULL;
                    IDHMap.put(idh.Id,idh);
                }
            }
        }
    }
    if(IDHMap.size()>0)
    {
        try
        {
            update IDHMap.values();
        }
        Catch(Exception e)
        {
        }
    }
}   
}