example/secondfile/objects/End_Customer__c.object
<CustomObject>
    <label>End Customer</label>
    <nameField>
        <label>End Customer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>End Customers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

example/secondfile/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>End_Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>End Customer</label>
        <referenceTo>End_Customer__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

example/secondfile/objects/SPProduct__c.object
<CustomObject>
    <description>Contains the information of the products like AVPN,CaaS and StaaS</description>
    <fields>
        <fullName>Deal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Deal</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>SP Products</relationshipLabel>
        <relationshipName>SPProducts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>End_Customer__c</fullName>
        <formula>Deal__r.End_Customer__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>End Customer</label>
        <type>Text</type>
    </fields>
    <label>SPProduct</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>SP Product ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SP Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

secondfile/classes/SIHeatMapController.cls
//A HeapMap Controller
public class SIHeatMapController {
    
    public String accountName {get; set;}
    public String endCustomerName {get; set;}

    public String searchType {get; set;}
    public String searchResStr {get; set;}
    
    public boolean isSearResDisplay {get; set;}
    public boolean isHeatMapDisplay {get; set;}
    public boolean isErrorDisplay {get; set;}
    
    public String headerDisplayStr {get; set;}
    public String heatMapObjId {get; set;}
    
    public Map<Id, SPProduct__c> heatResMap {get; set;}
    
    public String accountId {get; set;}
    public String objectTypeName {get; set;}
    
    public List<SIHeatMapUtility.SIHeatMapDto> persistedHeatMapList {get; set;}
    
    public List<SIHeatMapProduct> heatMapProducts {get; set;}
    public boolean isProductSelectAll {get; set;}
    
    //public ApexPages.StandardSetController con{get;set;} //For pagination
      
    //default cons
    public SIHeatMapController() {
        heatResMap = new Map<Id, SPProduct__c>();
        heatMapObjId = '';
        endCustomerName = '';
        accountName = '';
        isErrorDisplay = false;
        persistedHeatMapList = new List<SIHeatMapUtility.SIHeatMapDto>();
        heatMapProducts = SIHelper.getProducts();
    }
    
    //params cons
    public SIHeatMapController(String accountId) {
        this.accountId = accountId;
    }
    
    //To get search results
    public PageReference getSearchResults() {
        isSearResDisplay = false;
        isHeatMapDisplay = false;
        isErrorDisplay = false;
        heatResMap = new Map<Id, SPProduct__c>();
        heatMapObjId = '';

        headerDisplayStr = searchType.equalsIgnoreCase('account') ? 'SP Account' : 'End Customer';      
        searchResStr = searchType.equalsIgnoreCase('account') ? 'Account Search Results' : 'End Customers Search Results';
        
        if(null != searchType && searchType.length() > 0) {
            if(searchType.equalsIgnoreCase('account')) {
                if(null != accountName && accountName.length() > 0) {
                    heatResMap = SIHelper.fetchHeatMapRes('account', accountName, endCustomerName);
                    
                    
                }
            }
            if(searchType.equalsIgnoreCase('endCustomer')) {
                if(null != endCustomerName && endCustomerName.length() > 0) {
                    heatResMap = SIHelper.fetchHeatMapRes('endCustomer', accountName, endCustomerName);
                    
                }
            }
        }        
        if(heatResMap.size() > 0) {
            isSearResDisplay = true;
        } else {
                isErrorDisplay = true;
        }
              
        System.debug('Value :'+isProductSelectAll);
        return null;
    }
    
    //method used to cancel the searchResults
    public PageReference doCancelSearchAndSearchRes() {
        heatResMap = new Map<Id, SPProduct__c>();
        endCustomerName = '';
        accountName = '';
        isSearResDisplay = false;
        isErrorDisplay = false;
        return null;
    }
    
    //Generate a Heat Map
    public PageReference doHeatMap() {
        persistedHeatMapList = new List<SIHeatMapUtility.SIHeatMapDto>();
        System.debug('HeatMapObj :'+heatMapObjId);
        isHeatMapDisplay = false;
        
        if(searchType.equalsIgnoreCase('account')) {
            persistedHeatMapList = fetchSPAccountsHeatMap(heatMapObjId);

        } else {
            persistedHeatMapList = new SIHeatMapUtility(heatMapObjId).persistedHeatMapList;        
        }

        if(persistedHeatMapList !=null && !persistedHeatMapList.isEmpty()) {
            isHeatMapDisplay = true;
            if((null != accountName && accountName.length() > 0) && 
                (null != endCustomerName && endCustomerName.length() > 0)) {
                persistedHeatMapList = SIHelper.getInstance().
                        modifyPersistedHeatMapList(accountName, endCustomerName, persistedHeatMapList);
                System.debug('Both Criteria :'+persistedHeatMapList.size());
            }
        }
        
        return null;
    }
 
    //Method used to get the heatmap list related to the sp accounts
    public List<SIHeatMapUtility.SIHeatMapDto> fetchSPAccountsHeatMap(String accountId) {
        List<SIHeatMapUtility.SIHeatMapDto> heatMapList = new List<SIHeatMapUtility.SIHeatMapDto>();
        Set<String> accountStrSet = new Set<String>();
        SIHelper helperObj = SIHelper.getInstance();
        
        try {
            List<SPProduct__c> productList = [
                Select deal__r.Name, deal__r.End_Customer__r.Name,deal__r.StageName,deal__r.Account.Id,
                deal__r.End_Customer__r.Id,deal__r.Account.Name, RecordType.Name,CreatedDate from SPProduct__c 
                Where deal__r.Account.Id = :accountId order by CreatedDate Asc, 
                deal__r.Account.Name,RecordType.Name
            ];
            
            for(SPProduct__c productObj : productList) {
                accountStrSet.add(productObj.deal__r.Account.Id +'~'+productObj.deal__r.End_Customer__r.Name 
                        +'~'+productObj.deal__r.End_Customer__r.Id);
            }
                        
            heatMapList = helperObj.fetchSPAccountsHeatMap(accountStrSet);
        } catch(Exception excep) {
            System.debug('Exception Caught fetchSPAccountsHeatMap :'+excep.getMessage()); 
        }
        return heatMapList;
    }
    
    //An inner class to handle the product search
    public class SIHeatMapProduct {
        public Integer productCounter {get; set;}
        public String productName {get; set;}
        public boolean isSelected {get; set;}
        
        /*public SIHeatMapProduct() {
            productCounter = 0;
            productName = '';
            isSelected = false;
        }*/
        
        public SIHeatMapProduct(Integer productCounter, String productName, boolean isSelected) {
            this.productCounter = productCounter;
            this.productName = productName;
            this.isSelected = isSelected;
        }
        
        override
        public String toString() {
            return productCounter +'|'+ productName +'|'+isSelected;
        }
    }
}