example/secondfile/objects/End_User_Support_Ticket__c.object
<CustomObject>
    <fields>
        <fullName>End_User_Support_Ticket__c</fullName>
        <displayFormat>EU-{0000}</displayFormat>
        <label>End User Support Ticket #</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>Error_Message_Received__c</fullName>
        <label>Error Message Received</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>IT_Support_Ticket__c</fullName>
        <label>IT Support Ticket #</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Impact__c</fullName>
        <label>Impact</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Logged_Date_Time__c</fullName>
        <label>Logged Date\Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Related_To__c</fullName>
        <label>Related To</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Accounts</fullName>
                </value>
                <value>
                    <fullName>Contacts</fullName>
                </value>
                <value>
                    <fullName>Credit Validations</fullName>
                </value>
                <value>
                    <fullName>Data Access</fullName>
                </value>
                <value>
                    <fullName>Data Mismatch with ROME</fullName>
                </value>
                <value>
                    <fullName>Data Mismatch with BID</fullName>
                </value>
                <value>
                    <fullName>Enhancement</fullName>
                </value>
                <value>
                    <fullName>General Field Update</fullName>
                </value>
                <value>
                    <fullName>General Process Flow</fullName>
                </value>
                <value>
                    <fullName>Deal Registration Approval</fullName>
                </value>
                <value>
                    <fullName>Lead Conversion</fullName>
                </value>
                <value>
                    <fullName>Opportunities</fullName>
                </value>
                <value>
                    <fullName>SI/VAR-API</fullName>
                </value>
                <value>
                    <fullName>Sign on</fullName>
                </value>
                <value>
                    <fullName>Special Pricing Approval</fullName>
                </value>
                <value>
                    <fullName>SP Products</fullName>
                </value>
                <value>
                    <fullName>User Creation/Deletion</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>On/Off cart deals</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Screen__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Screenshot Included?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Severity__c</fullName>
        <label>Severity</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1 - Critical</fullName>
                </value>
                <value>
                    <fullName>2 - High</fullName>
                </value>
                <value>
                    <fullName>3 - Medium</fullName>
                </value>
                <value>
                    <fullName>4 - Low</fullName>
                    <default>true</default>
                    <label>4 - Low</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>When a request is in an &quot;AT&amp;T&quot; status, it is being handled by the AT&amp;T Triage team. If a request is in an &quot;IT&quot; status, it is assigned to the IT Support team.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open (AT&amp;T)</fullName>
                    <default>true</default>
                    <label>Open (AT&amp;T)</label>
                </value>
                <value>
                    <fullName>In Progress (AT&amp;T)</fullName>
                </value>
                <value>
                    <fullName>Closed (AT&amp;T)</fullName>
                </value>
                <value>
                    <fullName>Open (IT)</fullName>
                </value>
                <value>
                    <fullName>In Progress (IT)</fullName>
                </value>
                <value>
                    <fullName>Closed (IT)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Steps_to_Reproduce_Error__c</fullName>
        <label>Steps to Reproduce Error</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <label>Subject</label>
        <length>175</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ticket_Type__c</fullName>
        <label>Ticket Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Bulk Upload Request</fullName>
                </value>
                <value>
                    <fullName>Enhancement</fullName>
                </value>
                <value>
                    <fullName>Defect</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>End User Support Ticket</label>
    <nameField>
        <label>End User Support Ticket Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>End User Support Tickets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

secondfile/objects/IT_Support_Ticket__c.object
<CustomObject>
    <description>Used to open IT Support Tickets for ATT Maintenance projects.</description>
    <fields>
        <fullName>Added_Screenshot_as_Note_Attachment__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Will you be able to add a Screenshot of your issue as an Attachment?</inlineHelpText>
        <label>Screenshot Included?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>End_User_Support_Ticket__c</fullName>
        <label>End User Support Ticket#</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Error_Message_Received__c</fullName>
        <inlineHelpText>If you see an error message for your issue, please copy/paste here.</inlineHelpText>
        <label>Error Message Received</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Impact__c</fullName>
        <label>Impact</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Logged_Date_Time__c</fullName>
        <label>Logged Date/Time</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Related_to__c</fullName>
        <label>Related to</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Accounts</fullName>
                </value>
                <value>
                    <fullName>Contacts</fullName>
                </value>
                <value>
                    <fullName>Credit Validations</fullName>
                </value>
                <value>
                    <fullName>Data Access</fullName>
                </value>
                <value>
                    <fullName>Data Mismatch with BID</fullName>
                </value>
                <value>
                    <fullName>Data Mismatch with ROME</fullName>
                </value>
                <value>
                    <fullName>Deal Registration Approval</fullName>
                </value>
                <value>
                    <fullName>Email</fullName>
                </value>
                <value>
                    <fullName>Enhancement</fullName>
                </value>
                <value>
                    <fullName>Force Portal</fullName>
                    <default>true</default>
                    <label>Force Portal</label>
                </value>
                <value>
                    <fullName>General Field Update</fullName>
                </value>
                <value>
                    <fullName>General Process Flow</fullName>
                </value>
                <value>
                    <fullName>Lead Conversion</fullName>
                </value>
                <value>
                    <fullName>On/Off cart deals</fullName>
                </value>
                <value>
                    <fullName>Opportunities</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>SI/VAR-API</fullName>
                </value>
                <value>
                    <fullName>Sign on</fullName>
                </value>
                <value>
                    <fullName>Special Pricing Approval</fullName>
                </value>
                <value>
                    <fullName>SP Products</fullName>
                </value>
                <value>
                    <fullName>User Creation/Deletion</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Severity__c</fullName>
        <label>Severity</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1- Critical</fullName>
                </value>
                <value>
                    <fullName>2 - High</fullName>
                </value>
                <value>
                    <fullName>3 - Medium</fullName>
                    <default>true</default>
                    <label>3 - Medium</label>
                </value>
                <value>
                    <fullName>4 - Low</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>On Hold - Client Input/Verification Needed</fullName>
                </value>
                <value>
                    <fullName>On Hold - Referred to External Application</fullName>
                </value>
                <value>
                    <fullName>On Hold - Targeted for Maintenance Release</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Deferred(CR)</fullName>
                </value>
                <value>
                    <fullName>Not an Issue</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Steps_to_Reproduce_Error__c</fullName>
        <inlineHelpText>Enter step by step instructions for how the error was produced</inlineHelpText>
        <label>Steps to Reproduce Error</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Ticket_Subject__c</fullName>
        <label>Subject</label>
        <length>175</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>IT Support Ticket</label>
    <nameField>
        <displayFormat>ITS-{000000}</displayFormat>
        <label>IT Support Ticket #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>IT Support Tickets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

example/secondfile/classes/EUTktTriggerHandler.cls
/* 
 Name: EUTktTriggerHandle r
 Type: Class 
 
 Description: 
 */ 
public with sharing class  EUTktTriggerHandler extends SITriggerOperations.SITriggerImpl{
    public boolean isExecuted ;

    // Default Constructor
/* 
 Name: EUTktTriggerHandler
 Description: 
 */ 
    public EUTktTriggerHandler (){
        isExecuted = true;
    }

    //An Overridden method for AfterInsert
/* 
 Name: onAfterInsert
 Description: 
 */ 
    public override boolean onAfterInsert(SObject[] newObjects) {
        try {
            createITSupportTkt(newObjects);
        } catch(Exception excep) {
            isExecuted = false;
            throw excep;
        }
        return isExecuted;
    }   

    //An Overridden method for AfterUpdate
/* 
 Name: onAfterUpdate
 Description: 
 */ 
    public override boolean onAfterUpdate(SObject[] oldObjects, SObject[] updatedObjects, Map<Id, SObject>  newObjectsMap) {
        try {
            createITSupportTkt(updatedObjects);
        } catch(Exception excep) {
            isExecuted = false;
            throw excep;
        }
        return isExecuted;
    }

    /* method to create IT Support ticket*/
    private void createITSupportTkt(SObject[] newObjects){
        End_User_Support_Ticket__c euTkt = null;
        List<End_User_Support_Ticket__c> euList= new List<End_User_Support_Ticket__c>();
        List<IT_Support_Ticket__c> itSupportTktList = new List<IT_Support_Ticket__c>();

        try{
            for(SObject s:newObjects){
                euTkt = (End_User_Support_Ticket__c)s;
                if((euTkt.Ticket_Type__c == UtilityConstant.BULKUPLOAD_REQUEST || euTkt.Ticket_Type__c == UtilityConstant.DEFECT) && (euTkt.IT_Support_Ticket__c == null ||euTkt.IT_Support_Ticket__c == SpecialCharacterConstant.CONCAT)){
                    itSupportTktList.add(generateITTicket(euTkt));
                }
                else if(euTkt.Ticket_Type__c == UtilityConstant.ENHANCEMENT && euTkt.Status__c == UtilityConstant.OPEN_IT_x && (euTkt.IT_Support_Ticket__c == null ||euTkt.IT_Support_Ticket__c == SpecialCharacterConstant.CONCAT)){
                //else if(euTkt.Ticket_Type__c == UtilityConstant.ENHANCEMENT && euTkt.Status__c == UtilityConstant.OPEN_IT_x){
                    itSupportTktList.add(generateITTicket(euTkt));
                }
            }
            if(!itSupportTktList.isEmpty()){
                insert itSupportTktList;
            }
        }catch(Exception e){
            ATTException.logException( e.getTypeName(), ATTException.constructExceptionMessageString(e));
        }
    }

    /* This method will take End user ticket recrod as input and returns IT support ticket*/
    private IT_Support_Ticket__c generateITTicket(End_User_Support_Ticket__c euTkt){
        IT_Support_Ticket__c itSupportTkt = new IT_Support_Ticket__c();
        try{
            itSupportTkt.End_User_Support_Ticket__c = euTkt.name;
            itSupportTkt.Error_Message_Received__c = euTkt.Error_Message_Received__c;
            itSupportTkt.Impact__c = euTkt.Impact__c;
            itSupportTkt.Related_to__c = euTkt.Related_To__c;
            itSupportTkt.Severity__c = euTkt.Severity__c;
            itSupportTkt.Steps_to_Reproduce_Error__c = euTkt.Steps_to_Reproduce_Error__c;
            itSupportTkt.Ticket_Subject__c = euTkt.Subject__c;
            itSupportTkt.End_User_Support_Ticket__c = euTkt.End_User_Support_Ticket__c;
            itSupportTkt.Added_Screenshot_as_Note_Attachment__c = euTkt.Screen__c;
            itSupportTkt.Logged_Date_Time__c = system.now();
        }catch(Exception e){
            ATTException.logException( e.getTypeName(), ATTException.constructExceptionMessageString(e));
        }
        return itSupportTkt;
    }
}