example/secondfile/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Account_Name__c</fullName>
        <formula>Account.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Deal_Reg_Approval_Date__c</fullName>
        <label>Deal Reg Approval Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Deal_Reg_Discount_Percentage__c</fullName>
        <formula>Custom_Deal_Reg_Percentage__c</formula>
        <label>Deal Reg Discount Percentage</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>EndCustomerCity__c</fullName>
        <formula>End_Customer__r.City__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>EndCustomerCity</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EndCustomerName__c</fullName>
        <formula>End_Customer__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>EndCustomerName</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EndCustomerState__c</fullName>
        <formula>End_Customer__r.State__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>EndCustomerState</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EndCustomerZip__c</fullName>
        <formula>End_Customer__r.Zip__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>EndCustomerZip</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>End_Cust_Address__c</fullName>
        <formula>TRIM(End_Customer__r.Mailing_Street_Address__c)+ TRIM(End_Customer__r.City__c)+ TRIM(End_Customer__r.State__c)+ TRIM(End_Customer__r.Zip__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>End Cust Address</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>End_Customer_Address__c</fullName>
        <formula>End_Customer__r.Mailing_Street_Address__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>End Customer Address</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>End_Customer_Name__c</fullName>
        <formula>LOWER(TRIM(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(End_Customer__r.Name, &quot;?&quot;, &quot;&quot;), &quot;/&quot;, &quot;&quot;), &quot;.&quot;, &quot;&quot;), &quot;,&quot;, &quot;&quot;), &quot;;&quot;, &quot;&quot;), &quot;:&quot;, &quot;&quot;), &quot; &quot;, &quot;&quot;), &quot;{&quot;, &quot;&quot;), &quot;}&quot;, &quot;&quot;), &quot;[&quot;, &quot;&quot;), &quot;]&quot;, &quot;&quot;), &quot;&apos;&quot;, &quot;&quot;), &quot;=&quot;, &quot;&quot;), &quot;-&quot;, &quot;&quot;), &quot;=&quot;, &quot;&quot;), &quot;^&quot;, &quot;&quot;), &quot;&amp;&quot;, &quot;&quot;), &quot;*&quot;, &quot;&quot;), &quot;(&quot;, &quot;&quot;), &quot;)&quot;, &quot;&quot;), &quot;_&quot;, &quot;+&quot;), &quot;#&quot;, &quot;&quot;), &quot;!&quot;, &quot;&quot;), &quot;`&quot;, &quot;&quot;), &quot;@&quot;, &quot;&quot;), &quot;$&quot;, &quot;&quot;), &quot;%&quot;, &quot;&quot;), &quot;1&quot;, &quot;&quot;), &quot;2&quot;, &quot;&quot;), &quot;3&quot;, &quot;&quot;), &quot;4&quot;, &quot;&quot;), &quot;5&quot;, &quot;&quot;), &quot;6&quot;, &quot;&quot;), &quot;7&quot;, &quot;&quot;), &quot;8&quot;, &quot;&quot;), &quot;9&quot;, &quot;&quot;), &quot;0&quot;, &quot;&quot;)))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>End Customer Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_type__c</fullName>
        <label>Service type</label>
        <length>18</length>
        <type>Text</type>
    </fields>
</CustomObject>

example/secondfile/classes/SIOpptyWithoutSharingHelper.cls
public without sharing class SIOpptyWithoutSharingHelper{

    public Boolean CheckDiffSpOpty(ID optyAccount ,String optyFuzzyEndCust,String optyEndCust ,String optyProdName,String optyAccName ,String Address,Date dt,String stageValue){
     List<Opportunity> Optylist = new List<Opportunity>();
     Optylist = [Select Id,Deal_Reg_Discount_Percentage__c, Account_Name__c, Service_type__c, EndCustomerName__c,End_Customer_Name__c, End_Customer_Address__c, EndCustomerCity__c, EndCustomerState__c, EndCustomerZip__c from Opportunity where AccountId != :optyAccount and ((End_Customer_Name__c = :optyFuzzyEndCust) or (EndCustomerName__c = :optyEndCust)) and Service_type__c = :optyProdName and Deal_Reg_Approval_Date__c > :dt and stageName not in(:stageValue) and End_Cust_Address__c =: Address order by Deal_Reg_Approval_Date__c ]   ;
     System.debug('Optylist ------------'+Optylist );
     if(Optylist != null && Optylist.size() > 0){
         return true;
     }  
     else{
         return false;
     }          
    }
}