example/secondfile/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Credit_Check_Status__c</fullName>
        <label>Credit Check Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Credit Check Review</fullName>
                </value>
                <value>
                    <fullName>Credit Check Failure Resolved</fullName>
                </value>
                <value>
                    <fullName>Credit Check Approved</fullName>
                </value>
                <value>
                    <fullName>Credit Check Denied</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

secondfile/objects/Rome_Opportunity__c.object
<CustomObject>
    <fields>
        <fullName>Credit_Check_Result__c</fullName>
        <label>Credit Check Result</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity Name</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Rome_Opportunitys</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>ROME Opportunity</label>
    <nameField>
        <label>Rome Opportunity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ROME Opportunities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

secondfile/classes/SIROMEOpportunityTriggerHandler.cls
/**
* Class/Trigger  Name: SIROMEOpportunityTriggerHandler
* Author: Accenture
* Date: 29-May-2013
* Requirement # R-2123 
* Description: This is the trigger for ROMEOpportunity object
* Version History:1.1
*/

public with sharing class SIROMEOpportunityTriggerHandler extends SITriggerOperations.SITriggerImpl
{
	public override boolean onAfterUpdate(SObject[] oldObjects, SObject[] updatedObjects, Map<Id, SObject>  newObjectsMap) 
	{
		
        try 
        {
        	updateOpportunityCreditCheckStatus(oldObjects,updatedObjects);
        	
        }catch(Exception excep)        	
        {
            System.debug('Exception Caught :'+excep.getMessage()); 
			return false;
			throw excep;      
        } 
          return true; 	
     }
     
     // This function is to update the Credit Check Status Field.
     public void updateOpportunityCreditCheckStatus(SObject[] oldObjects, SObject[] updatedObjects)
     {
     	List <Rome_Opportunity__c> oldList= oldObjects;
     	List <Rome_Opportunity__c> newList= updatedObjects;
     	map<Id,String> optyMap= New map<Id,String>();
     	set<id> optyIdSet= New set <id>(); 
     	for(integer i=0;i<oldList.size();i++)
     	{
     		if(oldList[i].Credit_Check_Result__c!=newList[i].Credit_Check_Result__c)
     		{
     			optyMap.put(newList[i].Opportunity_Name__c,newList[i].Credit_Check_Result__c);
     			optyIdSet.add(newList[i].Opportunity_Name__c);    			
     		}
     	}
     	List <Opportunity> optyList= [select Id, Credit_Check_Status__c from Opportunity where Id IN:optyIdSet];
     	for(integer i=0;i<optyList.size();i++)
     	{
     		if((SIConstants.PASS).equalsIgnoreCase(optyMap.get(optyList[i].Id)))
     		{
     			optyList[i].Credit_Check_Status__c=SIConstants.CREDIT_CHECK_PASSED;
     		}
     		else if((SIConstants.FAIL).equalsIgnoreCase(optyMap.get(optyList[i].Id)))
     		{
     			optyList[i].Credit_Check_Status__c=SIConstants.CREDIT_CHECK_FAILED;
     		}
     	}
     	update optyList;
     }
}